### ISSUE TITLE
Insufficient Balance <Add points> Buy NFT

### ISSUE THREAD

**Issue by StefanB90** [Pylons-tech/pylons#1005]
## Summary

![Screen Shot 2022-09-08 at 10 28 12 AM](https://user-images.githubusercontent.com/97635071/189148725-3e4242c6-3eb5-4948-b14c-153452f21b92.png)

## Problem Definition

There are too many steps/screens in the Insufficient Balance scenario and we must simplify this process in order to alleviate any obstacles in the user's journey to buy a NFT when they don't have enough points in their account to purchase it immediately.

## Proposal

Simplifying the UX flow in the event that a person wishes to purchase a NFT using points, but does not have enough points in their Wallet to complete the transaction. In that scenario, the Add points button would appear instead of the swipe right to purchase toggle. Once they add enough points to bring their balance up to the required amount to purchase the NFT, they will automatically be taken back to the Trade Summary screen for that specific NFT they originally wanted to purchase, but instead of the Add points button the Swipe right to purchase toggle will be displayed.
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by MikeSofaer** [comment]
This looks great and is high priority!

**Comment by StefanB90** [comment]
Please note that in the design I provided the Edition Number actually changed from #4 to #5 because during the time in which the user left the Trade Summary screen to add more points to buy this NFT, the #4 edition was purchased by a different person.. 

My question is when they get to the Trade Summary screen do they have a set amount of time during which that specific edition is reserved for them in the event they have to go add more funds (be it points or a different currency we support in the future) to complete the transaction?

CC @MikeSofaer @mustafapylons @faisalnaveedRNS @kjawadDeveloper2 @afti-githobo @Tanyaml

**Comment by MikeSofaer** [comment]
We don't have a reservation system of that kind. If it sells out you could probably get a refund on the points though

**Comment by kjawadDeveloper2** [comment]
Updated the design. Will be sending a release tomorrow.

**Comment by StefanB90** [comment]
ready for testing @Tanyaml 

please close if working as expected. Thank you.

**Comment by faisalnaveedRNS** [comment]
@ahmadrns Please review latest design

**Comment by faisalnaveedRNS** [comment]
@ahmadrns will resolve this issue

**Comment by ahmadrns** [comment]
@Tanyaml  Can you kindly share the node of Figma to refactor the screen according to that design.

**Comment by faisalnaveedRNS** [comment]
@StefanB90 we need to discuss about pylons fee 
![image](https://user-images.githubusercontent.com/52915069/196657967-51bffaa9-303e-432d-982c-0c76044fe146.png)

**Comment by MikeSofaer** [comment]
Really we should redesign this to show fee to the seller when they list, and not to the buyer at all.
