### ISSUE TITLE
QR code not working as expected

### ISSUE THREAD

**Issue by StefanB90** [Pylons-tech/pylons#1006]
## Summary of Bug

QR code doesn't work since other wallets don't have a way to view our NFT from their side. QR code should point to recipe (NFT listing if available for sale) so user who scanned QR code can purchase a different edition of the same NFT the QR code is associated with.

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by Tanyaml** [comment]
This ticket does not give exact details.  new ticket is #1015
