### ISSUE TITLE
When user is sharing QR code - Error Occurs

### ISSUE THREAD

**Issue by Tanyaml** [Pylons-tech/pylons#1015]
When user is sharing QR code - Error Occurs 
When user is sharing QR code from their collection under MY PURCHASES --->The User who want to purchase NFT then scans NFT and  is sent to the Pylons wallet which then views NFT but they can't purchase the NFT it just shows up as NFT.

note from Stefan:
QR code doesn't work since other wallets don't have a way to view our NFT from their side. QR code should point to recipe (NFT listing if available for sale) so user who scanned QR code can purchase a different edition of the same NFT the QR code is associated with.

Please see video:

https://user-images.githubusercontent.com/93543576/189223949-96ad8981-e33f-412f-a7b5-1a34bbeb1d93.mov

## Version
1.1.2 (4)
iPhone 11

## Steps to Reproduce
1. Android User- Sharing UNDER MY PURCHASES NFTs QR code 
![Artist Sharing QR Code ](https://user-images.githubusercontent.com/93543576/189222010-255abd12-fee0-427b-bf39-9e1c3eada87b.png)
2.iOS User- Customer who wants to purchase NFT scans the NFT and is directed to Pylons Wallet and is only able to view NFT- no option to buy.

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by kjawadDeveloper** [comment]
I dont think its an issue. You  are trying to share the QR of an item not a recipe. Only recipe can be purchased for now. Not item.

**Comment by kjawadDeveloper** [comment]
If you want to sell an item that you own you need to create a trade.

**Comment by MikeSofaer** [comment]
The QR code should still go somewhere.

I would like an easy way to show people Lux Floralis so they can buy it, but I can figure it out. But a QR code that goes to wallet home page is confusing!

**Comment by Tanyaml** [comment]
@kjawadDeveloper This issue is not resolved- please see video: NFT that is purchased and shared with QR code is still not purchasable.

Android:

https://user-images.githubusercontent.com/93543576/189687422-83c1d874-fde0-4b50-87f9-160c30a43334.mov





iOS:



Uploading iOS #1015 Invaild.mov…

**Comment by Tanyaml** [comment]
The QR code is working as expected for both Android and iOS  for the NFT that is purchased and shared with QR code is now available to be purchased.

Please see videos:

iOS:

https://user-images.githubusercontent.com/93543576/189761752-ba5cbeee-085a-421b-a171-47bb4516a95e.mov

Android:

https://user-images.githubusercontent.com/93543576/189761984-5413eae8-01f2-43fb-ab07-1636a8e39544.mov
