### ISSUE TITLE
ADD: German & Spanish i18n to Easel

### ISSUE THREAD

**Issue by heyitsjk** [Pylons-tech/pylons#1016]
## Summary

Add Spanish & German i18n JSON's to Easel.

[de-DE.txt](https://github.com/Pylons-tech/pylons/files/9530698/de-DE.txt)
[es-ES.txt](https://github.com/Pylons-tech/pylons/files/9530699/es-ES.txt)

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by kjawadDeveloper2** [comment]
Done.

**Comment by Tanyaml** [comment]
@kjawadDeveloper2 

The German Language should be displayed as German- DE 
As for the Screens in Easel the following needs to be fixed

For both Spanish & German Screens need to be translated in the language 

**NFT Details** 
Give your NFT a name
Your Name as the artist 
Describe your NFT
Hashtags.

**NFT Price** 
Price
Royalties
Number of editions


German Language:
Uploading Lang- German Invaild.mov…


Spanish Language:

Uploading Spanish Language Invaild .mov…

**Comment by Tanyaml** [comment]
This is working as expected

**Comment by Tanyaml** [comment]
This is working as expected.

Please see video:

Spanish Language::
https://zube.io/files/pylons/b181a63e0561927c2845e71fc3f23838-spanish-lang-validate.mov


German Language:
