### ISSUE TITLE
REMOVE: "my nft" from Pylons i18n

### ISSUE THREAD

**Issue by heyitsjk** [Pylons-tech/pylons#1024]
## Summary

Per updated design request from @MikeSofaer, let's make the "my_nft" key blank for now for all languages.

_pylons/wallet/i18n/_
Line 282: "my_nft": "my nft",

Expected:
Line 282: "my_nft": " ",
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by Tanyaml** [comment]
I have validated the "my_nft" key blank for now for all languages and is as expected.
