### ISSUE TITLE
Recipe has counter/limit for items that can be minted should be moved to cookbook on the chain.

### ISSUE THREAD

**Issue by mustafapylons** [Pylons-tech/pylons#1034]
## Summary
Recipe has counter how many items can be minted. (limit in a recipe).
We would like to store this data in cookbook object on the chain that can be accessed from recipes which in
turn would allow recipe execution to increase the number of items minted.

## Proposal

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by StefanB90** [comment]
@faisalnaveedRNS please research how to implement this request. Thank you.

**Comment by faisalnaveedRNS** [comment]
@StefanB90  there are multiple recipes of cookbook, if we move limit to cook book, cook book will not be able to understand which limit is for which recipe.

**Comment by MikeSofaer** [comment]
> @StefanB90 there are multiple recipes of cookbook, if we move limit to cook book, cook book will not be able to understand which limit is for which recipe.

This is the beginning of a more general cookbook data storage paradigm I want to add. So if a recipe has a condition `lux_floralis_sold < 1000` and a result `lux_floralis_sold++` then we have recipe limits that can cross different payment methods.

We also have something that could become more powerful, like `gold_in_mine -= 100` when you do a gold mining recipe, and then the mine can run out. So we can start to have interesting multiplayer situations.

**Comment by StefanB90** [comment]
not required for upgrade to mainnet

**Comment by StefanB90** [comment]
general purpose functionality required as core feature

**Comment by StefanB90** [comment]
PR# 1127

**Comment by StefanB90** [comment]
@faisalnaveedRNS please confirm PR #1127

**Comment by faisalnaveedRNS** [comment]
@AbdulSamad876 Please confirm the dev chain deployment

**Comment by faisalnaveedRNS** [comment]
@mustafapylons need some more discussion on this. Right now in case of multiplayer scenarios we need more information of use case.

**Comment by faisalnaveedRNS** [comment]
@StefanB90 we need discuss the is feature.

**Comment by StefanB90** [comment]
to be completed post-mainnet

core engine redesign to be a new milestone
