### ISSUE TITLE
Adding Additional SKUs

### ISSUE THREAD

**Issue by mustafapylons** [Pylons-tech/pylons#1036]
## Summary
All the SKUs should be as below:

$0.99 - 10 points
$2.99-  30 points
$4.99-  50 points
$9.99-  100 points
$19.99- 200 points
$49.99- 500 points
$99.99 - 1K Points
(Please double check the math).

## Proposal

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by faisalnaveedRNS** [comment]
@kjawadDeveloper2 PR created from my side, please check on mobile side what needed

**Comment by MikeSofaer** [comment]
I would like a 10K, 30k and 100k SKU as well please

**Comment by faisalnaveedRNS** [comment]
@kjawadDeveloper2 please add on IAP side

**Comment by kjawadDeveloper2** [comment]
@MikeSofaer @mustafapylons @heyitsjk  the above skus doesnt contain bonus is it removed ?

**Comment by heyitsjk** [comment]
from Josh: 

"The three packages that we want the app to show are:
10 for $0.99
65 for $5.99
110 for $9.99

The app should show those three, the others are being added without a price decided by us yet.
The next chain update should have all of them though."

**Comment by faisalnaveedRNS** [comment]
@heyitsjk do we need to all bonus on all others

**Comment by heyitsjk** [comment]
that is a @MikeSofaer/Josh question if we want bonus ones on every SKU

**Comment by MikeSofaer** [comment]
In my opinion bonuses should be handled by us in the app/console, by repricing the SKUs. From the chain's perspective the SKU should reflect the points issues exactly.
