### ISSUE TITLE
Previewing Content, NFTs that are not purchased yet.

### ISSUE THREAD

**Issue by mustafapylons** [Pylons-tech/pylons#1037]
## Summary
A thumbnail of a content that's a preview of it should be visible to users that haven't purchased the NFT yet.

## Proposal

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by faisalnaveedRNS** [comment]
@kjawadDeveloper2 need to discuss

**Comment by StefanB90** [comment]
not must have for mainnet
