### ISSUE TITLE
Delete all references to Pylons USD

### ISSUE THREAD

**Issue by StefanB90** [Pylons-tech/pylons#1045]
## Summary of Bug

Prep for mainnet 

## Steps to Reproduce

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by MikeSofaer** [comment]
There's no such this as Pylons USD yet! (soon maybe). We want to reset all StripeUSD balances to 0 so that we can make it real money.

**Comment by nghuyenthevinh2000** [comment]
> There's no such this as Pylons USD yet! (soon maybe). We want to reset all StripeUSD balances to 0 so that we can make it real money.

Yep, the code for burning all stripe USD is ready along side redistribute bedrock.

**Comment by StefanB90** [comment]
duplicate of Issue #1056
