### ISSUE TITLE
feat(pylons): change iap options from hard coded to gov

### ISSUE THREAD

**Issue by nghuyenthevinh2000** [Pylons-tech/pylons#1051]
## Summary

currently, iap options are hardcoded to 3 options. However, this should be changeable through governance

- [ ] determine where is this?

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by nghuyenthevinh2000** [comment]
@faisalnaveedRNS 
I heard something about these iap options which are hardcoded to chain from Mike. But I don't know exactly where it is. Would you be able to provide clarity on this.

@ThanhNhann 
he will be handling this logic.

If possible, I would love to join in a quick call.

**Comment by StefanB90** [comment]
we have a different issue to add additional SKUs to our IAP.. can we do this without a chain upgrade?

**Comment by mustafapylons** [comment]
Based on @nghuyenthevinh2000 comment. this can be pushed to post mainnet.
