### ISSUE TITLE
multi-sig work for mainnet

### ISSUE THREAD

**Issue by StefanB90** [Pylons-tech/pylons#1052]
## Summary

In preparation for mainnet, we need to add pylon hyperlink to the website. We also need wallets.

## Proposal

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by nghuyenthevinh2000** [comment]
I understand that I will add this hyperlink: "https://www.pylons.tech/home/" to the multisig website?

**Comment by MikeSofaer** [comment]
I think maybe this ticket was supposed to be making sure that the multisig website works for Pylons, given the account creation etc differences.

**Comment by nghuyenthevinh2000** [comment]
> I think maybe this ticket was supposed to be making sure that the multisig website works for Pylons, given the account creation etc differences.

you mean refactoring for:
1. domain name
2. logo
3. logic to support Pylons only (transactions)
4. hyperlink to https://www.pylons.tech/home/ on pylons - specific multisig tool

Do I understand this correctly?

**Comment by MikeSofaer** [comment]
I don't really know, we don't expect anyone but us to use it, so I don't think we need to do a lot of cosmetics. I want to make sure it actually works for moving Bedrock.

**Comment by mustafapylons** [comment]
According to @nghuyenthevinh2000, we will get the link and this is in place.

**Comment by sontrinh16** [comment]
yeah just add the link in the select chain button
![Screenshot 2022-09-23 002556](https://user-images.githubusercontent.com/48055119/191812473-12dcab86-b79d-45bd-be9f-c62845f1fe98.png)

![Screenshot 2022-09-23 002509](https://user-images.githubusercontent.com/48055119/191812338-372236ab-6b15-44c6-85fe-6a18b8e0f426.png)

**Comment by StefanB90** [comment]
can send transactions over CLI but when on Keplr doesn't work.

**Comment by StefanB90** [comment]
can't deploy mainnet unless we have bedrock in the right multi-sig accounts. currently building flutter wallet for web. Will have to use CLI for now

**Comment by nghuyenthevinh2000** [comment]
https://github.com/Pylons-tech/pylons/issues/1169

**Comment by nghuyenthevinh2000** [comment]
https://github.com/Pylons-tech/pylons/issues/1175

**Comment by abdullahjankhan1** [comment]
Web wallet PR https://github.com/Pylons-tech/pylons/pull/1145

**Comment by nghuyenthevinh2000** [comment]
this is left to post mainnet

**Comment by nghuyenthevinh2000** [comment]
This can be resumed once more

**Comment by sontrinh16** [comment]
the keplr problems was fix, can we deploy the fixed version to finish up testing multisig with keplr

**Comment by nghuyenthevinh2000** [comment]
Let's call it v1.0.0 - rc4
