### ISSUE TITLE
Clean upylons

### ISSUE THREAD

**Issue by ThanhNhann** [Pylons-tech/pylons#1056]
## Summary
Clean upylons for mainnet

## Problem Definition
To prepare for mainnet, I want to know the condition for burn upylons

## Proposal

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by ThanhNhann** [comment]
Hi @MikeSofaer, @StefanB90. I got the task clean upylons to prepare for mainnet, but don't know the detail about the conditions to burn it. Can you list more about this for me

**Comment by MikeSofaer** [comment]
burning upylons is a signal to Pylons Inc that we should pay the person the cash represented by the pylons. An artist or game developer who has been KYCed can burn Pylons, and let us know the transaction ID, and we can pay them off chain

**Comment by ThanhNhann** [comment]
Can you list in detail the cases we should burn by the bullet points? Im confusing about your comment, Im understanding that burning mean that we have to burn upylons of addresses of artist or game developer who has been KYCed and all addresses created before our first paid event (created without IAP) @MikeSofaer

**Comment by MikeSofaer** [comment]
Yes, I'm making a distinction between removing them in the upgrade handler now, and a burn transaction that people can do with them later.

For this upgrade all pylons created without IAP must be removed

Later people with KYC can burn Pylons to be paid for them by Pylons, Inc. (sort of a reverse of IAP minting)

Two different things.

**Comment by Tanyaml** [comment]
Not ready for 9/23.

**Comment by nghuyenthevinh2000** [comment]
Just check the commit, the test needs to add:
1. 3 addresses with 100 pylons
2. in which 1 address has 30 valid pylons
3. the test should expect after cleaning upylons, only 1 address with 30 valid pylons remain

Otherwise, the code looks very good.

@Tanyaml this can be done by tomorrow

**Comment by nghuyenthevinh2000** [comment]
looking good
