### ISSUE TITLE
DALL·E 2 <Easel> text-to-NFT generator

### ISSUE THREAD

**Issue by StefanB90** [Pylons-tech/pylons#1063]
## Proposal

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by MikeSofaer** [comment]
lol

This might want to be its own app, we could use StableDiffusion, and charge Pylons Points for generating the images
