### ISSUE TITLE
Buy for 0 NFT invalid-  For Free NFT Drop

### ISSUE THREAD

**Issue by Tanyaml** [Pylons-tech/pylons#1074]
## Summary of Bug
When user is claiming free NFT- button to buy should be stated "Claim Free NFT" @StefanB90 please advise. 
As of now it said Buy for Free when you land on Big Dipper and then when you are directed to Pylons to purcahse Buy for 0 with the pylons icon 

Please see video:

https://user-images.githubusercontent.com/93543576/190669697-81b98875-5e2a-45c0-a1bf-82b3ab0622a2.mov

 it states 0 NFT and that just isn't logical.

## Steps to Reproduce

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by StefanB90** [comment]
![Screen Shot 2022-09-21 at 9 42 40 PM](https://user-images.githubusercontent.com/97635071/191639890-be6fb762-586f-43f1-8608-d2adda9abda1.png)

CC @kjawadDeveloper2 @Tanyaml @xinya

**Comment by Tanyaml** [comment]
@faizhashmiRnS  When user is claiming Free NFT only in Big Dipper first you still still see  "Buy for Free"
Note: it is working as expected when user is in Pylons App- it states "Claim Your Free NFT"

Please see video:

https://user-images.githubusercontent.com/93543576/192635596-57b94ab1-7a33-4b79-a570-08a63dd3ef1c.mov

**Comment by faizhashmiRnS** [comment]
> @faizhashmiRnS When user is claiming Free NFT only in Big Dipper first you still still see "Buy for Free" Note: it is working as expected when user is in Pylons App- it states "Claim Your Free NFT"
> 
> Please see video:
> 
>  Invaild.BD.Flow.mov

Hi @Tanyaml , 
I guess @faisalnaveedRNS Sir can look into the BigDipper side of this issue.

**Comment by kjawadDeveloper2** [comment]
@Tanyaml  can you confirm this?

**Comment by Tanyaml** [comment]
@kjawadDeveloper2  this is a Big Dipper issue as mentioned in my comment.

**Comment by kjawadDeveloper2** [comment]
So this should go to faisal team . Removing mobile team from this ticket. @StefanB90  @mustafapylons

**Comment by heyitsjk** [comment]
I feel like if we just print the text "Buy For" in the price line (Lines 727 & 1069) and then change the "Free" text on Lines 723 &  1068 to "Claim For Free" this could be an easy fix to close this.

_pylons/big-dipper/imports/ui/easel_buy/EaselBuy.jsx_ 
![Screen Shot 2022-10-20 at 10 10 15 AM](https://user-images.githubusercontent.com/74597290/197014460-244b9156-79b6-4697-bd05-6c60c4c77765.png)

**Comment by Tanyaml** [comment]
@faisalnaveedRNS This is still not working as expected. @StefanB90 please advise.

As of now the for the Owners View  it shows 0 Pylons- is that valid?

As for buyer when they are in iOS they land on the first screen which is shows BUY FOR FREE- technically that makes no sense.

Please see screenshots:
Owners View- O PYLONS
![image.png](https://zube.io/files/pylons/bc05f7398815f655f1398db4ca909309-image.png) 

Buyers View: Buy For Free
![image.png](https://zube.io/files/pylons/dd47ef340af38548fc3d06f5b2384373-image.png)
