### ISSUE TITLE
restrict the ability to create new address on mobile app only

### ISSUE THREAD

**Issue by GNaD13** [Pylons-tech/pylons#1082]
## Summary
restrict the ability to create new address on mobile app only

## Proposal

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by MikeSofaer** [comment]
> Hi @MikeSofaer, I got the task to restrict the ability to create new address on mobile app only. Can you please give me the detail of this task please? @nghuyenthevinh2000
> 
> Or who should I ask?

create_account requests should be rejected if they do not have a correct and unique AppCheck token from Firebase. This will prevent people from creating large numbers of fake accounts from their consoles.

**Comment by GNaD13** [comment]
> > Hi @MikeSofaer, I got the task to restrict the ability to create new address on mobile app only. Can you please give me the detail of this task please? @nghuyenthevinh2000
> > Or who should I ask?
> 
> create_account requests should be rejected if they do not have a correct and unique AppCheck token from Firebase. This will prevent people from creating large numbers of fake accounts from their consoles.

Hi sir, I found that create_account requests already have func to check token name verifyAppCheck.
![image](https://user-images.githubusercontent.com/89174180/191036484-f10b569c-7cfe-4750-8f26-7895517d4c9b.png)
Should we need another way to do this?

**Comment by afti-githobo** [comment]
> I know that @afti-githobo was able to create accounts from the command line, so I thought what we were doing was not applied to all transactions.

I was, at one point. It... might have changed in recent weeks? idk; i can check against current main later today

**Comment by GNaD13** [comment]
> > I know that @afti-githobo was able to create accounts from the command line, so I thought what we were doing was not applied to all transactions.
> 
> I was, at one point. It... might have changed in recent weeks? idk; i can check against current main later today

Hi sir @afti-githobo, can you give me the testing case please?

**Comment by afti-githobo** [comment]
make a keypair, run `pylonsd tx pylons create-account [username] [token] [referralAddress] [flags]` with a new username --from that keypair

referral address can be the address of any existing account

token can (if this has not been fixed) be literally any string

**Comment by GNaD13** [comment]
Hi sir @afti-githobo, I have tested with the last version of pylons, everything is ok (we can't create account in CLI). Can you re-check the problem please?

**Comment by mustafapylons** [comment]
@nghuyenthevinh2000, @afti-githobo will check it on 9/21, will let you know.

**Comment by GNaD13** [comment]
@mustafapylons, have you checked this problem? Is it ok?

**Comment by nghuyenthevinh2000** [comment]
@afti-githobo 
can you return your comment on this pr please

**Comment by afti-githobo** [comment]
`Error: error unmarshalling: invalid character '<' looking for beginning of value`

got this when trying to broadcast. it... might be fixed? or it might not? but either way this shouldn't be happening, right? seems like we're trying to unmarshal something that shouldn't be unmarshaled?

**Comment by GNaD13** [comment]
> `Error: error unmarshalling: invalid character '<' looking for beginning of value`
> 
> got this when trying to broadcast. it... might be fixed? or it might not? but either way this shouldn't be happening, right? seems like we're trying to unmarshal something that shouldn't be unmarshaled?

I think this should be the different issue... Idk...
This is my testing detail
**Step to take**
1. Deploy test node
2. Add a new keys for testing
Run cmd:
`pylonsd keys add testaccount --keyring-backend test`
Responses
```
- address: pylo1jqmzd3t87rflre6anzjt7fmtwdag33g7mwqewz
  name: testaccount
  pubkey: '{"@type":"/cosmos.crypto.secp256k1.PubKey","key":"A/tYHB2OPHZEKT4p7HuKc728an3aqANqVLGb5stmHuws"}'
  type: local


**Important** write this mnemonic phrase in a safe place.
It is the only way to recover your account if you ever forget your password.

million ladder eight security check name fish sudden anxiety pizza tongue absent floor together wage file client liberty unaware thank sting bundle pudding faith
```
![image](https://user-images.githubusercontent.com/89174180/191871503-188f78b8-0710-487d-9e43-44e1ac03580b.png)

3.  Send tx create-account
Run cmd:
`pylonsd tx pylons create-account test token validator --from testaccount --keyring-backend test --chain-id pylons-testnet`
Respone
```
{"body":{"messages":[{"@type":"/pylons.pylons.MsgCreateAccount","creator":"pylo1jqmzd3t87rflre6anzjt7fmtwdag33g7mwqewz","username":"test","token":"token","referral_address":"validator"}],"memo":"","timeout_height":"0","extension_options":[],"non_critical_extension_options":[]},"auth_info":{"signer_infos":[],"fee":{"amount":[],"gas_limit":"200000","payer":"","granter":""},"tip":null},"signatures":[]}

confirm transaction before signing and broadcasting [y/N]: y
code: 0
codespace: ""
data: ""
events: []
gas_used: "0"
gas_wanted: "0"
height: "0"
info: ""
logs: []
raw_log: '[]'
timestamp: ""
tx: null
txhash: C9FBF6F7684C9BF1A1CCFCE59CB96F45BE3DAE14CB16410BA9DEF6E1A74EFD29
```
![image](https://user-images.githubusercontent.com/89174180/191871531-db81e942-e78f-4cfb-9ba2-3dffa01a9eb9.png)

4. Check the tx detail with the txhash
Run cmd:
`pylonsd q tx C9FBF6F7684C9BF1A1CCFCE59CB96F45BE3DAE14CB16410BA9DEF6E1A74EFD29`
Response:
```
code: 18
codespace: sdk
data: ""
events:
- attributes:
  - index: true
    key: YWNjX3NlcQ==
    value: cHlsbzFqcW16ZDN0ODdyZmxyZTZhbnpqdDdmbXR3ZGFnMzNnN213cWV3ei8w
  type: tx
- attributes:
  - index: true
    key: c2lnbmF0dXJl
    value: U3dtZUdKZzNhR2FWQWV3Y1E1NHJDK1ZZRDYzY1YxcE0xQnB6QXFtcWwxSVh0aC9DVzdLUWJjN2xzOGRabkpJckI0Z2hOOVN1R1pwanozUGZ1SU5NUEE9PQ==
  type: tx
gas_used: "42338"
gas_wanted: "200000"
height: "15"
info: ""
logs: []
raw_log: 'failed to execute message; message index: 0: rpc error: code = Unauthenticated
  desc = unable to verify app-check token failed to parse token. token contains an
  invalid number of segments: invalid request'
timestamp: "2022-09-22T23:40:25Z"
tx:
  '@type': /cosmos.tx.v1beta1.Tx
  auth_info:
    fee:
      amount: []
      gas_limit: "200000"
      granter: ""
      payer: ""
    signer_infos:
    - mode_info:
        single:
          mode: SIGN_MODE_DIRECT
      public_key:
        '@type': /cosmos.crypto.secp256k1.PubKey
        key: A/tYHB2OPHZEKT4p7HuKc728an3aqANqVLGb5stmHuws
      sequence: "0"
    tip: null
  body:
    extension_options: []
    memo: ""
    messages:
    - '@type': /pylons.pylons.MsgCreateAccount
      creator: pylo1jqmzd3t87rflre6anzjt7fmtwdag33g7mwqewz
      referral_address: validator
      token: token
      username: test
    non_critical_extension_options: []
    timeout_height: "0"
  signatures:
  - SwmeGJg3aGaVAewcQ54rC+VYD63cV1pM1BpzAqmql1IXth/CW7KQbc7ls8dZnJIrB4ghN9SuGZpjz3PfuINMPA==
txhash: C9FBF6F7684C9BF1A1CCFCE59CB96F45BE3DAE14CB16410BA9DEF6E1A74EFD29
```
The tx detail show that the create-account do not success with the log desc: unable to verify app-check token failed to parse token
5. Re-check with the query account
Run cmd:
`pylonsd q pylons get-address-by-username test`
Where `test` is the username that I create in the create-account cmd
Responese
`Error: rpc error: code = InvalidArgument desc = rpc error: code = InvalidArgument desc = not found: invalid request`
![image](https://user-images.githubusercontent.com/89174180/191871933-014b9d8d-ff37-4b20-b218-89836a40a8ca.png)

This is my all testing detail. Can you guys check my testing please? @MikeSofaer @mustafapylons @afti-githobo @nghuyenthevinh2000

**Comment by afti-githobo** [comment]
> This is my all testing detail. Can you guys check my testing please? @MikeSofaer @mustafapylons @afti-githobo @nghuyenthevinh2000

That all seems incredibly robust; well done. I think there's just a separate issue on my end. Probably config.
