### ISSUE TITLE
Zoom level of image view within Big Dipper invalid 

### ISSUE THREAD

**Issue by Tanyaml** [Pylons-tech/pylons#1089]
## Summary of Bug
When User Purchases NFT and clicks on shared link, User is directed to Big Dipper and this is where the image is not valid, Image is zoomed in this only happening on BD.

Please see screenshot and video:
![image](https://user-images.githubusercontent.com/93543576/191082350-bd18a46f-99ba-486a-819b-ab410dc07047.png)

https://user-images.githubusercontent.com/93543576/191082736-ac6eb4c3-047d-4431-b119-ad9d8f19ee5e.mov

## Version
Pylons https://we.tl/t-MgA0Xemjtq
Easel https://we.tl/t-PZt8pZ0Tqk 

## Steps to Reproduce
1.User Clicks on shared NFT to purchase:https://wallet.pylons.tech/?recipe_id=Easel_Recipe_auto_recipe_2022_09_13_125805_803&cookbook_id=Easel_CookBook_auto_cookbook_2022_09_13_125802_831&address=pylo1kstu9dgfxjfe33h6jjg8zruneddcecwwj9dd0x
2.User is directed to Big Dipper and views NFT which is zoomed in and not valid.

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by faisalnaveedRNS** [comment]
@Tanyaml If we stretch the image to much, as our previous experience it does not look so great.

**Comment by MikeSofaer** [comment]
The aspect ratio of the image should never change, it is a question of whether some of the image is cut off, or there are black bars around it.
