### ISSUE TITLE
Separate Account Creation and Username Setting

### ISSUE THREAD

**Issue by MikeSofaer** [Pylons-tech/pylons#1119]
Choosing a username is a major bump in the onramp, especially for people who are looking to buy a particular piece of art. Users who have entered the system to buy a particular piece should not be required to select a username before purchasing Pylons Points or items.

To enable this, the `create_account` transaction should not require a username, and there should be an additional `set_username` transaction

## Proposal

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by StefanB90** [comment]
regression testing required.

**Comment by abdullahjankhan1** [comment]
PR# https://github.com/Pylons-tech/pylons/pull/1165

**Comment by faisalnaveedRNS** [comment]
@MikeSofaer do we need this feature urgently

**Comment by MikeSofaer** [comment]
I wouldn't hold up this upgrade for it, but it's a big blocker for meaningful adoption and iteration of the user experience.
