### ISSUE TITLE
Should display price in USD in addition to Pylons points for better usability.

### ISSUE THREAD

**Issue by mustafapylons** [Pylons-tech/pylons#1120]
## Summary
Should display price in USD in addition to Pylons points for better usability.

## Proposal

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by StefanB90** [comment]
Please let me know if you have any questions @kjawadDeveloper2 

![image](https://user-images.githubusercontent.com/97635071/191850063-7942c6f1-cf1f-4b15-8ea4-77b9f306bdfb.png)


Thank you.

**Comment by kjawadDeveloper2** [comment]
@mustafapylons 1 pylons is equal to how much dollars?

**Comment by MikeSofaer** [comment]
0.10 dollars per pylon
