### ISSUE TITLE
increase block slash (mainnet)

### ISSUE THREAD

**Issue by GNaD13** [Pylons-tech/pylons#1129]
## Proposal

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by GNaD13** [comment]
Hi sir @MikeSofaer, I just got new task for mainnet which is increase block slash. Can you give me the detail of this task please?
Or who should I ask?
@nghuyenthevinh2000

**Comment by MikeSofaer** [comment]
Please ask @faddat

**Comment by GNaD13** [comment]
Hi sir @faddat. Can you give me the detail of this task please?
