### ISSUE TITLE
Marketing Wallet on Purchase

### ISSUE THREAD

**Issue by MikeSofaer** [Pylons-tech/pylons#1130]
## Summary

We need a way to give money to platforms like OpenSea or galleries when they sell art

## Problem Definition

There is no easy way to promote your work on Pylons, and no native way to pay for promotional help. We would like to be able to have promoters and also be able to list work on platforms, and have them get paid.

## Proposal

Recipe execution and trade transactions can have a field for "affiliate_wallet". If there is a wallet in that field, 2.5% of the tokens moved go to that wallet instead of to the Bedrock holders. (So instead of 10% to Bedrock holders it should be 7.5% to Bedrock holders and 2.5% to the affiliate wallet)

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by heyitsjk** [comment]
Let's track this via Firebase too, if possible.
