### ISSUE TITLE
ADD: Firebase Analytics SDK to Easel

### ISSUE THREAD

**Issue by heyitsjk** [Pylons-tech/pylons#1131]
## Summary

Right now, we don't have Firebase Analytics enabled via Firebase on Easel - or, if we do, it's not connected/broken. Let's get this enabled and connected to console for marketing purposes.

We should realistically be able to see the "Realtime" users in the app on Firebase Console + their activity within the app.

It should also be able to log the bounce between Easel & the main Pylons App in console
SEE: Google Tag Manager 

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by heyitsjk** [comment]
Realistically, it should also be able to log the bounce between Easel & the main Pylons App in console
SEE: Google Tag Manager

**Comment by kjawadDeveloper2** [comment]
@heyitsjk  easel has different firebase project. I will add you in it.
