### ISSUE TITLE
NFT Listing Full Screen View (pylons app)

### ISSUE THREAD

**Issue by StefanB90** [Pylons-tech/pylons#1166]
## Problem Definition

For all NFT Listings (NFTs available for sale)

- Do not show QR code to prospective buyer (only NFT owner can see QR code icon)

- The buy button should look like this on Big Dipper & the Pylons App
![Screen Shot 2022-09-28 at 10 42 14 AM](https://user-images.githubusercontent.com/97635071/192809267-c46d370f-24c0-4839-bf5e-15c46d5cc30e.png)

- The description text should have read more at the end of the second line and expand to 4 lines max

- The buy button should be visible at all times. When you expand one subtab, the other subtabs minimize to ensure that the buy button is always visible.

### Subtabs

**Ownership**
1. Owner
3. Edition Number (this is updated based on how many editions have already been sold)
4. Royalty

**NFT Detail**
1. Recipe ID
2. Resolution which contains the size/dimensions & file type
3. IPFS CID

**History**
1. Most recent transaction (transaction involving the current owner)
2. First transaction (the person who purchased the NFT from the original artist/creator)
3. Creation event (the genesis event involving the NFT artist/creator)

## Proposal

![Screen Shot 2022-09-28 at 10 51 30 AM](https://user-images.githubusercontent.com/97635071/192811516-44b41c04-afa0-420b-b0bc-c768b8384cb2.png)

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by ahmadrns** [comment]
As you mentioned above,  `The description text should have read more at the end of the second line and expand to 4 lines max`

What if user have decription of more than 4 lines what we will do with remainig description do we hide it from user and show only those part which fits in 4 lines? @StefanB90  @kjawadDeveloper2

**Comment by ahmadrns** [comment]
@kjawadDeveloper2  Acknowledged

**Comment by faisalnaveedRNS** [comment]
@kjawadDeveloper2 any comments on this ticket
