### ISSUE TITLE
Error When User is Purchasing Pylons Points 

### ISSUE THREAD

**Issue by Tanyaml** [Pylons-tech/pylons#1176]
## Summary of Bug
When user is purchasing Pylons Points wifi goes off- but still gets confirmation  that they have purchased it with and email from google stating the IAP was successful- the actual Pylon points is not available in the transaction history does not show that the actual point has been purchased, yet there is a Receipt that purchase was successful.

Please see video:

https://user-images.githubusercontent.com/93543576/193082522-ecb8212d-bff5-4107-a0b2-12b05fdc4f84.mov

 

## Version
https://we.tl/t-hMFGkUXagR- from Faiz

## Steps to Reproduce
1. Open Pylons app
2. Go to wallet tab and and click on pylons and user will land on IAP
3. User will select which package they want for the pylon points 
4. User clicks on the 4.99 package and then clicks buy
5. User will disconnect from wifi once green tick is presented.
6. Then checks transaction history and no there is no pylons point purchased- yet there is a receipt from Google.

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by faizhashmiRnS** [comment]
Hi @Tanyaml, Were you able to test this on the build that I have sent you on Friday, 30th of Sep.

**Comment by Tanyaml** [comment]
I have tested and validated this Error When User is Purchasing Pylons Points and now it is working as Expected.
When User is disconnect from wifi once green tick is presented. Then checks transaction history it shows the actual Pylons Points and user can retry to purchase and it is working. 

Please see Video:


Uploading Validated Pylons Point .mov…
