### ISSUE TITLE
When User is Purchasing NFT- When Wifi is disconnected Error Occurs

### ISSUE THREAD

**Issue by Tanyaml** [Pylons-tech/pylons#1177]
## Summary of Bug
When User is Purchasing NFT- When wifi is disconnected for 5 seconds and purchasing is being finalized Error Occurs.
The actual NFT is still purchased but is not found in the Transaction under Menu.
User can view the actual purchase in wallet and then can click to see the actual details and user is able to click View and collections and NFT is available  to preview, but does not show up in Transaction under the Menu tab.

Please see video:

https://user-images.githubusercontent.com/93543576/193123406-3e389d34-7172-4901-8056-0d976cf57354.mov

## Version
 https://we.tl/t-hMFGkUXagR- Faiz Build

## Steps to Reproduce
1.User will click on NFT to purchase https://pylons.page.link/51BUDAj1KvUG7PFV8
2.User will purchase NFT and swipe right to purchase and then Click the wifi to go off.
3.User will then put Wifi back on and see that the actual NFT was purchased in the collection tab
4.User will go to menu and and click on general-->transaction and see that there is no NFT purchase was made.
5.User will go back to wallet and and click on the NFT that was purchased and will be able to see the receipt  and user is able to click View and collections and preview the NFT.

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by faisalnaveedRNS** [comment]
@kamran khan

**Comment by Kamran-Khan-Gene** [comment]
Hi, I am unable to track this issue. I am attaching screen recording from my side. kindly check and let me know if I am following steps properly or not.

https://user-images.githubusercontent.com/115459890/197342462-9251f683-5337-4e66-bf82-43fc0e46292f.mp4

**Comment by faisalnaveedRNS** [comment]
@kjawadDeveloper2 need to discuss this
