### ISSUE TITLE
UPDATE: Official Pylons Documentation 

### ISSUE THREAD

**Issue by heyitsjk** [Pylons-tech/pylons#1184]
## Summary

We should make sure all our official docs are up-to-date before going into mainnet, so that if potential devs want to develop with us they won't run into any hiccups along the way.

https://github.com/Pylons-tech/pylons/tree/main/docs

_Examples: Quick Start guide was updated 12 months ago + Technical Setup lists installing Starport as a requirement but if I remember correctly, we don't use Starport anymore?_ 

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by Tanyaml** [comment]
@kjawadDeveloper2 can you please merge.
