### ISSUE TITLE
UPDATE: Firebase Analytic flow tracking in Wallet

### ISSUE THREAD

**Issue by heyitsjk** [Pylons-tech/pylons#1186]
## Summary

We should also be adding analytic tracking to each screen so we can see where people move through the flow.
https://firebase.google.com/docs/analytics/screenviews#manually_track_screens

Essentially, give each screen a specific name set in FirebaseAnalytics code. Can we add the following:

- Create Key **["account_create"]**
- Main Screen (My Purchases) **["my-purchases_screen"]**
- My Creations **["my-creations_screen"]**
- Wallet **["wallet_screen"]**
- Transactions **["transactions_screen"]**
- Messages **["messages_screen"]**
- NFT Listing Screen **["nft-listing_screen"]**

If we can track windows, then we need them for the "swipe right to pay", "transaction complete", and "view receipt" ones as well.

This request is for Wallet. 
Pylons-tech/pylons#1131 is for Easel. 
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by kjawadDeveloper2** [comment]
@heyitsjk  can we close this?

**Comment by heyitsjk** [comment]
working in iOS Testflight 1.1.3 (10)
