### ISSUE TITLE
***Android Easel- When User is Uploading Half of the Audio Playback Audio box is missing

### ISSUE THREAD

**Issue by Tanyaml** [Pylons-tech/pylons#1187]
## Summary of Bug
When User is Uploading NFT Audio Please see issue below:
1. When User uploads Half of the Audio-playback box is not visible/missing, once user uploads thumbnail then you are able to see playback box.
 
Note: 
1.Audio NFT still uploads and is published
2.When User is in iOS uploading Audio NFT- it is working as Expected.

Please see video:

https://user-images.githubusercontent.com/93543576/193683065-a1fc4cee-507b-4a35-8869-7c1dfb1a0002.mov

## Version
wallet https://we.tl/t-iaRFLd5UH1

## Steps to Reproduce
1.Open Easel
2.Upload Audio NFT and playback the audio
3.User will click play and see playback box is missing.
4.User will then upload NFT thumbnail and then will see playback box. 

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by kjawadDeveloper2** [comment]
@Tanyaml i think this one resolved . Can you confirm?

**Comment by Tanyaml** [comment]
I have validated When User is Uploading  Audio Playback Audio is now working as expecting on Android.

Please see video:


Uploading Validated Audio Playback .mov…
