### ISSUE TITLE
Android Easel- When User is Uploading Video NFT Error 

### ISSUE THREAD

**Issue by Tanyaml** [Pylons-tech/pylons#1197]
## Summary of Bug
Note: Issue only in Android.
There is two issues:

1.When user uploads video and gets error message that the memory exceeds  to long.. and user waits over 2-3 mins to only find out the video is not valid. 

User should receive a message before instead of waiting after 2-3 mins to only find out video is not valid. User should automatically  know that the video is not valid once they try to upload video in the first step of when user is uploading video.

See screenshot for error message:

<img width="401" alt="Screen Shot 2022-10-04 at 4 30 59 PM" src="https://user-images.githubusercontent.com/93543576/193921837-044df80a-40a8-43ba-a09d-b0b98f301fc6.png">

2.Actual Results: Android Easel- When User is Uploading Video NFT Half of the Playback Audio box is missing.

Expected Results: When user is Uploading Video NFT, user should be able to see Playback Audio box  from beginging to end.

Please see video:

https://user-images.githubusercontent.com/93543576/193921643-eeee54b5-cab5-460e-8a34-10355e8b849e.mov

## Version
Latest Build-https://we.tl/t-AQvXloFBte

## Steps to Reproduce
1.Open Easel
2.Upload Video
3.Wait for confirmation for video upload which you will see the video does not upload at all and the playback box for audio is missing.

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by ahmadrns** [comment]
@kjawadDeveloper2  I have debugged this issue when we try to upload a 125MB sized file it uploads the file but when the file size exceeds it throws an error which is `Memory limit would be exceeded before EOF`, so can we restrict users to upload less than 125MB file? 
@kjawadDeveloper2  Is there any file size restriction on IPFS?

**Comment by ahmadrns** [comment]
@kjawadDeveloper2  I have debugged this issue when we try to upload a 125MB sized file it uploads the file but when the file size exceeds it throws an error which is `Memory limit would be exceeded before EOF`, so can we restrict users to upload less than 125MB file? 
@kjawadDeveloper2  Is there any file size restriction on IPFS?

**Comment by faisalnaveedRNS** [comment]
@kjawadDeveloper2 as per discussion we need to setup limit to 1GB

**Comment by kjawadDeveloper2** [comment]
We have changed the limits to 125 mb.

**Comment by faisalnaveedRNS** [comment]
@ahmadrns Please verify and move to testing

**Comment by ahmadrns** [comment]
@faisalnaveedRNS Working as Expected

**Comment by Tanyaml** [comment]
I have validated: When User is Uploading Video and now is working as expected.

Please see video:


Uploading Video NFT Validated.mov…
