### ISSUE TITLE
Ante handler refactoring

### ISSUE THREAD

**Issue by nghuyenthevinh2000** [Pylons-tech/pylons#1212]
during the debug of Pylons-tech/pylons#1191, a lot of issue with Ante Handler is found thank to @faddat 

This ticket will track the the creation of new pr for ante handler refactoring.

This is important for mainnet.

cc @MikeSofaer 
____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by Tanyaml** [comment]
@faisalnaveedRNS  Please review ticket.

**Comment by faisalnaveedRNS** [comment]
I think already merged PR we need to close that ticket @Tanyaml
