### ISSUE TITLE
Test upgrade handler for mainnet

### ISSUE THREAD

**Issue by nghuyenthevinh2000** [Pylons-tech/pylons#1214]
## Summary

Test the upgrade process so that it will be smooth.

@levanhieuhust 
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by ThanhNhann** [comment]
You can write test upgrade like this @levanhieuhust: https://github.com/osmosis-labs/osmosis/blob/main/app/upgrades/v9/upgrade_test.go
