### ISSUE TITLE
Pylons: When User is Creating Wallet Create Key and taps Back Arrow by accident- Invalid Behavior Occurs

### ISSUE THREAD

**Issue by Tanyaml** [Pylons-tech/pylons#1217]
## Summary of Bug
Pylons: When User is Creating Wallet Create Key and taps Back Arrow- Invalid Behavior Occurs
When user creates key name in Pylons, and user taps on the  backward arrow by accident on Create Key Screen  (note: the android back arrow can be tapped easily)- User then lands on White Screen and can not move to next screen, user must kill app and open Pylons App again  to Create Key name.

Please see video:

https://user-images.githubusercontent.com/93543576/194175798-820b74bf-ebc2-48a4-8b34-d13a9115323a.mov

## Version
https://we.tl/t-SknBhFyoUZ- Latest Wallet Build from Jawad

## Steps to Reproduce
1.User opens Pylons App
2.User is on Creates Key Screen
3.User taps back arrow by accident since the back arrows on the android phone is sensitive  and lands on White Screen
4.User can not move back to Create screen and has to kill app
5.User re-opens Pylons app and tries to create key once again

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by kjawadDeveloper2** [comment]
@Tanyaml kindly test.

**Comment by Tanyaml** [comment]
@StefanB90 as of now when user taps back button now it just leaves out of the app- is this how it is supposed to work? Thoughts?
Please advise.

Please video:



Uploading BackScreen Testing.mov…

**Comment by faisalnaveedRNS** [comment]
@Tanyaml please test

**Comment by heyitsjk** [comment]
@Tanyaml pressing the back button and it putting you on the device home screen is the same flow Easel has so I presume this would be the correct behavior now.

**Comment by Tanyaml** [comment]
@heyitsjk it is semi-correct for now it works. Also Based on our Scrum call- this flow works for now and I will be closing this ticket.
