### ISSUE TITLE
Pylons- When user is tapping 3D NFT Screen Error Occurs

### ISSUE THREAD

**Issue by Tanyaml** [Pylons-tech/pylons#1225]
## Summary of Bug
 When user is Tapping 3D NFT Screen Error Occurs-  The screen turns white when tapping on the screen and then you land on 3D NFT.

## Version
https://we.tl/t-ScVeFjeYX1

## Steps to Reproduce
1. User will open 3D NFT- https://pylons.page.link/buZnJbAGGDk6f9Yj9
2. User Will see the screen glitch and turn white and then land on 3D NFT.

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

https://user-images.githubusercontent.com/93543576/194419032-1034be30-97f6-40d0-9784-7fb22c74ab0d.mov

**Comment by ahmadrns** [comment]
The issue you mentioned above `When a user is Tapping 3D NFT Screen Error Occurs- The screen turns white when tapping on the screen and then you land on 3D NFT`

 This is the library's own loading style, so we have to fork the library and edit it according to our own needs @kjawadDeveloper2

**Comment by kjawadDeveloper2** [comment]
@Tanyaml kindly test.

**Comment by faisalnaveedRNS** [comment]
@ahmadrns Please review

**Comment by faisalnaveedRNS** [comment]
@kjawadDeveloper2 suggestion is to set initial background as black.

**Comment by faisalnaveedRNS** [comment]
@ahmadrns

**Comment by ahmadrns** [comment]
https://github.com/Pylons-tech/pylons/pull/1252

**Comment by faisalnaveedRNS** [comment]
@ahmadrns NFT is now semi-working as expecting- although now if you look at the 3D NFT there is a white that starts from the bottom to right of the 3D NFT please see video

**Comment by faisalnaveedRNS** [comment]
<img width="413" alt="Screen_Shot_2022-10-19_at_3 07 43_PM" src="https://user-images.githubusercontent.com/52915069/196871788-414c734f-71e0-4348-85d8-2d29f2edc83f.png">

**Comment by faisalnaveedRNS** [comment]
![Screenshot from 2022-10-19 18-48-22](https://user-images.githubusercontent.com/52915069/196871828-8f59efa1-9d8d-417f-a0ac-e2ba25d449ab.png)

**Comment by ahmadrns** [comment]
@faisalnaveedRNS  sure

**Comment by faisalnaveedRNS** [comment]
https://user-images.githubusercontent.com/52915069/196872007-5f24c04d-3eb5-439c-95cf-bd12c6cc8e75.mov

**Comment by ahmadrns** [comment]
https://github.com/Pylons-tech/pylons/pull/1274/

**Comment by Tanyaml** [comment]
I have validated the 3D NFT is working- it is working as expected.

Please see video:

https://user-images.githubusercontent.com/93543576/197540206-8c285979-1866-44f8-a70f-9140d9a8f624.mov
