### ISSUE TITLE
Fractal KYC

### ISSUE THREAD

**Issue by StefanB90** [Pylons-tech/pylons#1237]
## Summary

Pylons app api call to retrieve receipt from fractal.

only guaranteeing info is up-to-date for 24 hours.

internal flag to set expiration date (6 months) whitelisted credential.

Samuel: Partnerships
Tiago: developer from Fractal
API is a curl call
credentials expires in 24 hours.
Reach out to Sam for testing it.
Testnet:

[https://developer.next.fractal.id/](https://developer.next.fractal.id/)

[https://www.notion.so/fractal/Fractal-Product-Overview-2c63841aebaf4000b96f1c44c1680ad1](https://www.notion.so/2c63841aebaf4000b96f1c44c1680ad1)

[https://docs.developer.fractal.id/](https://docs.developer.fractal.id/)

[https://docs.developer.fractal.id/fractal-credentials-api](https://docs.developer.fractal.id/fractal-credentials-api)

receipt attestation process --> credential api valid for 24 hours KYC --> we won't prompt KYC update for 6 months after initial onboarding

**Two use cases**
1. send or receive bedrock tokens (need wallet address KYC’d) —> manually set validators through a different process
2. Stripe USD or Pylons Points in Wallet to cash out to your bank account (US-domiciled bank accounts to start)

separate out sending & receiving
## Problem Definition

<!-- Why do we need this feature? 

Enabling Fractal KYC allows us to send & receive bedrock tokens in compliance with US security rules and regulations. This will also allow users to cash out their Stripe USD & Pylons Points to their US-domiciled bank account. 

## Proposal

Similar to Stripe onboarding, we will enable fractal onboarding within the pylons app, then create an api call to retrieve the fractal KYC receipt when bedrock tokens are being sent or received into a specific person's multi-sig wallet.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by StefanB90** [comment]
@mustafapylons @kjawadDeveloper2 @faisalnaveedRNS fyi

**Comment by StefanB90** [comment]
To be completed by end of October

**Comment by StefanB90** [comment]
Breaking this ticket into two parts:
1. send/receive bedrock tokens has been completed as demonstrated by @faisalnaveedRNS during last Friday's demo.
2. Cash out will be completed post mainnet

receipt attestation is a priority post-mainnet launch, but must be researched based on Fractal's documentation relates specifically to Ethereum. we must ensure that integrating with their SDK does not cause any significant issues for us.

**Comment by Tanyaml** [comment]
@StefanB90 please see.
