### ISSUE TITLE
UPDATE: PDF Icon in Easel

### ISSUE THREAD

**Issue by heyitsjk** [Pylons-tech/pylons#1248]
## Summary

Per Design, the PDF Icon on the Creator Hub screen in Easel should be updated to the new icon + all sections capitalized as well ("IMAGE", "VIDEO", "AUDIO", "PDF")
https://www.figma.com/file/fhWmRya8H5Baasjq4XA35r/Easel?node-id=3658%3A468

Current: 
![IMG_450002EA1F16-1](https://user-images.githubusercontent.com/74597290/195659676-12fd76b4-4af3-4ba7-b0de-4d5f03bcf854.jpeg)

UPDATED: 
![Creator Hub](https://user-images.githubusercontent.com/74597290/195659753-86e84931-2669-40fe-a290-ac0366913210.png)

New Icon:
![PDF Icon - Vector 186 (Stroke)](https://user-images.githubusercontent.com/74597290/195663569-3bfb6193-43e1-4793-ba0f-f18eed810bdd.svg)

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by kjawadDeveloper2** [comment]
https://github.com/Pylons-tech/pylons/pull/1255  will solve this.

**Comment by heyitsjk** [comment]
this has been updated in Easel 1.0.3 (8) on iOS Testflight
