### ISSUE TITLE
Chain upgrade to RC4 for mainnet.

### ISSUE THREAD

**Issue by mustafapylons** [Pylons-tech/pylons#1253]
## Summary of Bug

Chain upgrade to RC4 for mainnet.

## Steps to Reproduce

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by StefanB90** [comment]
this has been completed. We can close this issue.
