### ISSUE TITLE
Add Firebase config for custom messaging / push notifications

### ISSUE THREAD

**Issue by StefanB90** [Pylons-tech/pylons#1254]
## Summary

In order to provide our users with greater detail regarding the reason(s) why the pylons app/network is not working as intended at the moment based on various circumstances that we may encounter, we must implement a custom messaging prompt in Firebase by adding a config to allow us to draft specific language for any given scenario we might face to then automatically send this message as a push notification to all impacted users, reassuring them that we are aware of the problem and working to solve it as quickly as possible.

Moreover, we will also need to be able to draft custom push notifications for marketing purposes (i.e. advertising featured drops/limited editions remaining for a trending NFT, et.c)

## Problem Definition

Right now we have no way of informing our users about a specific circumstance the pylons app or network is facing. We must be able to provide our users with more detail regarding the problem we are facing and reassure them that we are handling it and that their NFTs/assets are safe and secure.

## Proposal

Add Firebase config to enable custom messaging as push notifications to all impacted users in the event we are facing technical difficulties to reassure them that we are doing our best to address the issue and that their digital assets are secure and that we believe we will resolve the problem shortly.
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by faisalnaveedRNS** [comment]
@kjawadDeveloper2 I think we need to design a maintenance mode, scree when ever the chain is down
