### ISSUE TITLE
EASEL Creator Hub Screen Adjustments

### ISSUE THREAD

**Issue by faisalnaveedRNS** [Pylons-tech/pylons#1280]
## Summary
Need to adjust UI changes in creator hub

## Proposal

![Screen_Shot_2022-10-20_at_3 05 08_PM](https://user-images.githubusercontent.com/52915069/197128467-ca2766a7-1253-4c61-82ec-37430debb99c.png)

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by faisalnaveedRNS** [comment]
@kamran khan

**Comment by Kamran-Khan-Gene** [comment]
In the previous design NFT were shown to user according to the tabs. Means if user selects drafts then the NFT's in the drafts will be shown, similar for the published and for sale. 

but according to this updated UI all the NFT's are showing at the same time.

is it means filters are removed?

**Comment by Kamran-Khan-Gene** [comment]
If a NFT is published does it mean its available for sale? is there any difference between NFT Published and NFT For Sale?

**Comment by faisalnaveedRNS** [comment]
if during publishing if user set it sale then it is for sale, but user can take otherwise as well.

**Comment by faisalnaveedRNS** [comment]
@StefanB90 please confirm

**Comment by Kamran-Khan-Gene** [comment]
> if during publishing if user set it sale then it is for sale, but user can take otherwise as well.

There is only 2 options at the time of creating NFT "Save as drafts" and "Publish".
![1666612947686](https://user-images.githubusercontent.com/115459890/197521454-4057498c-3be4-46c3-9d41-2ba9560924e0.JPEG)

**Comment by faisalnaveedRNS** [comment]
1. When user publish the NFT it will directly go to for sale, then latter on if he wants to convert "Not for sale" he can do this

**Comment by faisalnaveedRNS** [comment]
@StefanB90 I think for Implementation of toggle on wallet side we need to create a new ticket, the scope of this ticket is only on easel side.
