### ISSUE TITLE
Maintenance Mode <> Pylons App + Easel

### ISSUE THREAD

**Issue by StefanB90** [Pylons-tech/pylons#1295]
## Summary

In order to ensure that we can offer our users uninterrupted service when our network experiences issues and must be brought down for unscheduled maintenance & repair, we must offer a maintenance mode that will be initiated whenever the chain it down.

Maintenance mode will allow Pylons app users the ability to continue using the app to view their Collection, but will not allow them to purchase new NFTs or sell existing ones from their Collection.

Maintenance mode will allow Easel users to create & edit Draft NFTs & Upload to IPFS, but will not allow them to publish new NFTs or toggle NFTs available for sale.

Once Maintenance mode has been initiated, a banner will be displayed within the Pylons and Easel apps to indicate to users that they are currently in Maintenance mode. Once Maintenance mode is no longer needed, the banner will be removed and users will receive a push notification indicating that the issue has been resolved and full functionality for both Easel and the Pylons app has been restored.

## Proposal

1. Cache all NFTs in the Collection tab of all Pylons app users (thumbnail + full-screen Owner's View).
2. Cache all Draft NFTs in the Creator Hub for all Easel app users, as well as thumbnail for both Draft & Published NFTs.
3. Display an in-app message to all users that we've temporarily instituted Maintenance mode to allow users to continue enjoying limiting app functionality while we resolve a network issue.

## Design

![Screen Shot 2022-11-16 at 3 48 07 PM](https://user-images.githubusercontent.com/97635071/202290808-43bae8ce-07d0-4db1-9cf8-5002f983686d.png)

- maintenance mode (1) = when a user opens the app, we display the message at the bottom of the screen, along with the Maintenance Mode banner on the top right with a semi-transparent black shadow overlay that disappears once the user clicks anywhere on the screen
- maintenance mode (2) = once the user clicks anywhere on the screen, only the Maintenance Mode banner at the top right remains until we deactivate Maintenance Mode and restore normal app functionality

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by faisalnaveedRNS** [comment]
@ahmadrns

**Comment by kjawadDeveloper2** [comment]
@ahmadrns  any update on this. @StefanB90  can we have any design how we are going to show user that we are in maintenance mode?

**Comment by StefanB90** [comment]
@kjawadDeveloper2 @ahmadrns @faisalnaveedRNS updated with final design mockup. Ready for dev.

**Comment by faisalnaveedRNS** [comment]
@Kamran-Khan-Gene Please look in to this feature

**Comment by Tanyaml** [comment]
@kjawadDeveloper2 please help christine with this ticket.
