### ISSUE TITLE
Change Sale Status Using Toggle

### ISSUE THREAD

**Issue by faisalnaveedRNS** [Pylons-tech/pylons#1298]
## Summary

Allow the user to change status of published NFT using toggle.  When user will change status it will crate a transaction in block chain, 
that will then update status.

1. During publishing the NFT will by default is for sale. and it ill appear in both for sale and published NFT
2. If user change toggle status to not for sale, then on easel it will appear in publish as not for sale, but will not appear on for sale.

On chain side, during nft buy it have to make sure that NFT is on sale.

Design Link
https://www.figma.com/file/QDHfg12EHmXgMd9jWsgEnC/Pylons-app-2.0?node-id=1065%3A1140

## Problem Definition

User will be able to change status of Published NFT using toggle.

## Proposal

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by faisalnaveedRNS** [comment]
@Kamran-Khan-Gene

**Comment by faisalnaveedRNS** [comment]
@StefanB90 please verify requirement

**Comment by Kamran-Khan-Gene** [comment]
What does this #4 indicates?


![image](https://user-images.githubusercontent.com/115459890/198011373-8b22addc-4889-47a7-93b4-b4ab296f570c.png)

**Comment by Kamran-Khan-Gene** [comment]
> 2\. If user change toggle status to not for sale,

How can I make transaction in the chain which changes status of NFT "For Sale" or "Not For Sale".

**Comment by faisalnaveedRNS** [comment]
@Kamran-Khan-Gene please checkout the proto buff for making transaction, @kjawadDeveloper2 can you please help out in this matter

**Comment by Kamran-Khan-Gene** [comment]
> please checkout the proto buff for making transaction,

OK

**Comment by Kamran-Khan-Gene** [comment]
@faisalnaveedRNS This drop down contains 2 values Pylons and USD dollars, isn't it? 

![image](https://user-images.githubusercontent.com/115459890/198266420-922028f0-1de4-4677-9897-36aa750e2e3e.png)

**Comment by Kamran-Khan-Gene** [comment]
> What does this #4 indicates?
> 
> ![image](https://user-images.githubusercontent.com/115459890/198011373-8b22addc-4889-47a7-93b4-b4ab296f570c.png)

@faisalnaveedRNS

**Comment by faisalnaveedRNS** [comment]
@Kamran-Khan-Gene i think i need to confirm from @StefanB90

**Comment by faisalnaveedRNS** [comment]
> 

@StefanB90 how many denoms in which our system can sale the NFT

**Comment by faisalnaveedRNS** [comment]
![image](https://user-images.githubusercontent.com/52915069/198517451-2eefe9d3-0fef-4ac6-a5e9-1131bf3d4de5.png)
@StefanB90 I dont think user need to pay when he wants to change status from sale to not for sale

**Comment by kjawadDeveloper2** [comment]
> > 2. If user change toggle status to not for sale,
> 
> How can I make transaction in the chain which changes status of NFT "For Sale" or "Not For Sale".

By calling `updateRecipe` of repository class. The recipe object has a param called `enabled`. By setting it false you are stopping its sales.

**Comment by kjawadDeveloper2** [comment]
> > What does this #4 indicates?
> > ![image](https://user-images.githubusercontent.com/115459890/198011373-8b22addc-4889-47a7-93b4-b4ab296f570c.png)
> 
> @faisalnaveedRNS

When you buy an NFT which has 10 editions . It indicates the edition that you bought. Forexample, you are the fourth person to buy this NFT then your NFT will be #4.
