### ISSUE TITLE
Big Dipper Buy Now page

### ISSUE THREAD

**Issue by StefanB90** [Pylons-tech/pylons#1308]
## Summary

[Figma Design Link](https://www.figma.com/file/QDHfg12EHmXgMd9jWsgEnC/Pylons-app-2.0?node-id=6676%3A2098)

![Screen Shot 2022-11-03 at 11 59 03 AM](https://user-images.githubusercontent.com/97635071/199771256-955e58e2-988d-4297-bdeb-eef36c80cc71.png)

## Acceptance Criteria

- New Buy Now button displays the price per edition & the number of editions remaining, which is dynamic and decreases as more editions are sold.

### Ownership
1. Current Owner aka Seller
2. Edition# [46 available = Total number of editions (50) - current edition number you as the prospective buyer can purchase (4)] --> this number must be dynamic and update as the remaining editions are purchased by other pylons app users
3. Royalty % always sent to the original artist/creators pylons wallet

### NFT Detail
1. Recipe ID w/ copy button
2. Resolution = pixel dimensions & file type
3. IPFS CID w/ copy button

### History
1. Most recent transaction
2. Second most recent transaction
3. Creation event / First sale

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by Tanyaml** [comment]
@faisalnaveedRNS  Did you start working on this ticket?
