### ISSUE TITLE
Safety net deprecated for app check.

### ISSUE THREAD

**Issue by kjawadDeveloper2** [Pylons-tech/pylons#1311]
@faisalnaveedRNS  For app check safetynet has been deprecated and we need to migrate it to play integrity.
```
  @Deprecated(
    'Safety Net provider is deprecated and will be removed in a future release. Play Integrity is the recommended provider.',
  )
  ```

The following is the token for the  play integrity.
```
eyJlcnJvciI6IlVOS05PV05fRVJST1IifQ==
```

**Comment by Tanyaml** [comment]
@faisalnaveedRNS can you please note what needs to be done for this ticket.
