### ISSUE TITLE
Prompt display message for in-app screenshots

### ISSUE THREAD

**Issue by StefanB90** [Pylons-tech/pylons#1337]
## Summary

Whenever a pylons app user takes screenshots of NFTs in full-screen view, display a message with an animated GIF letting the user know that screenshots are outdated and buying digital art is way better and rewards creators for their hard work.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by MikeSofaer** [comment]
I don't think we want to get into the business of copy protection. It's a never-ending hole. If people want to cheat we shouldn't worry to much about it, other than making the non-cheating paths as easy as possible.
