### ISSUE TITLE
Delete all pylons from accounts with over 100 pylons (except for creator's account)

### ISSUE THREAD

**Issue by StefanB90** [Pylons-tech/pylons#1340]
## Summary

Users with over 100 pylons in their account most likely received that many pylons for free from the faucet. As such, we can delete the pylons associated with these accounts since they did not originate from IAP.

## Proposal

Delete all pylons in accounts greater than 100 pylons, except for Andy, the creator's account.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by Tanyaml** [comment]
@faisalnaveedRNS what is the status this ticket?
