### ISSUE TITLE
New Splash Screen

### ISSUE THREAD

**Issue by StefanB90** [Pylons-tech/pylons#1342]
## Summary

[Figma Design Link](https://www.figma.com/file/QDHfg12EHmXgMd9jWsgEnC/Pylons-app-2.0?node-id=6676%3A2099)

![Screen Shot 2022-11-03 at 12 04 52 PM](https://user-images.githubusercontent.com/97635071/199772562-680016f6-9b71-4baf-8778-91687f3cdb34.png)

## Acceptance Criteria

- apply the PYLONS motion animation that is already being used for the [pylons.tech](https://www.pylons.tech) website for the splash screen users see when they open the app. This splash screen will effectively serve as a loading screen until the NFT the user was originally looking at on the Big Dipper Buy Page can be displayed in the background tinted with a black overlay shadow and the new Acknowledgement module.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by heyitsjk** [comment]
Attached are the background assets for the logo from the Pylons website:
[ghost-bg.zip](https://github.com/Pylons-tech/pylons/files/9931110/ghost-bg.zip)

**Comment by faisalnaveedRNS** [comment]
4 Hours

**Comment by xinyapylons** [comment]
@ahmadrns Here are the background images. 
![Rectangle 156-1](https://user-images.githubusercontent.com/112962673/200359689-13f4f9ae-bc0e-4add-908b-d025d0380045.jpg)
![Rectangle 156-2](https://user-images.githubusercontent.com/112962673/200359690-f74504ab-bf32-49e1-b2df-3baef0de4b37.jpg)
![Rectangle 156-3](https://user-images.githubusercontent.com/112962673/200359691-9b8f26fe-c7dd-4289-811d-df18fd0966a3.jpg)
![Rectangle 156-4](https://user-images.githubusercontent.com/112962673/200359692-f480d8ab-4f21-4cd6-a649-30ae9454e57e.jpg)
![Rectangle 156-5](https://user-images.githubusercontent.com/112962673/200359696-b4cb5b9a-9320-464f-88f0-80c6486da677.jpg)
![Rectangle 156](https://user-images.githubusercontent.com/112962673/200359698-8821b818-bb61-4770-9386-a2e0d9cb571b.jpg)

**Comment by ahmadrns** [comment]
@xinyapylons I need the splash screen background image the one which has color `Orange Soda`

**Comment by ahmadrns** [comment]
@xinyapylons I need the splash screen background image the one which has color `Orange Soda`

**Comment by StefanB90** [comment]
@ahmadrns @kjawadDeveloper2 

[SPLASH SCREEN](https://www.figma.com/file/QDHfg12EHmXgMd9jWsgEnC/Pylons-app-2.0?node-id=6870%3A2098)

**Comment by Tanyaml** [comment]
@StefanB90 I have tested the splash screens and work as expected and crossed referenced with the figma files and it is valid. 
Please See Video:


https://user-images.githubusercontent.com/93543576/202266681-8054a9a3-24df-43eb-9d3c-018fd3100a03.mov

**Comment by heyitsjk** [comment]
looks like the logos have a faint dark layer behind them? should not have that.
also, looks a little weird when they blink to the next one - should we have them quickly fade into the next like on the website?
@StefanB90

**Comment by Tanyaml** [comment]
> looks like the logos have a faint dark layer behind them? should not have that. also, looks a little weird when they blink to the next one - should we have them quickly fade into the next like on the website? @StefanB90

I agree it jumps to fast and it should fade into the next image...

**Comment by Tanyaml** [comment]
@ahmadrns The images should fade into each-other just how it is on pylons.tech

**Comment by ahmadrns** [comment]
Uploading Screen Recording 2022-11-21 at 2.32.14 PM.mov…

**Comment by ahmadrns** [comment]
https://user-images.githubusercontent.com/106388520/203026786-4dfff921-0848-446c-947c-1717629db868.mov

**Comment by ahmadrns** [comment]
@heyitsjk @Tanyaml  kindly verify the attach video of splash screen

**Comment by Tanyaml** [comment]
@ahmadrns The Fade in for each splash screen looks good... Except its still looks like that dark layer is still present- is there any way that dark layer can be removed?

**Comment by ahmadrns** [comment]
@Tanyaml I have removed the background layer completely.

**Comment by ahmadrns** [comment]
@Tanyaml  @kjawadDeveloper2  I have recorded this video on physical device.

**Comment by heyitsjk** [comment]
@ahmadrns on current Testflight build, the "Update Available" screen slides in from the right. Is there any way to add that back in rather than it just appearing suddenly? Other than that, the fade animation looks good.

**Comment by Tanyaml** [comment]
@StefanB90 I have validated the Splash Screen and it working as expected.
Please see video:
https://user-images.githubusercontent.com/93543576/203121025-ec5769a0-baad-4766-8ea8-d07ac6b5ddc4.mov

**Comment by ahmadrns** [comment]
@heyitsjk I have recorded this video on Android Phone, you will see same behaviour when this push to iOS TestFlight
