### ISSUE TITLE
Acknowledgement module

### ISSUE THREAD

**Issue by StefanB90** [Pylons-tech/pylons#1343]
## Summary

[Figma Design Link](https://www.figma.com/file/QDHfg12EHmXgMd9jWsgEnC/Pylons-app-2.0?node-id=6676%3A2100)

![Screen Shot 2022-11-03 at 12 21 08 PM](https://user-images.githubusercontent.com/97635071/199776363-dae0e823-af5f-44f9-a754-b6c08d86be17.png)

## Acceptance Criteria

1. Once the splash screen animation is complete, display the NFT the new Pylons app user wanted to buy when they clicked on the Buy Now button on the Big Dipper Buy Page, however, add a black tinted transparent overlay box on top of the NFT and the new Acknowledgement popup module will rise from the bottom of the screen, preventing the user from continuing until they agree to our Terms of Service & Privacy Policy.
2. The Get Started button will be disabled (greyed out) until the user checks both boxes.
3. Once the user checks both boxes, the Get Started button will be enabled (red w/ white font)
4. Clicking on the blue hyperlinked Terms of Service or Privacy Policy opens a new tab in the user's Mobile Browser that links to the Terms of Service & Privacy Policy located on [pylons.tech](https://www.pylons.tech)

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by faisalnaveedRNS** [comment]
5 Hour

**Comment by faisalnaveedRNS** [comment]
@ahmadrns this flow only for the user who are coming from deep links, there will be separate flow for the users who come with out deeplink

**Comment by faisalnaveedRNS** [comment]
@ahmadrns to make sure to properly test all type of NFTs

**Comment by faisalnaveedRNS** [comment]
8 Hour added,

**Comment by faisalnaveedRNS** [comment]
@ahmadrns any update on this

**Comment by ahmadrns** [comment]
@faisalnaveedRNS send a PR for it once approved, It will merge

**Comment by ahmadrns** [comment]
Uploading Screen Recording 2022-11-24 at 12.43.17 PM.mov…

**Comment by ahmadrns** [comment]
https://user-images.githubusercontent.com/106388520/203727638-85b5b4f5-457d-4260-a844-4a3ef12a5ebe.mov

**Comment by ahmadrns** [comment]
@Tanyaml @kjawadDeveloper2
