### ISSUE TITLE
Revised NFT Full Screen View (Buy Now + sub-tabs)

### ISSUE THREAD

**Issue by StefanB90** [Pylons-tech/pylons#1344]
### Summary

[Figma Design Link](https://www.figma.com/file/QDHfg12EHmXgMd9jWsgEnC/Pylons-app-2.0?node-id=6676%3A2101)

![Screen Shot 2022-11-03 at 12 53 20 PM](https://user-images.githubusercontent.com/97635071/199784604-9f930707-6018-4dcb-9bad-cb7badfb066f.png)

### Acceptance Criteria

1. New Buy Now button now contains the current price per edition displayed in the following format:

- for all dollar denominations greater than one dollar --> $x.00
- for all dollar denominations less than one hundred dollars$xx.00 
- for all dollar denominations greater than or equal to one hundred dollars --> $xxx
- for all dollar denominations greater than or equal to one thousand --> $x,xxx 

NOTE: WE NOW RESTRICT ALL DOLLAR DENOMINATED PRICES TO WHOLE NUMBERS ONLY ROUNDED TO THE NEAREST $1 & DO NOT USE "USD" WHEN DISPLAYING ANY PRICE DENOMINATED IN U.S. DOLLARS. ONLY THE "$" IS ALLOWED.

2. The "ea." after the current price per edition stands for "each" and is in a small font relative to the price
3. The remaining number of editions available for purchase is the same font size as the "ea." and is dynamic in that it constantly decreases as each edition is sold.

- In the example provided, there were originally 50 editions made available for sale and 46 editions are left, meaning that the first four editions have already been sold and that the user currently looking at this specific screen at this moment in time can purchase edition Pylons-tech/pylons#5 of 50. However, if they do not checkout before someone else does, then they may not be guaranteed to obtain the fifth edition. 

5. The Buy Now button remains fixed at all times. The Watchlist ("eye"), Like ("heart") & Share icons also remain fixed. We've reduced the information in each sub-tab and adjusted the spacing for all fields & icons in the NFT full-screen popup module:

![Screen Shot 2022-11-03 at 12 57 10 PM](https://user-images.githubusercontent.com/97635071/199785544-65bef52d-f3bb-4824-af67-4f4cce004c12.png)

6. The Edition# is now dynamic and linked to the remaining number of editions available for purchase. This implies that as a new edition is purchased by another pylons app user, the number shown below the price per edition decreases by one (or the equivalent amount) and the Edition# displayed in the Ownership sub-tab increases by one (or the equivalent amount).

7. The History sub-tab displays the original creation event with the artist/creator's username, the second last transaction & the most recent transaction in descending order

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by faisalnaveedRNS** [comment]
If user bought a item, Is it possible to resale the item in the market @StefanB90

**Comment by kamran8545** [comment]
The design of the flow has been updated now, and a button to download NFT has been added to it which means the user will be able to download NFT by pressing that button. this is a flow where the user opens NFT by link and wants to purchase NFT. if the user will be able to download NFT before purchasing it, why would the user purchase NFT? I think the download button should not be added here.

@faisalnaveedRNS , @kjawadDeveloper2 , @StefanB90 Need your suggestion.

<img width="1109" alt="image" src="https://user-images.githubusercontent.com/28790321/200264485-9355cd29-3984-4e66-a630-020e837a120d.png">

**Comment by kamran8545** [comment]
I have created an NFT and purchased it from 3 different accounts but when I am visiting NFT to purchase it from the 4rth account, I am unable to get its history. 

If I am purchasing NFT I am able to see history from the same account. 

@faisalnaveedRNS @kjawadDeveloper2  are we showing history to all the users even they have not purchased NFT?

**Comment by StefanB90** [comment]
This is incorrect. Only the NFT owner sees the download icon.

**Comment by StefanB90** [comment]
Yes @faisalnaveedRNS 
https://github.com/Pylons-tech/pylons/issues/1348#issue-1438515881

**Comment by faisalnaveedRNS** [comment]
@Kamran-Khan-Gene Please make sure the app work properly with following use cases

1. User try to purchase nft without creating account
2. User already have account

**Comment by faisalnaveedRNS** [comment]
when use already have account 

1. show splash screen, then home screen, then buy now screen

**Comment by heyitsjk** [comment]
@Kamran-Khan-Gene 

In addition to what Tanya stated above: 
- this screen does not need a download button (only the NFT owner needs this button so it's ok not to have it here) 
- the "report" flag icon is missing from the top-right of the screen.
- under "NFT Detail" section, the "Resolution" needs to also include the file type uploaded (GIF, JPEG, etc.) 
- the orange close box in the top-right of the info pan is cut off.
- there is a second orange triangle in the lower-left corner that needs to be removed. 


Please see attached Figma file for reference: 
![NFT Detail tab](https://user-images.githubusercontent.com/74597290/202593440-78c4206d-9d6f-4f10-944e-cbb27bd639b6.png)

**Comment by Tanyaml** [comment]
@Kamran-Khan-Gene what is the status on this ticket?

**Comment by Kamran-Khan-Gene** [comment]
> @kamran8545 Below are the following items that need to fixed.
> 
> 1. History Tab  is missing
> 2. Actual amount is missing decimals- meaning  it needs to 5.00




@Tanyam
1. you are unable to see the history tab because there is no history generated.. this NFT is just created, and when it will be sold once you will be able to see its history.

2. you are seeing a whole no 5 because you have created this NFT with pylons points. for the pylons points, we are not showing values in decimals.
