### ISSUE TITLE
Collection tab w/ Favorites folder

### ISSUE THREAD

**Issue by StefanB90** [Pylons-tech/pylons#1346]
## Summary

[Figma Design Link](https://www.figma.com/file/QDHfg12EHmXgMd9jWsgEnC/Pylons-app-2.0?node-id=6757%3A2617)

![Screen Shot 2022-11-07 at 9 20 45 AM](https://user-images.githubusercontent.com/97635071/200333137-1d83ece6-bf30-4da4-976f-80afc8d957c9.png)

## Acceptance Criteria

- When you complete the buying flow, the Purchases tab is opened under Collection to display the new thumbnail of the NFT you just purchased. The NFT type (icon in top left of thumbnail) & NFT name with edition # is displayed in bottom left of thumbnail.
- Favorites are NFTs you've liked. Tapping the filled in heart icon located at the bottom right of the thumbnail unlikes the NFT and removes it from your Favorites.
- Creations display NFTs you've minted in Easel. Clicking the Download Easel button opens the App Store page to allow the User to download Easel.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by Kamran-Khan-Gene** [comment]
@faisalnaveedRNS new screen will be design on just favorite tab will be added in old collection screen?

**Comment by Kamran-Khan-Gene** [comment]
I need the updated mockup of the Wallet screen as well because I have updated the upper portion that is common for Collection Screen and for Wallet Screen.

<img width="373" alt="image" src="https://user-images.githubusercontent.com/115459890/200514909-6208237e-c871-4278-9be8-dadcb55079a5.png">

**Comment by faisalnaveedRNS** [comment]
> I need the updated mockup of the Wallet screen as well because I have updated the upper portion that is common for Collection Screen and for Wallet Screen.
> 
> <img alt="image" width="373" src="https://user-images.githubusercontent.com/115459890/200514909-6208237e-c871-4278-9be8-dadcb55079a5.png">

hi @Kamran-Khan-Gene i think the figama have most up 2 date design, is this is not enough

**Comment by Kamran-Khan-Gene** [comment]
@faisalnaveedRNS I mean that the profile section at the top is common for both Collection and Wallet tabs. what I am asking is profile section of both the Collection and Wallet Tab will be updated.

<img width="290" alt="image" src="https://user-images.githubusercontent.com/115459890/200532960-dc4d47b2-6bc5-4273-afaa-275a9d5727ba.png">

<img width="285" alt="image" src="https://user-images.githubusercontent.com/115459890/200533048-b0d57db3-3d8b-4f48-89c4-0e15be2a66d2.png">

**Comment by faisalnaveedRNS** [comment]
I think yes, as it is same

**Comment by Kamran-Khan-Gene** [comment]
@StefanB90 , @faisalnaveedRNS  liking NFT and adding NFT in favorites are these both the same? because we don't have any button for adding NFT in the favorites yet.

**Comment by faisalnaveedRNS** [comment]
@Kamran-Khan-Gene is this issue resolved
