### ISSUE TITLE
Sell your NFT

### ISSUE THREAD

**Issue by StefanB90** [Pylons-tech/pylons#1348]
## Design

[Figma Design Link](https://www.figma.com/file/QDHfg12EHmXgMd9jWsgEnC/Pylons-app-2.0?node-id=6759%3A2618)

![Screen Shot 2022-11-07 at 10 02 57 AM](https://user-images.githubusercontent.com/97635071/200342899-01817aa3-ec2e-48cb-9426-35d8108302a8.png)

## Acceptance Criteria

- Only the NFT Owner has the download icon available to them
- The Number of Editions Available is unique to each owner, meaning the 10 available is dynamic and reflects the actual number of editions this particular user has available for sale.
- Learn More links to the FAQ on pylons.tech

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by faisalnaveedRNS** [comment]
@StefanB90 

1. if user sell move NFT from not for sale to sale, does software allow to edit exiting number of editions and prices ?

**Comment by Kamran-Khan-Gene** [comment]
@StefanB90 @faisalnaveedRNS can user change status of purchased NFT?

**Comment by StefanB90** [comment]
@faisalnaveedRNS @Kamran-Khan-Gene 

if a pylons app user purchases an edition of a NFT directly from the NFT creator or from another Pylons app user, the buyer has the ability to sell their NFT edition again if they so chose to. This is what's known as secondary market transactions. All secondary market transactions must automatically distribute the royalty percentage directly to the NFT creator's pylons wallet address. You cannot change the royalty percentage or the number of editions for any secondary market transactions.

You can only sell the number of editions you currently possess in your collection or creations folder.

CC @Tanyaml
