### ISSUE TITLE
Delist NFT

### ISSUE THREAD

**Issue by StefanB90** [Pylons-tech/pylons#1349]
## Design

[Figma Design Link](https://www.figma.com/file/QDHfg12EHmXgMd9jWsgEnC/Pylons-app-2.0?node-id=6759%3A2728)

![Screen Shot 2022-11-07 at 10 36 37 AM](https://user-images.githubusercontent.com/97635071/200350843-e18beacd-b118-443e-9b1b-778b63c322dd.png)

## Acceptance Criteria

- When a NFT owner has an active NFT Listing, by clicking the For Sale toggle the intermediate yellow state is triggered and a Confirmation popup is displayed prompting the owner to Swipe right to confirm that they would like to delist their NFT. Once this is complete the toggle is displayed in the Not for sale state and the NFT is no longer available for sale.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by heyitsjk** [comment]
@StefanB90 what does Big Dipper display after it has been delisted?

**Comment by Tanyaml** [comment]
@Amean 
Please check why the PR has failed- please discuss this @Jawad-Ahmed.
