### ISSUE TITLE
double tap to hide icons

### ISSUE THREAD

**Issue by StefanB90** [Pylons-tech/pylons#1350]
## Design

[Figma Design Link](https://www.figma.com/file/QDHfg12EHmXgMd9jWsgEnC/Pylons-app-2.0?node-id=6759%3A3058)

![Screen Shot 2022-11-07 at 11 00 37 AM](https://user-images.githubusercontent.com/97635071/200356466-ec90e5d0-45c5-4b75-944c-b3dda9fe5068.png)

## Acceptance Criteria

- Double tapping anywhere inside the blue outline box will hide all text & icons to allow the user to admire the NFT unadulterated.
- Double tapping again will display all text & icons once again.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by ahmadrns** [comment]
Start working on this issue

**Comment by ahmadrns** [comment]
https://user-images.githubusercontent.com/106388520/205637030-816653b8-6d23-4d68-adcb-61424f018bba.mp4

**Comment by ahmadrns** [comment]
https://user-images.githubusercontent.com/106388520/205643441-f7f88c73-7351-464d-8a06-781db7ca1527.mp4
