### ISSUE TITLE
execute_recipe_request enhancement

### ISSUE THREAD

**Issue by StefanB90** [Pylons-tech/pylons#1374]
## Summary

Enhance the execute recipe API call to allow for more in-depth cross-app communication, which will essentially confirm that a user has enough pylon credit in their current account balance to initiate the desired recipe execution, if said recipe execution requires an input price to trigger the API call.

Add IAP module that is automatically prompted in the event that the user does not have enough pylon credit in their wallet to pay the cost to execute the recipe.

For example, say it costs $0.01 to trigger the execute_recipe API call, and the user doesn't have any pylon credit in their wallet, then the IAP module would prompt them to purchase $1 worth of pylon credit and once the user confirms this, $0.01 is deducted from their new $1 pylon credit balance and triggers the desired outcome of executing the recipe API call. If the user then opens their wallet, they would have a balance of $0.99 under their pylon credit. 

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by StefanB90** [comment]
CC @afti-githobo @MikeSofaer

**Comment by Tanyaml** [comment]
@afti-githobo can you please confirm this can be closed, is this done yet?
