### ISSUE TITLE
Find executions by recipe ID weirdness

### ISSUE THREAD

**Issue by afti-githobo** [Pylons-tech/pylons#1392]
## Summary of Bug

Tthe Flutter low-level recipe execution command "fails" with an empty response object when the tx happens successfully. This is known to happen when executing recipes from the testapp cookbook, because the app isn't able to rereieve an execution using the execution-by-recipe-ID command; this *shouldn't* be specific to a single set of recipes (and there should be no way a live recipe _could_ be broken such that this behavior would happen) but should be tested w/ other recipes regardless. This appears to be an issue with the API endpoint, though - while it'd be nice to confirm whether there are recipes for which that call *does* find executions, there shouldn't be recipes executing successfully that fail to show up there.

## Version

testapp-redo

## Steps to Reproduce

Just go ahead and try to hit a button what executes a recipe. Watch logcat to see the fireworks.

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by faisalnaveedRNS** [comment]
@afti-githobo unable to reproduce, can you please create video reference for it.

**Comment by afti-githobo** [comment]
> @afti-githobo unable to reproduce, can you please create video reference for it.

sorry, i didn't see this til now. simplest way to reproduce would be to just run `pylonsd query pylons list-executions-by-recipe appTestCookbook RecipeTestAppFightGoblin` at the CLI tho?

**Comment by Tanyaml** [comment]
@afti-githobo can you please record a video so we can replicate it ?
