### ISSUE TITLE
1.) Tutorial + Creator Hub (intro)

### ISSUE THREAD

**Issue by StefanB90** [Pylons-tech/pylons#1394]
## UX / UI

[Figma Design Link](https://www.figma.com/file/fhWmRya8H5Baasjq4XA35r/Easel?node-id=4193%3A258&t=hjHtYKoErhDepZrS-4)

![Screen Shot 2022-11-16 at 12 45 03 AM](https://user-images.githubusercontent.com/97635071/202093853-d0c5ac77-aa9c-4bcf-a03c-b914aa7dc86a.png)

## Acceptance Criteria

1. Tutorial + Creator Hub (intro) is shown once when users open Easel for the first time (regardless of whether they downloaded Easel first or if they downloaded Easel from the Creations folder in the Pylons App.
2. Create Draft button only appears under "Published" if there are no Published NFTs, but always appears under "Draft"
3. The title "Creator Hub" & description "Draft NFTs contain an IPFS Content ID, but require additional information to be published on the pylons chain and listed for sale on the pylons app. You can remove an active NFT listing, but you can never unpublish a NFT." Only appear once.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by Kamran-Khan-Gene** [comment]
I have started working on this ticket.
