### ISSUE TITLE
2.) Upload (new audio icon)

### ISSUE THREAD

**Issue by StefanB90** [Pylons-tech/pylons#1395]
## UX / UI

[Figma Design Link](https://www.figma.com/file/fhWmRya8H5Baasjq4XA35r/Easel?node-id=4196%3A259&t=hjHtYKoErhDepZrS-4)

![Screen Shot 2022-11-16 at 10 59 29 AM](https://user-images.githubusercontent.com/97635071/202230489-d8c939e2-bda8-4706-b7c7-21c1eef12f57.png)

## Acceptance Criteria

1. **New Audio symbol**
![Screen Shot 2022-11-16 at 11 11 44 AM](https://user-images.githubusercontent.com/97635071/202233539-a91f1fdc-3d7e-474c-8b59-fa648681f37b.png)

2. **Revised Progress bar**
![Screen Shot 2022-11-16 at 11 00 06 AM](https://user-images.githubusercontent.com/97635071/202230625-ddac7817-0e51-4845-92d0-b0cd7cd1ad96.png)

3. **NFT Preview must match NFT full-screen view exactly.**
![Screen Shot 2022-11-16 at 12 48 29 PM](https://user-images.githubusercontent.com/97635071/202255282-3f983003-6fe4-492f-bdcc-eae15f747484.png)

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by Kamran-Khan-Gene** [comment]
I have started working on it.
