### ISSUE TITLE
3.) Set up username (Pylons App not installed)

### ISSUE THREAD

**Issue by StefanB90** [Pylons-tech/pylons#1398]
## UX / UI

[Figma Design Link](https://www.figma.com/file/fhWmRya8H5Baasjq4XA35r/Easel?node-id=4200%3A549&t=hjHtYKoErhDepZrS-4)
![Screen Shot 2022-11-16 at 12 55 23 PM](https://user-images.githubusercontent.com/97635071/202256712-59e4330f-6400-429c-b9b1-0bd86ca02aef.png)

## Acceptance Criteria

1. Set up username modal in Easel is only prompted when:
    - User downloads Easel before downloading the Pylons app and proceeds to create a Draft NFT & Upload to IPFS.
    - User has Pylons app and downloaded Easel directly from App Store (did not set up username in Pylons app when clicking "Download Easel" button in the Creations folder).

2. Given (1) --> while file is uploading to IPFS, we must check to see if a Pylons username already exists for the Easel creator --> check to see if they downloaded the Pylons app & whether they downloaded Easel by clicking the "Download Easel" button from the Creations folder in the Pylons app.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by faisalnaveedRNS** [comment]
@ahmadrns Please checkout this ticket

**Comment by ahmadrns** [comment]
@kjawadDeveloper2 Need discussion on this issue
