### ISSUE TITLE
4.) NFT Pricing (Payment type)

### ISSUE THREAD

**Issue by StefanB90** [Pylons-tech/pylons#1399]
## UX / UI

[Figma Design Link](https://www.figma.com/file/fhWmRya8H5Baasjq4XA35r/Easel?node-id=4204%3A531&t=qrK7ostzOXrbcxkR-4)
![Screen Shot 2022-11-16 at 4 00 56 PM](https://user-images.githubusercontent.com/97635071/202293269-4e0dca05-e165-416e-9472-f71f9924c84a.png)

## Acceptance Criteria

1. Payment type slider when creator indicates that this Draft NFT is not a free drop:
   - Apple of Google Pay = In-app Purchase = "Credit" in Wallet tab of Pylons app 
   - Credit or Debit Card = "Cash" in Wallet tab of Pylons app

2. Price per edition is always denominated in U.S. Dollars using the dollar "$" symbol.
    - The dollar "$" symbol should automatically appear when the creator begins typing.
    - The dial-pad is automatically prompted when the creator clicks into the input field.
    - The number entered must be restricted to whole dollar amounts only, by automatically rounding any number entered to the nearest whole number (i.e. creator enters "9.62" then the amount will adjust to "$10.00" when the creator clicks out of the field.

3. The percent "%" symbol is automatically applied and visible to the creator as they enter a royalty amount.
    - The dial-pad is automatically prompted when the creator clicks into the input field.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by StefanB90** [comment]
@faisalnaveedRNS @kjawadDeveloper2 are we able to support zero royalties now? How about royalties less than one percent?

**Comment by Kamran-Khan-Gene** [comment]
I have started working on it.
