### ISSUE TITLE
5.) Download Pylons App

### ISSUE THREAD

**Issue by StefanB90** [Pylons-tech/pylons#1400]
## UX / UI

[Figma Design Link](https://www.figma.com/file/fhWmRya8H5Baasjq4XA35r/Easel?node-id=4204%3A532&t=qrK7ostzOXrbcxkR-4)
![Screen Shot 2022-11-16 at 4 15 38 PM](https://user-images.githubusercontent.com/97635071/202295941-75e9021a-f6c1-49fc-abb6-4cb9a5733a42.png)

## Acceptance Criteria

1. Download popup modal appears only if the creator has not installed the Pylons app on their device and agreed to the Terms of Service & Privacy Policy. The Pylons app check is triggered when the creator clicks "Publish".

2. Once the creator clicks "Download", they are taken to the Pylons App Store listing page to download the Pylons App onto their mobile device. The assumption is that they open the Pylons app once it is finished downloading and agree to the Terms of Service & Privacy Policy. In the event that they download the Pylons app and don't open it before returning to Easel (therefore don't agree to the Terms of Service and Privacy Policy, we will open the Pylons app when they press "Publish" to compel them to agree to the Terms of Service and Privacy Policy before returning them to Easel to finish publishing their Draft NFT. 

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by faisalnaveedRNS** [comment]
@ahmadrns Please check out this ticket

**Comment by ahmadrns** [comment]
Start working on this issue

**Comment by ahmadrns** [comment]
https://user-images.githubusercontent.com/106388520/206168184-32b79ddb-fe4b-4c60-b4f5-8b2f3efdd398.mp4

**Comment by ahmadrns** [comment]
https://user-images.githubusercontent.com/106388520/206168334-47ea30e4-08eb-4d66-9e4c-c629b3abd8bc.mov

**Comment by heyitsjk** [comment]
@ahmadrns 
- the P in "publish" button should be capitalized - "Publish".
- In the popup, the second "pylons" should have a capital P - "Pylons chain".
