### ISSUE TITLE
6.) Publishing NFT (motion frames)

### ISSUE THREAD

**Issue by StefanB90** [Pylons-tech/pylons#1402]
## UX / UI

[Figma Design Link](https://www.figma.com/file/fhWmRya8H5Baasjq4XA35r/Easel?node-id=4204%3A533&t=qrK7ostzOXrbcxkR-4)
![Screen Shot 2022-11-16 at 4 24 33 PM](https://user-images.githubusercontent.com/97635071/202297578-a506b53f-2209-4748-a4b2-ff5c15f58995.png)

## Acceptance Criteria

1. When the creator has successfully set a unique username associated with their Pylons app & Easel , and agreed to the Terms of Service and Privacy Policy within the Pylons app, when the click "Publish" this motion frame animation will be displayed as their Draft NFT is being published to the Pylons chain and listed available for sale on the Pylons app. 

![Screen Shot 2022-11-16 at 4 27 52 PM](https://user-images.githubusercontent.com/97635071/202298102-ed403023-ea45-48f2-a8a1-9c46ff2075b1.png)

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by Kamran-Khan-Gene** [comment]
I have started working on it
