### ISSUE TITLE
7.) Creator Hub 2.0

### ISSUE THREAD

**Issue by StefanB90** [Pylons-tech/pylons#1404]
## UX / UI

[Figma Design Link](https://www.figma.com/file/fhWmRya8H5Baasjq4XA35r/Easel?node-id=4204%3A534&t=qrK7ostzOXrbcxkR-4)
![Screen Shot 2022-11-16 at 7 20 29 PM](https://user-images.githubusercontent.com/97635071/202323435-1c324508-036c-43c5-a6d0-47f1679d49ca.png)

[Figma Design Link](https://www.figma.com/file/fhWmRya8H5Baasjq4XA35r/Easel?node-id=4206%3A535&t=qrK7ostzOXrbcxkR-4)
![Screen Shot 2022-11-16 at 4 31 16 PM](https://user-images.githubusercontent.com/97635071/202298680-24bbc1f3-1a13-44cb-8607-291937ddf9b1.png)

## Acceptance Criteria

1. **Three dot menu options**
    - **Draft NFT**
        1. Delete
        2. View on IPFS
    - **Published NFT**
        1. View on Pylons
        2. View on IPFS

2. Clicking anywhere on the thumbnail or card of a **Draft NFT** [aside from the three dot menu options referenced in (1)] opens the last saved point for the creator to pickup where they left off in the publishing process.

3. Clicking anywhere on the thumbnail or card of a **Published NFT** [aside from the three dot menu options referenced in (1)] opens the NFT Owner's View as is the case when a user clicks on a NFT thumbnail in the Collection tab of the Pylons app.
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by ahmadrns** [comment]
@kjawadDeveloper2 started working on this issue
