### ISSUE TITLE
Upgrade handler for bank module

### ISSUE THREAD

**Issue by StefanB90** [Pylons-tech/pylons#1432]
## Summary

Jacob released a security patch required for the bank module. As such, we must create the necessary upgrade handler to implement the security patch to ensure that any vulnerabilities related to the bank module are rectified.

## Acceptance Criteria

Create the upgrade handler required to address the bank module security vulnerability identified by Jacob and his team.
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by StefanB90** [comment]
CC @MikeSofaer @Tanyaml

**Comment by Tanyaml** [comment]
Reference 46.6 Doc regarding upgrading handler requirements.
