### ISSUE TITLE
TxExecutionResponse for multiple executions in quick succession

### ISSUE THREAD

**Issue by StefanB90** [Pylons-tech/pylons#1433]
## Summary

Discrepancy in execution responses for multiple queries initiated in quick succession.

## Problem Definition

Do we build in a time lag for execution responses in the event that multiple requests are sent simultaneously?

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by faisalnaveedRNS** [comment]
@afti-githobo need more details

**Comment by MikeSofaer** [comment]
There is another issue with more details on this, but it seems like the SDK gives bad values if you aren't careful how you sequence queries.

**Comment by faisalnaveedRNS** [comment]
@StefanB90 is this a duplicate ticket

**Comment by StefanB90** [comment]
@kjawadDeveloper2 can you help with this?
