### ISSUE TITLE
When User is Easel in Draft in Grid View the Value of USD or Pylons is Invalid 

### ISSUE THREAD

**Issue by Tanyaml** [Pylons-tech/pylons#1460]
## Summary of Bug
There is 2 issues for when user is in Draft

1.When User is in Easel, and  creates NFT with Pylons Points and has a value of 5 Pylons, when user is in Drafts in Grid View the NFT it shows value of 0 Pylons.

Please see video:

https://user-images.githubusercontent.com/93543576/204036195-01ec4d81-a29d-4d3e-835d-cc41611f44b1.mov

2. When User is in Easel, in Grid View  and creates  NFT with USD Currency and has Value of 5.00 USD, when user is in  Drafts in Grid View NFT it shows value of 0 Pylons.

Please see video:

https://user-images.githubusercontent.com/93543576/204036320-733925e5-2ca9-4702-a405-73c56c76747b.mov

**### Note when user is in Draft in List view user sees the true value.**
See Screenshot:

![image](https://user-images.githubusercontent.com/93543576/204038988-ff47f212-3c17-4b33-8709-342f1a90a7af.png)

## Steps to Reproduce
1.User will create either Image,Video, 3D, Audio or PDF NFT 
2.User will add currency Pylons Point and click on Draft
3.User will then be directed to Draft and see the Value of the NFT which will show 0 Pylons
4.Repeat steps 1-3 for USD Value showing 0 Pylons

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by Tanyaml** [comment]
@StefanB90 can you please clarify the label of the amount for the NFT, when NFT is in grid view is shows 10 Pylons, and when it is in list view it just show $10.
Which is the correct label ?

Please see screenshot:

![image](https://user-images.githubusercontent.com/93543576/204369942-23fe7b9c-ee9f-4094-879e-d8c750a26a54.png)



![image](https://user-images.githubusercontent.com/93543576/204369974-5b89a77f-3006-4c9c-9da8-8b21cdfe94a5.png)

**Comment by StefanB90** [comment]
Draft NFTs should not have a green price tag in the right corner in either list or grid view.

A Published NFT with a price tag in the top right corner indicates that it is currently for sale. A Published NFT without a price tag indicates it is not for sale or has sold out.

All prices are denominated in dollar. Any reference to PYLN or points is incorrect.
