### ISSUE TITLE
Save file type on chain

### ISSUE THREAD

**Issue by StefanB90** [Pylons-tech/pylons#1462]
## Summary

Add a new string field for "file type" whenever a file is successfully uploaded to IPFS in Easel. Add this 

## Acceptance Criteria

- Saving the file type on chain should enable us to depict the file type after the file size/dimensions in the Resolution field under the NFT Detail sub-tab in the full screen NFT view: 
![Screen Shot 2022-11-25 at 1 18 08 PM](https://user-images.githubusercontent.com/97635071/204038478-0717b45b-f35b-4de5-8634-8bd64618d4af.png)

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by StefanB90** [comment]
CC @kjawadDeveloper2 @Tanyaml

**Comment by ahmadrns** [comment]
Start working on this issue

**Comment by ahmadrns** [comment]
![image](https://user-images.githubusercontent.com/106388520/206090459-84798387-3855-45cf-b388-387a262e3838.png)

**Comment by ahmadrns** [comment]
![image](https://user-images.githubusercontent.com/106388520/206090459-84798387-3855-45cf-b388-387a262e3838.png)
