### ISSUE TITLE
Fix: Remove Splash Page Logo Shadow

### ISSUE THREAD

**Issue by heyitsjk** [Pylons-tech/pylons#1486]
## Summary of Bug

The shadow behind the logo still exists. 
On an Android Tablet, it is more obvious.

Solution: Remove the back shadow entirely behind the logo.

## Version

iOS: Testflight 1.1.5 (6)
Android: 1.0.1 (58) - Production

## Steps to Reproduce

Download the Pylons app.
Open the app.
Observe the shadow behind the logo.

Screenshots: 

![IMG_5289](https://user-images.githubusercontent.com/74597290/204355551-2615606d-3326-43fa-94be-c7e12344c275.jpg)
![IMG_5291](https://user-images.githubusercontent.com/74597290/204355555-371df8e9-58c8-4851-9a2b-6ed5431b80c9.PNG)

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by Tanyaml** [comment]
@ahmadrns Please see video:


https://user-images.githubusercontent.com/93543576/204916706-b1045842-4bdc-42aa-ab4b-eda6de158531.mov

**Comment by ahmadrns** [comment]
This PR solves this BG issue: https://github.com/Pylons-tech/pylons/pull/1418
