### ISSUE TITLE
FREE DROP BUTTON

### ISSUE THREAD

**Issue by StefanB90** [Pylons-tech/pylons#1501]
## UX / UI

[Figma Design Link](https://www.figma.com/file/QDHfg12EHmXgMd9jWsgEnC/Pylons-app-2.0?node-id=7220%3A2439&t=lQ0zODiEV8Vc2QUF-4)
![Screen Shot 2022-11-30 at 12 59 44 PM](https://user-images.githubusercontent.com/97635071/204873252-8c9de040-17f5-45ca-ac64-4a5cb997cbb0.png)

## Acceptance Criteria

1. Text displayed inside red button is "Claim Now" instead of "Buy Now"
2. Price per edition is removed. No reference to $0 or free.
3. Number of editions available = Number of editions unclaimed = Number of editions remaining --> dynamic counter based on total number of editions claimed so far.
4. Add total number of editions associated with the free drop next to the dynamic counter displaying number of editions available/unclaimed/remaining.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by StefanB90** [comment]
CC @Tanyaml @kjawadDeveloper2 @heyitsjk

**Comment by heyitsjk** [comment]
@StefanB90 looks good to me

**Comment by Tanyaml** [comment]
I second that. looks great.

**Comment by ahmadrns** [comment]
Started working on this issue

**Comment by ahmadrns** [comment]
<img width="531" alt="now" src="https://user-images.githubusercontent.com/106388520/205303323-d51f044e-0f36-4ded-9d6e-1845caf326fb.png">

**Comment by ahmadrns** [comment]
![image](https://user-images.githubusercontent.com/106388520/205303470-cf382380-166a-4d46-96a3-8ba3bdc609aa.png)

**Comment by ahmadrns** [comment]
![image](https://user-images.githubusercontent.com/106388520/205303560-8a18acbe-0036-44ed-a27a-d79bbf570767.png)

**Comment by heyitsjk** [comment]
@ahmadrns design notes: 

![205303560-8a18acbe-0036-44ed-a27a-d79bbf570767](https://user-images.githubusercontent.com/74597290/205351057-b2e7cc65-e580-4b24-93a5-b6c88b11cebd.png)

1) the report flag icon is missing in the upper-right corner of the screen.
2) theres not enough space/padding around the close window icon.
3) the menu text (Ownership, NFT Detail, History) should be bold font.
4) The lines under the menu text need to be closer to the text. 
5) The View icon is wrong - needs to be a bolder asset. 
6) The Like/Favorite heart icon is wrong - needs to be a bolder asset.
7) There needs to be a slight drop shadow behind the orange "Claim Now" button into the grey remaining box.
8) Unnecessary orange box in the lower-left corner - please remove this. 

Please see Figma comparison: (this design is from "Buy Now" but still applies to "Claim Now") 
![NFT Detail tab](https://user-images.githubusercontent.com/74597290/205351101-ce03c001-5050-447d-9a13-890b4dd0a7f7.png)
@Tanyaml

**Comment by ahmadrns** [comment]
7) There needs to be a slight drop shadow behind the orange "Claim Now" button into the grey remaining box.
I think that black shade came because of the image behind it. That's why didn't considered it I will refactor the design accordingly with all other changes @heyitsjk

**Comment by ahmadrns** [comment]
<img width="1440" alt="Screenshot 2022-12-05 at 9 52 08 AM" src="https://user-images.githubusercontent.com/106388520/205552224-b0f1ca30-0a64-4e71-b8d3-c65b2ba7c154.png">

**Comment by ahmadrns** [comment]
<img width="533" alt="tab" src="https://user-images.githubusercontent.com/106388520/205582479-c5a704c8-084b-438a-b228-191f92d26624.png">

**Comment by ahmadrns** [comment]
![image](https://user-images.githubusercontent.com/106388520/205582624-b1093720-1d42-40fa-ad43-a2b723852a16.png)

**Comment by heyitsjk** [comment]
@ahmadrns mobile phone design looks good to me.
@StefanB90 what do you think about the menu text size for the tablet screenshot? should those be larger?

**Comment by StefanB90** [comment]
@heyitsjk I think the + shouldn't be bigger than the icons.

Why can't we scale everything proportionally from the mobile device size to the new tablet size based on the wireframe used in the figma design? Would that be possible or should I start creating tablet mockups as well? If so, let's standardize a wireframe size for mobile & tablet to avoid these discrepancies moving forward. What do you think?

**Comment by heyitsjk** [comment]
@StefanB90 theoretically they should be able to scale, but thats a dev question.
most likely will need to make two sets one for mobile and one for a 10in tablet in the future if it doesn't auto scale so we don't keep running into mismatched tablet funkiness.

In the meantime, to get new features out the door, we can approve these - then revisit a design review down the road for mobile v tablet comparisons

**Comment by Tanyaml** [comment]
@kjawadDeveloper2 

Please see attached.
Actual Results: When user claims FREE NFT- the actual button saids claim your free NFT.

Expected Results: Claim now button and show the amount remaining of NFT available.


![image](https://user-images.githubusercontent.com/93543576/207899028-fa985b19-8b99-4840-b908-5c165cd86d31.png)
