### ISSUE TITLE
1.) Sidebar Menu

### ISSUE THREAD

**Issue by StefanB90** [Pylons-tech/pylons#1554]
## UX / UI

[Figma Design Link](https://www.figma.com/file/QDHfg12EHmXgMd9jWsgEnC/Pylons-app-2.0?node-id=7254%3A4112&t=l8uVVu7a8B4L9HBi-4)
![Screen Shot 2022-12-08 at 12 17 51 PM](https://user-images.githubusercontent.com/97635071/206519783-86860870-50aa-4a8a-85ae-ac45dd8171cf.png)

## Acceptance Criteria

- Settings Sidebar prompted when settings menu icon located in top left corner of main screen in Pylons App is clicked. Rest of screen is tinted with dark shadow when sidebar menu is engaged.
- Grey highlight box appears when specific section label in sidebar menu is clicked.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by ahmadrns** [comment]
Start working on it

**Comment by ahmadrns** [comment]
@StefanB90  As `Edit profile` is highlighted, is it like when user clicks on any option it highlights or only `edit profile` is highlighted as defined in design.

**Comment by ahmadrns** [comment]
@StefanB90 when user clicked on `Cash Out` the menu portion color of drawer changes to black can you confirm?
https://www.figma.com/file/QDHfg12EHmXgMd9jWsgEnC/Pylons-app-2.0?node-id=7254%3A2999&t=SKHXhqI3x3FJybCR-0

**Comment by ahmadrns** [comment]
@StefanB90 That highlighted thing define just the splash effect or that tile is highlighted that user clicked.

**Comment by ahmadrns** [comment]
@StefanB90 Kindly provide me the use-case of social media account connectivity.
