### ISSUE TITLE
2.) Edit Profile

### ISSUE THREAD

**Issue by StefanB90** [Pylons-tech/pylons#1555]
## UX / UI

[Figma Design Link](https://www.figma.com/file/QDHfg12EHmXgMd9jWsgEnC/Pylons-app-2.0?node-id=7270%3A2411&t=l8uVVu7a8B4L9HBi-4)
![Screen Shot 2022-12-08 at 12 28 03 PM](https://user-images.githubusercontent.com/97635071/206521966-f2477377-f1dc-499a-82f1-2b9bb27f7ffa.png)

## Acceptance Criteria

- Edit profile pic updates in Edit Profile section and on Settings Sidebar Menu after saved using OS default selector.
- Bio section saves automatically after user inputs characters into designated section.
- Email address 2FA verification process displays blue checkmark next to Pylons username when user downloads Easel and creates a username.
- Link social media account process at the discretion of the engineering team.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by ahmadrns** [comment]
@StefanB90 Kindly provide me the use-case of social media account connectivity.

**Comment by ahmadrns** [comment]
@StefanB90  Taping the pencil icon will enable user to edit name and for changing the image user click on CircleAvatar accordingly. please confirm
