### ISSUE TITLE
Issue w/ executing recipes utilizing cookbook denoms

### ISSUE THREAD

**Issue by afti-githobo** [Pylons-tech/pylons#1871]
## Summary of Bug

Executing recipes that utilize cookbook-specific denoms in their coin costs will always give an insufficient-funds error for 0 of whatever coin, even when the account does in fact have sufficient funds.

```Tx error:5 failed to execute message; message index: 0: 0whatsit is smaller than 10whatsit: insufficient funds```

Note that it does not appear to matter whether or not the recipe specifies a cookbook prefix on the cost - the error is the same in either case.

## Version

current

## Steps to Reproduce

Run `appFlameClicker/RecipeGetWhatsit` 10 times, then run `appFlameClicker/RecipeBuyThingamabob`.

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by MikeSofaer** [comment]
@kjawadDeveloper2 @faisalnaveedRNS @faddat Any ideas on first glance?

**Comment by kjawadDeveloper2** [comment]
@MikeSofaer  no idea but have to check.
