### ISSUE TITLE
QR Code scanning does not work

### ISSUE THREAD

**Issue by MikeSofaer** [Pylons-tech/pylons#2375]
## Summary of Bug

When sharing an item from your creations the QR code displayed is not scannable.

This may be because of transparency.

## Steps to Reproduce

Create a work and try to scan the QR
____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by AhsanRns** [comment]
No this is not because of the tranparency. 

its because there is diffrence in colors of the dataModuleStyle & eyeStyle

**Comment by AhsanRns** [comment]
https://github.com/Pylons-tech/pylons/pull/2376
