### ISSUE TITLE
Publishing an image appears to fail

### ISSUE THREAD

**Issue by MikeSofaer** [Pylons-tech/pylons#2377]
## Summary of Bug

When publishing an image from Easel, an error toast appears at the bottom, and the navigation to the new item's page does not occur. The publish appears to succeed later, but it is not in the transactions list.

## Steps to Reproduce

Mint an image from Easel. The mint should communicate success if it succeeds, and navigate to the item page. The mint attempt should be in the transactions list, whether it succeeded or failed.
____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by AhsanRns** [comment]
https://github.com/Pylons-tech/pylons/pull/2382

this is the fix of the of the issue 


new issue is identified when the wallet is created new for some time like 10 - 30 min 

gRPC Error (code: 5, codeName: NOT_FOUND, message: account pylo1m3zpkv8n7mum4srp3m7lvheyaf4hx38wrdpkug not found, details: [], rawResponse: null, trailers: {})
