### ISSUE TITLE
All Pylons tokens should instead display as USD

### ISSUE THREAD

**Issue by MikeSofaer** [Pylons-tech/pylons#2378]
## Summary

The Pylons token confuses users. We should instead call pylons acquired from IAP "Pylons credits" and display them as USD at all times. In prices displayed, in the wallet tab, etc.

## Problem Definition

People who use Pylons are confused by what the pylons token is, and why they need to buy it. Non crypto natives feel they need to understand what is going on before they continue, and they do not understand the pylons token. People do understand what USD credit on a platform is, and since pylons tokens are basically platform credit we can use that to make them more comprehensible.

## Proposal

In the wallet tab change "Pylons" to "Pylons Credit" and display as $1.10 instead of 11 PYLN
In the creations tab on the green banners instead of "11 PYLN" display "$1.10 credit"
In the social cards displayed on Twitter, Telegram, and Discord, display "$1.10" instead of 11 PYLN
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by MikeSofaer** [comment]
For the currency dropdown in minting, it's currently "USD" and "PYLN" but we should change it to "Stripe" and 'IAP"

**Comment by AhsanRns** [comment]
https://github.com/Pylons-tech/pylons/pull/2390
