### ISSUE TITLE
Add BlockSlayer Items to Pylons App

### ISSUE THREAD

**Issue by MikeSofaer** [Pylons-tech/pylons#2379]
## Summary

Blockslayer progress should be visible in the Pylons app.

## Problem Definition

Blockslayer works, but players cannot see or list what they have earned in the Pylons app. Players should be able to see what they have in non-Easel Pylons apps in the Pylons app

## Proposal

Add a third tab to the Pylons App main section next to "Collection" and "Wallet" called "Items". Blockslayer characters should be visible in this tab.
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by AhsanRns** [comment]
https://github.com/Pylons-tech/pylons/pull/2398

here is the PR for the issue
