### ISSUE TITLE
Method for switching API endpoints

### ISSUE THREAD

**Issue by MikeSofaer** [Pylons-tech/pylons#2383]
## Summary

Create a system of tests and a guide to determine if an API endpoint is not working, and the process for finding and switching to a new API endpoint.

## Proposal

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by AhsanRns** [comment]
**There is already a way to update the endpoint in the system.** 

there is an environment file called **.prod_env**

there are different variable defined in that file one of them is called **env** -> `please change it to "test"/"any text you want" but not "prod" if this it will read value from remote config`

when you change this variable it will start reading value defined in the environment file 

now we are concerned to change the API endpoints 

its dependent on the two variables 

```
LCD_URL
LCD_PORT
```

please update this with your desired values 

now all request are send to your desired variable defined

**Comment by MikeSofaer** [comment]
OK. Maybe we should have an operations.md file that has instructions on how to do these things?
