### ISSUE TITLE
Game Development Recipe Deployment App

### ISSUE THREAD

**Issue by MikeSofaer** [Pylons-tech/pylons#2402]
## Summary

This is a Pylons app that a game developer can use to create and update the recipes that their game uses. Much like Easel, this allows the creation of cookbooks and recipes inside them. Ahsan has started something like this as part of creating a demo game.

## Proposal

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by gram-incolo** [comment]
@MikeSofaer after making MVP for the current applications, we can start with this right?
