### ISSUE TITLE
Internal QA Reported Issues

### ISSUE THREAD

**Issue by RNSSolutions** [Pylons-tech/pylons#2411]
1-Wallet Alias/name creation,it keeps the previous address and name ,you need to reopen the app after closing to get the updated info.
2-Invalid creation date.
3-Back button not working on Collection creation.
4-Drafts shows published status of collection.
5-Wallet State  update issue.
6-On Messages it prompts something went wrong.
7-Back button on general settings button area need to be updated

**Comment by gram-incolo** [comment]
we are not checking if the start date is before end date

**Comment by Raviramnani1** [comment]
> we are not checking if the start date is before end date
this issue has been fixed
