### ISSUE TITLE
Update recipe message requires correct AmountMinted to be set

### ISSUE THREAD

**Issue by afti-githobo** [Pylons-tech/pylons#561]
## Summary of Bug

At present, recipe update transactions (over RPC? unclear if this matters) will be rejected (for trying to set AmountMinted to a different value) unless they have an AmountMinted that is equal to what currently exists on chain. There's no reason for AmountMinted to be modified, and it makes workflows significantly more fiddly and brittle.

## Version

whatever rpc.testnet.pylons.tech is running on as of 5/6/22

## Steps to Reproduce

1) set up devtool 
2) make a cookbook and a recipe that mints an item; run it
3) modify the recipe, try to update it using devtool, expected `rpc error: code = InvalidArgument desc = failed to execute message; message index: 0: cannot modify AmountMinted field of a recipe`
4) create AmountMinted field and set to 1, try again - should work

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by hieuvubk** [comment]
@afti-githobo Is this bug fixed right? I tried and didn't see it anymore

**Comment by hieuvubk** [comment]
@MikeSofaer

**Comment by MikeSofaer** [comment]
Not sure, @faisalnaveedRNS might know
