### ISSUE TITLE
Two paths forward

### ISSUE THREAD

**Issue by faddat** [Pylons-tech/pylons#570]
Path 1:  we keep what is here and upgrade it

Path 2: we base this chain from notional-labs/craft and then re-add pylons module

NB: when I say "use craft" I mean only its "base", not its "features"

**Comment by MikeSofaer** [comment]
How do we go about thinking about this?

I think we have a relatively decent set of test cases for what the pylons module does, so pushing it onto a new chain base shouldn't be too insane. It would almost certainly require a reset, though, right?

**Comment by faddat** [comment]
It seems we can accomplish without a rewrite, I'm closing this, for a much more detailed issue.
