### ISSUE TITLE
Getting to a release

### ISSUE THREAD

**Issue by faddat** [Pylons-tech/pylons#577]
## goal

The specific goal here is to bring pylons to a public release, and that public release should be able to do nonfungible tokens over ibc.

## steps
These should happen concurrently.

* Remove starport
Blockchain and CLI development should no longer use the Star port/ignite CLI. The reason for this is that they are moving further and further from the standards to find in the cosmos STK, and it is difficult to apply both security and performance updates, as well as build the chain out in the direction that we would like. In order to have total control of the code base, we need to be able to set default settings, for example. However, if we continue to use the tooling, we will be unable to do so. I have had to make this unfortunate recommendation across a number of chains and to a number of teams who were invested in the tooling. I'm sorry that this is likely to cause an interruption in workflow. 

Removing starport involves restructuring the CMD folder in pylons. Please note that this is nowhere near as easy as it should be. I think that's likely intentional. We will need to restructure CMD and we will need to add a Paramus folder to the app folder. You can use Gaia or osmosis to gain work on this. Additionally, I am aware that there are other Blockchain engineers on this project, and if you are working on the chain at this time I would like to strongly suggest that you work to remove the cosmos CMD package. If you look at the branch I made a pr for yesterday, you'll also notice that it does not build. 

**we need to:**
* remove starport/ignite tooling.  we will know this is done when no modules map into github.com/ignite or github.com/tendermint/starport
* re-do tests using cosmos-sdk tooling
* upgrade to ibc v3.1 (done except app.go and antehandler changes)
* upgrade to cosmos-sdk v0.46.0-rc1 and eventually to the final release
* remove starport from cli tooling and the like
* determine if github.com/osmosis-labs/telescope can serve our needs for client libraries, which starport generates

**Personally I can**
* guide and assist these efforts

**The notional team can**
* end-to-end the blockchain pieces of it

...but I am assuming that it is more desirable for all parties to try and transfer some of this knowledge and ability to members of the Pylons team and community.  So I am planning on working with the pylons team as well as the notional team to break the work here down into pieces.

## Timeline

I would like to have all of this complete so the the Pylons chain can begin to operate, as soon as the final release of the cosmos SDK version 46 is finished.

I think that it is best to think of this like a house, with the blockchain as its foundation.  The team's vision goes much deeper than only having a chain, but having a chain to keep records of NFTs as property is central to that vision, so we should try to ensure that the blockchain launches first, then things that connect to it.

**Comment by MikeSofaer** [comment]
@faisalnaveedRNS @kjawadDeveloper2 @mustafapylons what are your thoughts on this?

**Comment by kjawadDeveloper2** [comment]
@faddat  since you have worked with other teams can you tell how much big this change is?

**Comment by mustafapylons** [comment]
@faddat I think it makes sense. However there is potentially major impact to how we build our products and we need to take a phased approach and we have to test it in dev environment for each phase to ensure we haven't regressed any functionality.  Three questions:

1- When you have delivered this for other chains, what are lessons learned and how can we apply here?

2- What're the phases and timeline for this delivery?

3- Suggestions you have for us how to remove dependency in our code to cosmos CMD package.

When I say phases, I am especially interested how we will accomplish the following:

1- remove starport/ignite tooling. we will know this is done when no modules map into github.com/ignite or github.com/tendermint/starport

2- remove starport from cli tooling and the like

Let's have a discussion Monday, Tuesday at a time that works for you and we can all have a quick whiteboard over this.
 
Mustafa

**Comment by faddat** [comment]
I think this is complete.
