### ISSUE TITLE
Stripe Payment Graceful Degradation

### ISSUE THREAD

**Issue by MikeSofaer** [Pylons-tech/pylons#586]
## Summary

Currently the purchase process for an item can fail after the Stripe purchase completes, and then the buyer is either stuck with a Stripe receipt or with StripeUSD that the user should not have, since they have not set up Stripe

## Problem Definition

It's bad for Pylons to have Stripe transactions occur that do not result in the execution of a recipe. We should think through the failure modes and ensure that we have the smoothest experience possible when users are spending money.

Users should not be sent to Stripe until we have confirmed that the recipe execution will succeed (meaning reserve a spot if the recipe is limited in execution count)

We should be able to resubmit transaction to the chain if the claim fails.

We should cleanly request a refund if we cannot finalize the transaction.

## Proposal

We should use the system we created for long-running executions (block delay) to hold space for a user to pay on Stripe and submit the recipe, so we know it won't be rejected.

There should be a way to expire reservations that have not been completed.

If the final execution fails, the wallet should automatically request a refund.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by hieuvubk** [comment]
@MikeSofaer Should we process the payment attached with recipe execution when it is complete? So, users' funds not be locked if the execution fails.

**Comment by MikeSofaer** [comment]
I think we need to process the payment before we finalize on chain, the payment is the more reversible side. But we should do as much as possible to ensure that the execution does not fail (as in create a pre-execution that is on chain and only requires to payment voucher to be finalized)

**Comment by hieuvubk** [comment]
![Ảnh chụp Màn hình 2022-06-21 lúc 04 19 22](https://user-images.githubusercontent.com/72878483/174679139-f5894c74-fa8f-4571-95b6-dc1268e0e2eb.png)
Hi why we move pendingExecution to Actualize here. I think when complete return err just remove the pending execution?

**Comment by MikeSofaer** [comment]
We need to keep the history, I think that's what it's doing.

**Comment by hieuvubk** [comment]
ah got it, thank u

**Comment by hieuvubk** [comment]
@MikeSofaer https://github.com/Pylons-tech/pylons/pull/600 can you take a look at this pr, handle payment when the execution fails

**Comment by MikeSofaer** [comment]
I think we don't ever want the buyer to have the payment coins, and it would be better to transfer the payment voucher to the seller and then mint the coins on the seller's account.

**Comment by hieuvubk** [comment]
I don't know in the recipe execution context who buyer and seller( U mean executor and recipe owner?)
And also we process payment before execution is complete so coins are already minted to the executor, fee collector module. Should have a mechanism to revert this process?

**Comment by MikeSofaer** [comment]
In this case recipe creator is the seller and recipe executor is the buyer.

What I'm saying is that I don't think we should process payment unless the execution succeeds. I think the executor should receive a voucher tied to the specific payment event off-chain, which can be used to process an off-chain refund if the execution does not succeed.
