### ISSUE TITLE
more composable/interoperable protos

### ISSUE THREAD

**Issue by pyramation** [Pylons-tech/pylons#607]
Hello! I'm working on tooling to generate clients, and a lot of chains are using a "standard" naming convention for storing the proto files.

For example,

- [./proto/stargaze](https://github.com/public-awesome/stargaze/tree/main/proto/stargaze)
- [./proto/osmosis](https://github.com/osmosis-labs/osmosis/tree/main/proto/osmosis)
- [./proto/akash](https://github.com/ovrclk/akash/tree/master/proto/akash)
- [./proto/cosmos](https://github.com/cosmos/cosmos-sdk/tree/main/proto/cosmos)
- [./proto/juno](https://github.com/CosmosContracts/juno/tree/main/proto/juno)

To make this more interoperable, can we

- [ ] move [./proto/epochs/](https://github.com/Pylons-tech/pylons/tree/main/proto/epochs) so it's `./proto/pylons/epochs` in `package pylons.epochs`?
- [ ] while we're at it, do we need `package Pylonstech.pylons.pylons`, could we do something more simple like `package pylons` or `package pylons.core`

These are obviously not required, but would be HUGE in terms of interoperability with the codegen tooling, as well as being similar in naming convention to all the above chains.

@faddat @nghuyenthevinh2000 I'm not sure the solution for how to name the `pylons.pylons` package so it's not duplicative

P.S. we did similar with we juno https://github.com/CosmosContracts/juno/issues/202 successfully 

```diff
- package CosmosContracts.juno.mint; 
+ package juno.mint; 
```

So, for pylons the current question is:

since we have the epochs could be reduced to this

```diff
- package Pylonstech.pylons.epochs;
+ package pylons.epochs;
```

but we'd still be left with an extra pylons in this case...

```diff
- package Pylonstech.pylons.pylons
+ package pylons.pylons
```

should we consider naming this pylons.pylons something like pylons.core or something you guys would suggest?

CAVEAT: this may be pedantic, but know the tooling can make this super clean if we use this naming convention, it's a good time to handle this. Happy either way, all suggestions.

**Comment by nghuyenthevinh2000** [comment]
uh, sure, I will do this
