### ISSUE TITLE
PRIORITY: test run time

### ISSUE THREAD

**Issue by faddat** [Pylons-tech/pylons#625]
## Summary of Bug

This is a priority issue.  We shouldn't do other chain related work till it is solved. 

We should reduce the time for a default ci test to 5 minutes or fewer.  The issue seems to be in the x/pylons folder, when we run:

```bash
cd x/pylons/client/cli
go test ./...
```

In that folder, `go test` freezes.  

I think this is because:

1) tests aren't run in parallel
2) we spin up and tear down many testnets in there

Currently I am using several techniques to find the test, including just running through all of them.  Any insights on this issue are greatly appreciated. 

## Version

main

## Steps to Reproduce

```bash
cd x/pylons/client/cli
go test ./...
```
____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by nghuyenthevinh2000** [comment]
this one takes long time as well in x/pylons: TestKeeperTestSuite/TestGetRewardsDistributionPercentages

It starts a network and on my computer takes about several mins

**Comment by faddat** [comment]
cool let's kill that.

**Comment by faddat** [comment]
test time reduced to 3 minutes.

tests replaced with table driven tests.

e2e tests to be added later.
