### ISSUE TITLE
How signature is generated?

### ISSUE THREAD

**Issue by nghuyenthevinh2000** [Pylons-tech/pylons#632]
I want to ask how these signature is generated so that I can do testing

![Screenshot from 2022-07-11 10-10-28](https://user-images.githubusercontent.com/23058164/178181835-69417307-ee34-4c11-91bb-a67cefee8e40.png)

**Comment by nghuyenthevinh2000** [comment]
Can you record the step to generate it. If you can record in a video, just love it. 

I mean like the data structure will still change a lot in the future. Sometimes a code change that I write fails to pass signature related test and I really don't know whether the code leads to problem or the signature is obsolete somehow.

**Comment by abdullahjankhan1** [comment]
The signature is generated at the mobile end, so I can't help there, but I am sure that the signature (it is a certificate that apple in-app-purchase returns to the mobile end) doesn't expire or gets obsolete.
