### ISSUE TITLE
SPIKE: obscure video NFT upload

### ISSUE THREAD

**Issue by faisalnaveedRNS** [Pylons-tech/pylons#642]
## Summary

Prevent copy right infringement on uploading a movie

## Problem Definition

how to prevent copyright infringement from potential Easel creators uploading a movie obtained illegally and then uploading to IPFS & listing the video NFT as available for sale on the Pylons app?

## Proposal

We case use google cloud base service to find video infringement
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by StefanB90** [comment]
This issue requires a discussion to provide next steps or close this issue.
