### ISSUE TITLE
Ensure that payouts happen at transaction time

### ISSUE THREAD

**Issue by faddat** [Pylons-tech/pylons#644]
We've removed the epochs module from Pylons. 

We need to ensure that payouts happen at the time of transaction.

**Comment by MikeSofaer** [comment]
Love this idea. Are you sure epochs are the right thing here? Giuseppe was sure we didn't want to do this stuff inline, but I wasn't so sure.

**Comment by faddat** [comment]
I am not sure what you mean. What stuff are we discussing?

**Comment by MikeSofaer** [comment]
The epoch module is used for paying out the chain commission. It doesn't seem like that should be so hard to do in the payment transaction. There aren't that many payment transactions!

**Comment by faddat** [comment]
@MikeSofaer based on my read of the code, default behavior is to pay at transaction time. 

So, without epochs, it should function as you describe.

**Comment by faddat** [comment]
NB: we should test this, I won't close till we have verified the behavior.

**Comment by StefanB90** [comment]
@faddat can we confirm this when possible? Have epochs been removed? Is this the right course of action? Thank you.
