### ISSUE TITLE
NFT ETH BUY ISSUE

### ISSUE THREAD

**Issue by faisalnaveedRNS** [Pylons-tech/pylons#677]
## Summary of Bug
User unable to buy nft with IBC transferred enough eth ETH from axelar, 

Refernce NFT is here 
http://35.188.86.73:4018/?action=purchase_nft&recipe_id=&cookbook_id=Easel_CookBook_auto_cookbook_2022_07_20_020951_069

./pylonsd tx pylons execute-recipe Easel_CookBook_auto_cookbook_2022_07_20_020951_069 Easel_Recipe_auto_recipe_2022_07_20_021129_848 0 '[]' '[]' --from eth-account

      "denom": "ibc/AAD7136DD626569C3DDE7C5F764968BB2E939875EFC568AE5712B62081850814",
      "amount": "10000000000000000"
      
      {
  "denom_trace": {
    "path": "transfer/channel-3",
    "base_denom": "weth-wei"
  }
}

## Version
0.4.2

## Steps to Reproduce

1. Transfer ETH to pylons using axelar
2. create NFT to sell for 0.01 ETH
3. Buy NFT from other user who have enough ETH

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by StefanB90** [comment]
deprioritized for the next few months. Revisit end of November.
