### ISSUE TITLE
Decouple recipe from the cookbook

### ISSUE THREAD

**Issue by kjawadDeveloper2** [Pylons-tech/pylons#694]
Right now a recipe is only unique within the cookbook. We need this recipe to be unique through out the chain.

P.S: Right now all the queries and api calls need cookbookId to get info of a recipe. e.g get-recipe

**Comment by MikeSofaer** [comment]
I think the situation is that recipes have both a user-created recipe name (not unique) and a unique ID. We should be able to query the recipe by the ID as well as by the combination of recipe and cookbook names.

**Comment by kjawadDeveloper2** [comment]
@MikeSofaer  if i get query the recipe by id it will help me to remove the cookbook id from the share url.

**Comment by StefanB90** [comment]
quality of life ticket not critical for mainnet
