### ISSUE TITLE
Chain Panic on v46 upgrade

### ISSUE THREAD

**Issue by faisalnaveedRNS** [Pylons-tech/pylons#707]
## Summary of Bug
on chain start system panic on Get balance 

panic: math/big: cannot unmarshal "\n\bubedrock\x12\a4000000" into a *big.Int

goroutine 1 [running]:
github.com/cosmos/cosmos-sdk/x/bank/keeper.BaseViewKeeper.GetBalance({{_, _}, {_, _}, {_, _}}, {{0x2e2cd58, 0xc0001ac000}, {0x2e3e500, 0xc001377180}, ...}, ...)
	github.com/cosmos/cosmos-sdk@v0.46.0/x/bank/keeper/view.go:108 +0x20c
github.com/cosmos/cosmos-sdk/x/staking/keeper.Keeper.TotalBondedTokens({{0x2e14a38, 0xc0015446b0}, {0x2e3b7c0, 0xc000212c20}, {0x2e30dc0, 0xc001374d20}, {0x7f85702da890, 0xc001004840}, {0x2e3b580, 0xc00000e930}, ...}, ...)
	github.com/cosmos/cosmos-sdk@v0.46.0/x/staking/keeper/pool.go:62 +0x210
github.com/cosmos/cosmos-sdk/x/staking/keeper.Keeper.BondedRatio({{0x2e14a38, 0xc0015446b0}, {0x2e3b7c0, 0xc000212c20}, {0x2e30dc0, 0xc001374d20}, {0x7f85702da890, 0xc001004840}, {0x2e3b580, 0xc00000e930}, ...}, ...)
	github.com/cosmos/cosmos-sdk@v0.46.0/x/staking/keeper/pool.go:74 +0x29b
github.com/cosmos/cosmos-sdk/x/mint/keeper.Keeper.BondedRatio(...)
	github.com/cosmos/cosmos-sdk@v0.46.0/x/mint/keeper/keeper.go:93
github.com/cosmos/cosmos-sdk/x/mint.BeginBlocker({{0x2e2cd58, 0xc0001ac000}, {0x2e3e500, 0xc001377180}, {{0xb, 0x0}, {0xc000ddd010, 0x10}, 0x5d2, {0xc938cf, ...}, ...}, ...}, ...)
	github.com/cosmos/cosmos-sdk@v0.46.0/x/mint/abci.go:22 +0x318
github.com/cosmos/cosmos-sdk/x/mint.AppModule.BeginBlock(...)
	github.com/cosmos/cosmos-sdk@v0.46.0/x/mint/module.go:155
github.com/cosmos/cosmos-sdk/types/module.(*Manager).BeginBlock(_, {{0x2e2cd58, 0xc0001ac000}, {0x2e3e500, 0xc001377180}, {{0xb, 0x0}, {0xc000ddd010, 0x10}, 0x5d2, ...}, ...}, ...)
	github.com/cosmos/cosmos-sdk@v0.46.0/types/module/module.go:481 +0x398
github.com/Pylons-tech/pylons/app.(*PylonsApp).BeginBlocker(_, {{0x2e2cd58, 0xc0001ac000}, {0x2e3e500, 0xc001377180}, {{0xb, 0x0}, {0xc000ddd010, 0x10}, 0x5d2, ...}, ...}, ...)
	github.com/Pylons-tech/pylons/app/app.go:621 +0x7b
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).BeginBlock(_, {{0xc0001c9680, 0x20, 0x20}, {{0xb, 0x0}, {0xc000ddd010, 0x10}, 0x5d2, {0xc938cf, ...}, ...}, ...})
	github.com/cosmos/cosmos-sdk@v0.46.0/baseapp/abci.go:200 +0x843
github.com/tendermint/tendermint/abci/client.(*localClient).BeginBlockSync(_, {{0xc0001c9680, 0x20, 0x20}, {{0xb, 0x0}, {0xc000ddd010, 0x10}, 0x5d2, {0xc938cf, ...}, ...}, ...})
	github.com/tendermint/tendermint@v0.34.20/abci/client/local_client.go:280 +0x118
github.com/tendermint/tendermint/proxy.(*appConnConsensus).BeginBlockSync(_, {{0xc0001c9680, 0x20, 0x20}, {{0xb, 0x0}, {0xc000ddd010, 0x10}, 0x5d2, {0xc938cf, ...}, ...}, ...})
	github.com/tendermint/tendermint@v0.34.20/proxy/app_conn.go:81 +0x55
github.com/tendermint/tendermint/state.execBlockOnProxyApp({0x2e2e028?, 0xc0001da9c0}, {0x2e35640, 0xc00156d720}, 0xc0011785a0, {0x2e3c320, 0xc00156c710}, 0x5d1?)
	github.com/tendermint/tendermint@v0.34.20/state/execution.go:307 +0x3dd
github.com/tendermint/tendermint/state.(*BlockExecutor).ApplyBlock(_, {{{0xb, 0x0}, {0xc001bb65c0, 0x8}}, {0xc001bb65d0, 0x10}, 0x1, 0x5d1, {{0xc001b48300, ...}, ...}, ...}, ...)
	github.com/tendermint/tendermint@v0.34.20/state/execution.go:140 +0x171
github.com/tendermint/tendermint/consensus.(*Handshaker).replayBlock(_, {{{0xb, 0x0}, {0xc001bb65c0, 0x8}}, {0xc001bb65d0, 0x10}, 0x1, 0x5d1, {{0xc001b48300, ...}, ...}, ...}, ...)
	github.com/tendermint/tendermint@v0.34.20/consensus/replay.go:503 +0x23c
github.com/tendermint/tendermint/consensus.(*Handshaker).ReplayBlocks(_, {{{0xb, 0x0}, {0xc001bb65c0, 0x8}}, {0xc001bb65d0, 0x10}, 0x1, 0x5d1, {{0xc001b48300, ...}, ...}, ...}, ...)
	github.com/tendermint/tendermint@v0.34.20/consensus/replay.go:416 +0x7ae
github.com/tendermint/tendermint/consensus.(*Handshaker).Handshake(0xc00142fa58, {0x2e3ebc0, 0xc00123aa90})
	github.com/tendermint/tendermint@v0.34.20/consensus/replay.go:268 +0x3c8
github.com/tendermint/tendermint/node.doHandshake({_, _}, {{{0xb, 0x0}, {0xc001bb65c0, 0x8}}, {0xc001bb65d0, 0x10}, 0x1, 0x5d1, ...}, ...)
	github.com/tendermint/tendermint@v0.34.20/node/node.go:328 +0x1b8
github.com/tendermint/tendermint/node.NewNode(0xc000ea8280, {0x2e298a0, 0xc000dd6960}, 0xc00156c160, {0x2e0df40, 0xc00000ea50}, 0x1?, 0x0?, 0xc00156c4b0, {0x2e2e028, ...}, ...)
	github.com/tendermint/tendermint@v0.34.20/node/node.go:772 +0x577
github.com/cosmos/cosmos-sdk/server.startInProcess(_, {{0x0, 0x0, 0x0}, {0x2e4ac18, 0xc00136e7b0}, 0x0, {0xc00118cd50, 0xf}, {0x2e41388, ...}, ...}, ...)
	github.com/cosmos/cosmos-sdk@v0.46.0/server/start.go:300 +0x75b
github.com/cosmos/cosmos-sdk/server.StartCmd.func2(0xc000e9cf00?, {0x3fc6570?, 0x0?, 0x0?})
	github.com/cosmos/cosmos-sdk@v0.46.0/server/start.go:142 +0x148
github.com/spf13/cobra.(*Command).execute(0xc000e9cf00, {0x3fc6570, 0x0, 0x0})
	github.com/spf13/cobra@v1.5.0/command.go:872 +0x694
github.com/spf13/cobra.(*Command).ExecuteC(0xc000e5bb80)
	github.com/spf13/cobra@v1.5.0/command.go:990 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.5.0/command.go:918
github.com/spf13/cobra.(*Command).ExecuteContext(...)
	github.com/spf13/cobra@v1.5.0/command.go:911
github.com/cosmos/cosmos-sdk/server/cmd.Execute(0xc000e5bb80?, {0x21d4017, 0x7}, {0xc0001c92a0, 0x19})
	github.com/cosmos/cosmos-sdk@v0.46.0/server/cmd/execute.go:36 +0x20f
main.main()
	github.com/Pylons-tech/pylons/cmd/pylonsd/main.go:24 +0x105

## Version

v0.46.1

## Steps to Reproduce

1. Download v0.4.2 from [v0.4.2](https://github.com/Pylons-tech/pylons/releases/tag/v0.4.2)
2. create validator and start the chain
3. stop the validator
4. download latest code from [latest](https://github.com/Pylons-tech/pylons)
5. build the code using make build-linux
6. run pylonsd in artifacts directory

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by vuong177** [comment]
Thanks @faisalnaveedRNS. I'm digging on it

**Comment by vuong177** [comment]
Did you create a gov for update ? @faisalnaveedRNS
