### ISSUE TITLE
Confuse about logic calculate fee in FulfillTrade function in msg_server_fulfill_trade.go

### ISSUE THREAD

**Issue by ThanhNhann** [Pylons-tech/pylons#749]
## Summary of Bug
   - In `FulfillTrade` function I see a logic for calculate fee below: 
https://github.com/Pylons-tech/pylons/blob/4729c616de0d4d3c0c52593fa4ad17db1bacf987/x/pylons/keeper/msg_server_fulfill_trade.go#L171-L175 

   - From the initialization of `chainAmt `, `cookbookAmt `, we can see that `itemTransferFeeAmt ` = `cookbookAmt.Amount` + `chainAmt.Amount`, so that amount of `transferAmt ` = `itemTransferFeeAmt ` - `cookbookAmt.Amount` - `chainAmt.Amount` will always equal zero, it mean `inputTransferTotAmt ` will also equal zero too.
   - The same logic can be caught at here:
   https://github.com/Pylons-tech/pylons/blob/4729c616de0d4d3c0c52593fa4ad17db1bacf987/x/pylons/keeper/msg_server_fulfill_trade.go#L189-L193
   - I don't know if this is your logic or something like that, but I want to confirm this

## Version
`0.4.2`

## Steps to Reproduce

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by MikeSofaer** [comment]
This logic definitely seems more complex than it needs to be. Are there tests?

Trade fees have a few properties:

1) The chain can set a minimum trade fee (this is a bit like a gas fee for trading)
2) The item creator can take a percentage.

The total fee is the sum of its parts so that part makes sense. I think line 173 looks wrong, but I'm not sure. I think we should definitely make sure we have a lot of test cases on this.

**Comment by faddat** [comment]
I think the best solution here is:

1) comment the code to say what each line should do
2) based on 1, refactor this logic
3) write tests

we could do 3 first, but either way, I hit this exact section of this file and my thought was "hrm.  better not touch this....'

**Comment by ThanhNhann** [comment]
Yeah, I have the same thinking about the sum fee with you@MikeSofaer, and following steps with @faddat to check the code, tests will be added to check

**Comment by MikeSofaer** [comment]
I am a huge proponent of tests before refactoring. It should only take 5 or 6 cases to lock down behavior and then we can refactor, and hopefully make it clear enough not to need step 1.

**Comment by ThanhNhann** [comment]
Hi @MikeSofaer, do you have the document about the logic calculating fees of this function? I tested the code but to make sure it is wrong and refactor it, I need to know more about the logic behind it. I think trade fee has properties like you, but there are a lot of variables used that make confusion about how to get them

**Comment by MikeSofaer** [comment]
OK, where are the tests? I can go through them.

**Comment by ThanhNhann** [comment]
Sorry for the late @MikeSofaer, I have faced some mistakes about logic but now its done, pls check the cases () (I commented in detail on each case) 
https://github.com/Pylons-tech/pylons/blob/556435e7cacfb7f949b1d2a7b55aa5fef7bbec46/x/pylons/keeper/msg_server_fulfill_trade_test.go#L492

**Comment by ThanhNhann** [comment]
Do you have any documents for this trade logic @MikeSofaer

**Comment by MikeSofaer** [comment]
I don't really understand them, but I am glad they are there. I will go through them soon. Does the logic make more sense to you now? Do you still think it is broken?

**Comment by ThanhNhann** [comment]
Not yet sir, with the logic calculating fee, its mean the line of `Sencoins` below will always executed (with `tradeFulfillerAddr`and `tradeCreatorAddr ` are valid) because `inputTransferTotAmt` always equal zero. That mean free fee of pylon for this feature? right?

**Comment by MikeSofaer** [comment]
The way it is supposed to work is that the creator can set a minimum fee for an item, and also the network can set a transfer fee for all items. The user receiving the item must pay enough to cover those minimum fees, even if the user sending it is not getting anything.

**Comment by ThanhNhann** [comment]
Yeah I got you, but in this case, that fee always equals zero, I think this is an important point to think

**Comment by StefanB90** [comment]
Ongoing discussion in progress
