### ISSUE TITLE
Item ID provided when querying an execute-recipe transaction is not, in fact, the item id

### ISSUE THREAD

**Issue by afti-githobo** [Pylons-tech/pylons#759]
## Summary of Bug

When querying an execute recipe transaction that created an item with the CLI, the provided `itemId` field is populated with... something else. 

cf. 

https://pastebin.com/5N4jLHmm

`pylonsd query pylons get-item appTestCookbook 1550837-8901
Error: rpc error: code = InvalidArgument desc = rpc error: code = InvalidArgument desc = not found: invalid request`

(the actual id of the created item here is `J5FNYse1SCo`)

## Version

e4e6f8c9720f3011106ebc546ea5552e94186939

## Steps to Reproduce

`pylonsd tx pylons execute-recipe appTestCookbook RecipeTestAppGetCharacter 0, '[]' '[]'`

will run a recipe that creates an item; you can then get the incorrect id by running `pylonsd query tx` with that txhash

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by faddat** [comment]
Does this bug still exist?

**Comment by StefanB90** [comment]
@faisalnaveedRNS please confirm this after you've addressed the other critical issues this week. Thank you.
