### ISSUE TITLE
BedRock Dividend has to be calculated correctly.

### ISSUE THREAD

**Issue by mustafapylons** [Pylons-tech/pylons#764]
## Summary

In order to make this testable, we must set up a chain in keplr and suggest tokens to display (i.e. stripe USD, pylons &/or bedrock) for both internal users & validators --> Are the right people getting the right stablecoins suggested to them based on whether they are a validator or unaffiliated user?)

## Proposal

Auto detect wallet address in keplr and display the appropriate stablecoins based on their status/permissions/KYC validation.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by StefanB90** [comment]
@kjawadDeveloper2 do you have update regarding the Bedrock dividend calc?

Thank you sir.

**Comment by mustafapylons** [comment]
@faisalnaveedRNS team will take some more time on this ticket.

**Comment by StefanB90** [comment]
@abdullahjankhan1 please add PR so we can close this. Thank you.

**Comment by StefanB90** [comment]
for upgrade handlers, can show paper audit trail for transaction date, amount, sender, recipient, % allocation.

for dividends, can query all transactions and provide the same information (transaction date, amount, sender, recipient, % allocation.

this will essentially prove that bedrock tokens are being sent to the appropriate destination and the amount calculated and transferred is correct based on the predefined % allocation table.

**Comment by faisalnaveedRNS** [comment]
@abdullahjankhan1 Please add more test cases in it

**Comment by Tanyaml** [comment]
Check what dividend were paid out. The main mulitsig should have 40 cents- confirm @faisalnaveedRNS
