### ISSUE TITLE
Pylons points must not be transferable

### ISSUE THREAD

**Issue by MikeSofaer** [Pylons-tech/pylons#772]
Jawad let me know that he can send them from the console. This should not be permitted, Pylons Points should only be able to be spent in recipes or burned.

**Comment by vuong177** [comment]
@MikeSofaer could you provide txhash ?

**Comment by MikeSofaer** [comment]
@kjawadDeveloper2 can you send some Pylons and provide a txhash please?

**Comment by StefanB90** [comment]
@kjawadDeveloper2 can you still send pylon points to other people?

If you cannot, then we can close this. If you can, then we must prevent this tx from occurring.

**Comment by StefanB90** [comment]
folks can use the chain to move pylons points. We need to ensure that this is not possible.

**Comment by StefanB90** [comment]
there's a flag in the bank module that designates whether tokens are transferrable

**Comment by faisalnaveedRNS** [comment]
updated, but I think that also need to add, in upgrade handler,

**Comment by StefanB90** [comment]
To be completed by 9/23

cc @MikeSofaer @mustafapylons @faisalnaveedRNS

**Comment by StefanB90** [comment]
new upgrade handler branch: `https://github.com/Pylons-tech/pylons/tree/nhan/upgrade-handler`
