### ISSUE TITLE
Updating readme.md file

### ISSUE THREAD

**Issue by mustafapylons** [Pylons-tech/pylons#778]
## Summary
Let's update readme.md file with the attached file.
[README.md](https://github.com/Pylons-tech/pylons/files/9312653/README.md)

## Proposal

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by heyitsjk** [comment]
need clarification on this from @MikeSofaer -- are we "Pylons LLC" or "Pylons, Inc."?

**Comment by MikeSofaer** [comment]
We became Pylons Inc. in April 2021

**Comment by heyitsjk** [comment]
new file with updated company tag + mike's docker instructions :
[README.md](https://github.com/Pylons-tech/pylons/files/9328845/README.md)
s

**Comment by heyitsjk** [comment]
new file with updated company tag + mike's docker instructions :
[README.md](https://github.com/Pylons-tech/pylons/files/9328851/README.md)

**Comment by heyitsjk** [comment]
new file with updated company tag + mike's docker instructions :
[README.md](https://github.com/Pylons-tech/pylons/files/9328858/README.md)
