### ISSUE TITLE
Using local keys to sign transactions while using gRPC endpoints

### ISSUE THREAD

**Issue by afti-githobo** [Pylons-tech/pylons#788]
## Summary

It should be possible to use the Pylons client to submit transactions over gRPC while using a local keypair to do that. It may be possible to do this already, in which case a how-to would be a perfectly cromulent resolution to this issue.

## Problem Definition

At present, it's trivial to use a local keypair for signing transactions with the CLI client, but the CLI is supposed to be deprecated in favor of using gRPC to interact with the chain. It's obviously possible to submit signed transactions over gRPC, but doing that means that any application written for a platform for which we don't ship a first-party wallet needs to be responsible for creating, storingg, and signing with its own keys.

## Proposal

One of two things needs to happen:

a) there's already a way to do this! In that case, just leave the info below and close the issue.

b) there isn't a way to do this! We need to be able to pass gRPC calls through the Pylons client, using a local keypair to handle signing where necessary.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by faddat** [comment]
did you for real just say cromulent?

amazing

**Comment by afti-githobo** [comment]
I mean, it's fine, and I want to stress that I don't *know* that this is actually a technical problem. It could, as allowed for here, just be a well-supported thing that I don't know how to do, in which case it's a *documentation* problem.

My *understanding* of the situation as it stands: the gRPC endpoints are the selfsame ones the mobile wallet is using, and so work w/ signed transactions. The CLI generates and signs transactions using a local key, but Should Be Avoided. This means that using the gPRC endpoints significantly increases the responsibilities of even a minimal app.

My proposed solution, provided one does not in fact exist, is to be able to pass gRPC calls through the Pylons client, if installed, and have it take responsibility for signing using the provided local keypair.

**Comment by StefanB90** [comment]
@afti-githobo do you feel satisfied with the feedback provided? If so, we can close this. If not, we should set up a thread in the code channel to get to the bottom of this. Thank you.

**Comment by afti-githobo** [comment]
we can close this; it's not an issue, the initial advice was just bad
