### ISSUE TITLE
Add "Submit Feedback" functionality

### ISSUE THREAD

**Issue by StefanB90** [Pylons-tech/pylons#807]
## Summary

We must make it easier for users to submit feedback by adding the capability for users to share their feedback to the flag icon located at the top right corner of the NFT fullscreen view, as well as at the bottom of the Settings menu underneath "Legal" and above "Delete Wallet" 

## Problem Definition

Currently, our users can only submit feedback requests on our support channel in Discord. We need to make it easier for our users to help us identify bugs or inconsistencies in our UX / UI, as well propose new features they'd like us to prioritize (i.e. "Dark mode")

## Proposal

When you click the flag icon in the top right corner of the NFT fullscreen view, you will have the option to submit feedback in addition to reporting an offense. A dialog popup box will appear allowing the user to input their feedback (up to 256 characters with character counter akin to Description box used in Easel)

When a user goes to Settings > Submit Feedback, they will see two input fields:

1. Subject
2. Description

The "Subject" field will leverage the design used for the NFT name field currently used in Easel. The Description field will be the one used in Easel, allowing users to enter up to 256 characters (with character counter) and press the "Submit" button located at the bottom of the screen (akin to the "Continue" button in Easel) 

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by faizhashmiRnS** [comment]
HI @StefanB90 , 

1. we will have just description box when user presses flag button from NFT view but we will have both "Subject" and "Description" fields when user come from settings > Feedback, right?

2. Where to push data when user presses "Submit" ?

**Comment by StefanB90** [comment]
@justyntemme can this information be stored in mongoDB or a SQL DB?

**Comment by MikeSofaer** [comment]
We can probably use Firebase for this

**Comment by StefanB90** [comment]
@faizhashmiRnS please be so kind as to set up an automated email that notifies us when user feedback has been submitted so we may leverage it moving forward. Thank you!

**Comment by MikeSofaer** [comment]
@justyntemme might be able to wire up something that pumps feedback straight into a Discord channel.

**Comment by faizhashmiRnS** [comment]
> assigned

Alright, i will look into it.

**Comment by heyitsjk** [comment]
This is already implemented

**Comment by faisalnaveedRNS** [comment]
@kjawadDeveloper2 is there is no further development can we close  this ticket.
