### ISSUE TITLE
Upload Status = Success message should not be displayed unless the file has been successfully uploaded to IPFS

### ISSUE THREAD

**Issue by StefanB90** [Pylons-tech/pylons#812]
## Summary of Bug

Status = Success message in the IPFS Upload confirmation box that appears once an Easel creator uploads their file to IPFS should not be displayed until the file is actually successfully uploaded. If the file is loading, the message should display "in progress" or "processing" in pylons yellow font color (#FED564). If it fails to upload, then it should display "Failed" in pylons red font color (#EF4421).

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by faizhashmiRnS** [comment]
Hi @StefanB90 , It only shows that dialog when image is successfully uploaded. It anything goes wrong it will not show the dialog.
The loading or shimmer effect you see in the dialog is basically to load the thumbnail of that NFT. 
Should we replace the dialog success status with the thumbnail loading status?

**Comment by StefanB90** [comment]
@faizhashmiRnS if the thumbnail is shimmering then Status = In progress

If thumbnail is displayed and file is indeed uploaded to IPFS (meaning I can click view on IPFS for 2D images, audio & video files) then Status = Success

**Comment by faizhashmiRnS** [comment]
Hi @Tanyaml, Please test this.

**Comment by faizhashmiRnS** [comment]
@ahmadrns Please look into this issue.

**Comment by kjawadDeveloper2** [comment]
@Tanyaml  check this also in new build.
