### ISSUE TITLE
CI for wallet app

### ISSUE THREAD

**Issue by kjawadDeveloper2** [Pylons-tech/pylons#813]
`flutter analyze .` checks static analysis issue.

`flutter format .` formats the app.

`flutter test`  run the test for the app. 

`flutter build appbundle --flavor prod -t lib/main/main_prod.dart` is used for building a production build for android

`flutter build ios --flavor prod -t lib/main/main_prod.dart` is used for building a production build for ios

**Comment by StefanB90** [comment]
@kjawadDeveloper2 has this been completed? Please verify and close when possible. Thank you.
