### ISSUE TITLE
Android User clicks on NFT to purchase or view from Artist, User should  be directed to Pylons App

### ISSUE THREAD

**Issue by Tanyaml** [Pylons-tech/pylons#815]
## Summary of Bug

When Artist shares link to purchase NFT- User should be directed to Pylons App and purchase NFT from Pylons App.

Actual Results:

When Android user clicks on NFT to purchase or view from Artist, User is directed to Big Dipper.

Expected Results:

Android User clicks on NFT to purchase or view from Artist, User will be directed to Pylons App.

## Version
Latest Build of Android

## Steps to Reproduce
1. User will click on shared NFT LINK
2. User will be Directed to Big Dipper
3. User will land on Big Dipper webpage.

https://user-images.githubusercontent.com/93543576/185440696-5f29d7f9-986b-451b-b412-ad64787cf7da.mov

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by StefanB90** [comment]
Still needs to be addressed

**Comment by Tanyaml** [comment]
I have validated and it is working as expected:Android User clicks on NFT to purchase or view from Artist, User should be directed to Pylons App 

Please see video:

https://user-images.githubusercontent.com/93543576/188755820-639982d7-e06c-4e61-b7be-5ea8cdd63eed.mov
