### ISSUE TITLE
Wallet: Path to done

### ISSUE THREAD

**Issue by faddat** [Pylons-tech/pylons#823]
## immediate

* all packages in the wallet should be published to pub
  - [ ] tendermint packages
  - [ ] pdf viewer
  - [ ] android webview
  - [ ] alan
  - [ ] any others

 - [ ] packages in the wallet must not depend on git repositories and a commit hash
 - [ ] the wallet must not use any version overrides
 - [ ] customizations to any wallet dependency (alan) should be in this repository
 - [ ] unused transaction types should be removed from the wallet
 - [ ] unneeded boilderplate code should be removed from the wallet
 - [ ] the wallet should use the latest versions of every dependency to the greatest extent possible
- [ ] the transaction signing gateway package must
  - [ ] live in this repo
  - [ ] be published to pub
 - [ ] google cloud backup for keys needs to be thoroughly re-evaluated and maybe scrapped

## goals

* code size of wallet should shrink dramatically, estimate more than half
* we should reduce the number of dependencies that the wallet has
* we should evaluate other codebases or consider a full rewrite

**Comment by StefanB90** [comment]
revisit with @faddat when he returns.
