### ISSUE TITLE
When User clicks on NFT on Pixel 4 Device UI is incorrect

### ISSUE THREAD

**Issue by Tanyaml** [Pylons-tech/pylons#825]
## Summary of Bug
Actual Results:
When User clicks on NFT on Pixel Device UI is incorrect;
When user clicks on NFT:
1.  The  NFT image does not have the mobile template with the image
2. The TITLE , OWNERSHIP, NFT DETAIL, HISTORY not seen unless user clicks arrow
3. The Purchase button is on the wrong side- it should be on the right 

Expected Results:
When User clicks on NFT on Pixel 4 Device UI 
When user clicks on NFT - 
1.  The  NFT image has the mobile template with the image
2. The title and tabs are seen: TITLE , OWNERSHIP, NFT DETAIL, HISTORY
3. The Purchase button is on the wrong side- it should be on the right 

## Steps to Reproduce
1.User is using Pixel 4 Device and Clicks on shared NFT
2.User is directed toBig Dipper to purchase  NFT 
3.User is now on Big Dipper and is able to view incorrect UI for Pixel Device

Uploading UI issue in Pixel.mov…

3.User is on Big Dipper and now is able to view the incorrect UI of Big Dipper

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by AbdullahJanKhan** [comment]
@Tanyaml Can you please share the screenshot for incorrect UI

**Comment by abdullahjankhan1** [comment]
Is fixed in PR https://github.com/Pylons-tech/pylons/pull/865

Screen Outputs:

![image](https://user-images.githubusercontent.com/101688102/186421495-20eafa65-2240-40f6-8267-c5366df961f6.png) 

![image](https://user-images.githubusercontent.com/101688102/186421385-25dc046a-7297-41a4-b2dc-4121b2a84b77.png)

**Comment by Tanyaml** [comment]
@AbdullahJanKhan @faisalnaveedRNS  This is not correct. Please see video on how it is supposed to look.



https://user-images.githubusercontent.com/93543576/186431253-6ce25b79-3ab3-4695-8612-3e42e8769e7a.mov

**Comment by faisalnaveedRNS** [comment]
i think these is also resolved

**Comment by faisalnaveedRNS** [comment]
@Tanyaml

**Comment by Tanyaml** [comment]
@faisalnaveedRNS  @StefanB90 Yes we can close this.
