### ISSUE TITLE
When User is in Pylons Wallet Purchasing Pylons On Galaxy A8 + Pixel 3 "Something went wrong" message pops-up

### ISSUE THREAD

**Issue by Tanyaml** [Pylons-tech/pylons#826]
## Summary of Bug
Actual Results:
When User is in Pylons Wallet Purchasing Pylons On Galaxy A8 + Pixel 3- "Something went wrong" message pops-up.

Expected Results:
When User is in Pylons Wallet Purchasing Pylons On Galaxy A8 + Pixel 3- User should be able to purchase and have added pylons to the wallet and user can now purchase NFT.

Please see video:

https://user-images.githubusercontent.com/93543576/186011064-be371847-3090-4844-9aba-20fcfdafa97e.mov

https://user-images.githubusercontent.com/93543576/186009708-2a7b8e41-7d6c-4636-aaa5-25ad8164255e.mov

## Steps to Reproduce
1. User will click on NFT to purchase
2. User will click on buy button to purchase NFT 
3. Add Pylons pop-up screen appears 
4. User clicks on add and then is directed to Pylons buy screen
5. User clicks on buy and this when Something went wrong message appears.

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by faizhashmiRnS** [comment]
@kjawadDeveloper2  We are currently unable to reproduce this issue on our end. After even trying on the phones mentioned above.

**Comment by StefanB90** [comment]
@StefanB90 test on Samsung device to see if this is device specific or Android overall

**Comment by StefanB90** [comment]
Linked to more meaningful message issue
CC @Tanyaml @StefanB90

**Comment by Tanyaml** [comment]
@StefanB90 When User is in Pylons Wallet Purchasing Pylons On Galaxy A8 + Pixel 3 "Something went wrong" message pops-up has been resolved and now working as expected.

Please see Video:
Galaxy 
https://user-images.githubusercontent.com/93543576/188200224-80d5e18a-564b-49d5-8dc5-dcafb91cc198.mov














PIxel:
Uploading Pixel Validated #826.mov…
