### ISSUE TITLE
Need more meaningful message than "Something went wrong" during error scenarios.

### ISSUE THREAD

**Issue by mustafapylons** [Pylons-tech/pylons#827]
## Summary of Bug

We should change the message "Something went wrong" to "Something went wrong. Try restarting the app."

## Steps to Reproduce

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by StefanB90** [comment]
@Tanyaml please test when possible. Thank you.

**Comment by Tanyaml** [comment]
@StefanB90  I have validated the "Something went wrong. Try restarting the app." and is working as expected.

Please See video:
Android:

https://user-images.githubusercontent.com/93543576/188254078-64770528-2ee0-455c-80b4-cc8c4d652ebf.mov













Please Video:
iOS

https://user-images.githubusercontent.com/93543576/188254122-acf50d76-d75d-4d3b-a226-008c51409e75.mov
