### ISSUE TITLE
Remove view counts from BigDipper. (This is not working at the moment).

### ISSUE THREAD

**Issue by mustafapylons** [Pylons-tech/pylons#828]
## Summary of Bug

Remove view counts from BigDipper. (This is not working at the moment).

## Steps to Reproduce

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by faisalnaveedRNS** [comment]
I think there already API that are ready, we only need to connect with them

**Comment by faisalnaveedRNS** [comment]
@abdullahjankhan1 please follow with the Big dipper team to finalize it

**Comment by abdullahjankhan1** [comment]
It will be fixed with 
PR https://github.com/Pylons-tech/pylons/pull/833
