### ISSUE TITLE
Pylons App should have capability to make NFTs created by blacklisted users invisible.

### ISSUE THREAD

**Issue by mustafapylons** [Pylons-tech/pylons#829]
## Proposal

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by faizhashmiRnS** [comment]
@kjawadDeveloper2 This needs more discussion.

**Comment by StefanB90** [comment]
@mustafapylons to set up discussion to carry this forward. Lower priority

**Comment by kjawadDeveloper2** [comment]
@mustafapylons how we can know that a specific person is blacklisted?
