### ISSUE TITLE
Easel should only price USD or Pylons for now.

### ISSUE THREAD

**Issue by mustafapylons** [Pylons-tech/pylons#831]
## Summary

Easel should only price USD or Pylons for now.

## Proposal

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by StefanB90** [comment]
@Tanyaml please verify when possible. Thank you.

**Comment by Tanyaml** [comment]
I have validated Easel should only price USD or Pylons.

Please see screenshots:

iOS:

![ios Price ](https://user-images.githubusercontent.com/93543576/189765287-7338de72-ba7e-44c9-9fe5-b0f77c0ba14c.jpg)

Android:
![Android price ](https://user-images.githubusercontent.com/93543576/189765417-7708faf8-d329-403f-bbf0-ca0fc5291217.jpg)
