### ISSUE TITLE
Grey shadow skeleton placeholder for new drafts where thumbnail is not yet available

### ISSUE THREAD

**Issue by StefanB90** [Pylons-tech/pylons#832]
## Summary

Given the variability in IPFS upload time in order for Easel or Evently to display the NFT thumbnail image in the Creator Hub or Event Hub respectively, we've created a grey skeleton image that can be used until the thumbnail image can be properly displayed:

![Screen Shot 2022-08-22 at 5 40 20 PM](https://user-images.githubusercontent.com/97635071/186023730-a72afad9-0099-489a-a334-17baa868bc0e.png)

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by faizhashmiRnS** [comment]
@kjawadDeveloper2 can we close this issue if its approved and tested?

**Comment by StefanB90** [comment]
@kjawadDeveloper2 please confirm if this has been implemented for Easel. Thank you.
