### ISSUE TITLE
Big Dipper Mobile Browser Layout

### ISSUE THREAD

**Issue by StefanB90** [Pylons-tech/pylons#835]
## Summary

[https://www.figma.com/file/KgrDNaC6Cbn445c17qrx0j/block-explorer?node-id=784%3A911](url)

![image](https://user-images.githubusercontent.com/97635071/186179858-48b5b58f-7aa8-4b49-b1ca-4681fb1d13b0.png)

[https://www.figma.com/file/KgrDNaC6Cbn445c17qrx0j/block-explorer?node-id=794%3A35](url)

![image](https://user-images.githubusercontent.com/97635071/186180055-e06efe45-6fc1-422e-8c9c-fd9eb382aea5.png)

## Problem Definition

Current NFT full screen mobile browser view in Big Dipper:
![image](https://user-images.githubusercontent.com/97635071/186180143-a1177b67-614d-4aff-be7b-ea3dfe5d954a.png)

Previously, we only had the image (no device frame)

Font is not scaled appropriately and lines continue behind the phone frame

![image](https://user-images.githubusercontent.com/97635071/186180339-b1eb3574-0ec8-4c00-87cc-933c264b68e0.png)

## Proposal

Full screen NFT view in Big Dipper for Mobile Browser format that scales appropriately and displays the full screen NFT view according to the device type (i.e. mobile, tablet, desktop)
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by StefanB90** [comment]
[https://pylonstech.atlassian.net/browse/PS-491](url)

**Comment by faisalnaveedRNS** [comment]
@StefanB90 please close this issue, this is already done

**Comment by faisalnaveedRNS** [comment]
@Tanyaml i think this is already done, can we close this issue

**Comment by Tanyaml** [comment]
@faisalnaveedRNS  Yes it is done. We can close it @StefanB90
