### ISSUE TITLE
Messages & Push Notifications

### ISSUE THREAD

**Issue by StefanB90** [Pylons-tech/pylons#838]
## Summary

![image](https://user-images.githubusercontent.com/97635071/186187662-00abb910-3d01-4dd9-ba9f-8477abb6360f.png)

**To start, we will have four push notifications/in-app messages:**

1. “You’re NFT [NFT Title] has been sold. Your total proceeds are [$XYZ USD]”
2. “The first edition of [NFT Title] has been sold. Your total proceeds are [$XYZ USD]”
3. “Half of the editions for [NFT Title] have been sold. You’re total proceeds are [$XYZ USD]”
4. “All editions for [NFT Title] have been sold. Your total proceeds are [$XYZ USD]”

**_NOTE: total proceeds = proceeds from sale after pylons fee = 0.90(Listed Price * number of editions sold)_**

## Problem Definition

we need to inform Easel creators and Pylons app users with pertinent status updates regarding NFTs they've listed for sale.

## Proposal

- New envelop icon next to banner image icon in top right corner which displays a red dot when there are unread messages.
- Pop-up modal which prompts only when your NFT has been sold.
- Messages will only generate when actively listed NFTs are sold.

_NOTE: requires BD deployment on testnet to enable push notifications_
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by StefanB90** [comment]
https://pylonstech.atlassian.net/browse/PS-349

**Comment by StefanB90** [comment]
@Tanyaml lower priority. We can test this together when you've closed the other issues.

**Comment by Tanyaml** [comment]
@faisalnaveedRNS I have test the Messages & Push Notifications and it is not working as expected.

Please see videos:

Android:

https://user-images.githubusercontent.com/93543576/188761747-99c32dee-cd25-46fc-a6d2-d55527772dd5.mov



iOS:


https://user-images.githubusercontent.com/93543576/188761835-5f23ec48-0ab9-4a2d-95c5-16a647ab0a08.mov

**Comment by Tanyaml** [comment]
@faisalnaveedRNS This is not working as expected.

Please videos:

Android:



iOS:

https://user-images.githubusercontent.com/93543576/188761614-9ea28d54-747f-4ade-ae8e-0826da04743c.mov

@faisalnaveedRNS 

Please see screen shot: 
The Audio playback is not in the right postion: 
See screenshot:



![Screen Shot 2022-09-06 at 9 29 21 PM](https://user-images.githubusercontent.com/93543576/188768915-078b878c-a258-47af-ae29-09bfae8ebaec.png)

**Comment by Tanyaml** [comment]
@faisalnaveedRNS any update on this?

**Comment by kjawadDeveloper2** [comment]
@Amean you can work on this with faisal.
