### ISSUE TITLE
Populate Ownership, NFT Detail & History with real data

### ISSUE THREAD

**Issue by StefanB90** [Pylons-tech/pylons#840]
## Summary

Please populate the three expandable subsections of the NFT full screen view (pop-up box maximized) with real data pertaining to the NFT:
![image](https://user-images.githubusercontent.com/97635071/186190830-5b81b462-9c73-4935-8d4b-c965bfcadeba.png)

Per @abdullahjankhan1 These are the endpoints for item history:
GetItemOwnershipHistory → Item history 
{grpc_endpoint}/pylons/item_history/{cookbook_id}/{item_id}

## Problem Definition

Users want to know as much as possible about a NFT before they decide to purchase it. Creators want to convey legitimacy by providing potential buyers with as much information as possible regarding NFTs they've listed for sale.

## Proposal

There shouldn't be any placeholder data in the Ownership, NFT Detail or History subsections of the NFT full screen view. Please only display real data we obtain from the Pylons chain, IPFS or corresponding metadata therein.
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by StefanB90** [comment]
[https://pylonstech.atlassian.net/browse/PS-52](url)

**Comment by faizhashmiRnS** [comment]
@kjawadDeveloper2 can we close this issue if its approved and tested?

**Comment by faizhashmiRnS** [comment]
@kjawadDeveloper2 can we close this issue if its approved and tested?

**Comment by StefanB90** [comment]
@Tanyaml I'll take this one

**Comment by Tanyaml** [comment]
@StefanB90  The buy option actual results screen  does not have the History tab and  Buy Button when expanding subsections of the NFT full screen the as previewed in the  figma file attached. Can you confirm that the screenshot attached is valid, if not please advise.

See video and screenshot:

https://zube.io/files/pylons/2caaf8606b73bfdbfbf18b0bc34f3f81-ios-invaild-subsections-of-the-nft-full-screen.mov


![Screen Shot 2022-09-15 at 10.29.28 PM.png](https://zube.io/files/pylons/6f4ac54688cd70be6594f3341a69d0aa-screen-shot-2022-09-15-at-10-29-28-pm.png)

**Comment by faizhashmiRnS** [comment]
Hi @Tanyaml , 
1. The issue when Buy Button is not showing when expanded, is Fixed. Please test when you are able to.
2. Please make sure you are checking History Tab on a purchased NFT. 

@kjawadDeveloper2 
We are only showing the History tab in case of a purchased NFT `(viewModel.nft.type != NftType.TYPE_RECIPE).`

Please advise if that needs any changes.
