### ISSUE TITLE
App check not working for console

### ISSUE THREAD

**Issue by StefanB90** [Pylons-tech/pylons#842]
## Summary of Bug

app check is not working --> not detecting if a token is real

was able to create app check for any console and it wasn't verifying anything at all.

Purpose of app check is to prevent spam. We need app check on the client & console-side.

Create console account on your phone and import seed phrase.

## Version

reference @afti-githobo test build

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by StefanB90** [comment]
Long-term goal: use AuthZ

**Comment by StefanB90** [comment]
no mobile yet, will need one soon.

**Comment by abdullahjankhan1** [comment]
@afti-githobo can I get the app check I need to verify before making the PR? I have enabled it.
Thanks

**Comment by abdullahjankhan1** [comment]
@StefanB90 

Handled in PR https://github.com/Pylons-tech/pylons/pull/910

**Comment by StefanB90** [comment]
P1 - part of this is handled. Second part will be completed this week.

**Comment by faisalnaveedRNS** [comment]
@justyntemme as per our discussion, please test this ticket and close this issue
