### ISSUE TITLE
Cel execution is broken when a recipe contains rand() calls/potentially other customs?

### ISSUE THREAD

**Issue by afti-githobo** [Pylons-tech/pylons#843]
## Summary of Bug

When executing a recipe that contains a cell expression that calls the integer rand() function (tested, possibly others?) *no* cel expressions attached to that recipe will execute. The recipe will run and do nothing. Removing the expression that uses the rand() function, however, will cause the other expressions to start working again.

## Version

v1.0.0-rc1

## Steps to Reproduce

a) make a recipe containing two cel expressions, one of which uses long rand()
b) execute it

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by StefanB90** [comment]
P2 - @StefanB90 to add correct label

**Comment by faisalnaveedRNS** [comment]
@afti-githobo can you please provide more details on it, or sample video on this

**Comment by afti-githobo** [comment]
sorry, i forgot to get to you on this during the weekend

you could create the recipes in the pylons-tools-demo-app repo as of commit `a354695de88b114cb46cbe30ccb0ffded45ac8ac` w/ your own cookbook ID, run the create-character recipe, and then run the fight-goblin recipe. none of the expected state changes will take place.

**Comment by StefanB90** [comment]
we should not be going to mainnet with transaction that do the wrong thing

**Comment by StefanB90** [comment]
we are trying to build a general purpose chain that can be used across many different use cases. This is a fundamental issue that must be addressed.

**Comment by StefanB90** [comment]
TO BE COMPLETED BY 9/23

CC @MikeSofaer @mustafapylons @faisalnaveedRNS @afti-githobo
