### ISSUE TITLE
Firebase driven SKUs should be possible.

### ISSUE THREAD

**Issue by mustafapylons** [Pylons-tech/pylons#845]
## Summary

Firebase driven SKUs should be possible.

## Proposal

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by kjawadDeveloper2** [comment]
@MikeSofaer @mustafapylons @StefanB90  can you tell me how we will make design dynamic?   How we will now that how much bonus coins are in a package?

**Comment by MikeSofaer** [comment]
The chain has to have all the options programmed in for now, I'm not sure how we'd make it reliable otherwise. So it would be a list of the subset to display.

**Comment by kjawadDeveloper2** [comment]
@faisalnaveedRNS mobile side is now getting it from firebase remote config. Is there anything that chain has to do . Kindly look into it.

**Comment by faisalnaveedRNS** [comment]
[
  {
    "id": "pylons_10",
    "bonus": "",
    "subtitle": "$1.00",
    "pylons": "10 PYLN"
  },
  {
    "id": "pylons_35",
    "bonus": "(+5 Bonus)",
    "subtitle": "$3.00",
    "pylons": "35 PYLN"
  },
  {
    "id": "pylons_60",
    "bonus": "(+10 Bonus)",
    "subtitle": "$5.00",
    "pylons": "50 PYLN"
  }
]
@aliirns please check chain have following skus

**Comment by aliirns** [comment]
We cannot perform Firebase calls from the chain , as it involves storing secrets which would be a security concern .
SKU's already exist in `x/pylons/types/params.go`

```
...
CoinDenom: PylonsCoinDenom,
	Packages: []GoogleInAppPurchasePackage{
		{PackageName: "tech.pylons.wallet", ProductId: "pylons_10", Amount: sdk.NewInt(10000000)},
		{PackageName: "tech.pylons.wallet", ProductId: "pylons_35", Amount: sdk.NewInt(35000000)},
		{PackageName: "tech.pylons.wallet", ProductId: "pylons_60", Amount: sdk.NewInt(60000000)},
	},
...
```

**Comment by faisalnaveedRNS** [comment]
@kjawadDeveloper2 cleared from our side

**Comment by StefanB90** [comment]
per @faisalnaveedRNS both teams have checked their respective tasks and we can close this issue.
