### ISSUE TITLE
update readme (again)

### ISSUE THREAD

**Issue by heyitsjk** [Pylons-tech/pylons#846]
Summary
Let's update readme.md file with the newest attached file.

+ includes updated Pylons branding, company name, & social links.
____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by heyitsjk** [comment]
[README.md](https://github.com/Pylons-tech/pylons/files/9410725/README.md)

**Comment by StefanB90** [comment]
@mustafapylons to speak with @heyitsjk to confirm

**Comment by heyitsjk** [comment]
Merged & Deployed : Sept. 9, 2022
