### ISSUE TITLE
Add support for .GIF uploads to Easel

### ISSUE THREAD

**Issue by heyitsjk** [Pylons-tech/pylons#847]
## Summary

Add support for .GIF uploads to Easel

## Problem Definition

GIFs are widely used within the NFT community, it makes sense for Easel to support this format when we support a multitude of other image formats. IPFS supports the uploads of .GIFs 

## Proposal

Add the ability to upload .GIF files to Easel.
Add the ability for the Pylons app/Big Dipper to display .GIF uploads. 

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by faizhashmiRnS** [comment]
@kjawadDeveloper2 Can you please mention the design for this feature?

**Comment by MikeSofaer** [comment]
It should be supported as a type of image file, no design changes.

**Comment by StefanB90** [comment]
Let's go with option #1 and allow user to pick .GIF from Images

Thank you
