### ISSUE TITLE
Pylons Wallet Language Settings Errors 

### ISSUE THREAD

**Issue by Tanyaml** [Pylons-tech/pylons#871]
## Summary of Bug
Pylons Wallet Language Settings Errors: please see below

English working as expected
Russian works as expected 
Indonesia works as expected 

**German is not working as expected** 
1.Language shows Deutsch which is Incorrect- should be German** 
2.In the security tab  there should be no hyphen (-) near the word ID  
3.Hyphen letters are bold any letter that has a hyphen it is bold

**Korean  is not working as expected**
1.Main settings page format off- too long.

**Japanese  is not working as expected**
1.Japanese Main settings page format off- too long.
2.Security Tab  FACE ID  should be translated into Japanese for Login and Transaction

**Spanish  is not working as expected**
1.Hyphen letters are bold- any letter that has a hyphen it is bold
2.Main settings page format off- too long.

**Vietnamese  is not working as expected**
1.Hyphen letters are bold- any letter that has a hyphen it is bold
2.Main settings page format off- too long.

Please video attached and screen shots 
![German - Hypen letters are bolded](https://user-images.githubusercontent.com/93543576/186511860-8ac69114-51be-4ed3-9e31-23d60741f4c6.png)
![Korean format incorrect  main settings](https://user-images.githubusercontent.com/93543576/186511901-985ca8b7-69e6-47d4-abee-010b11249ba8.png)
![Japense Format incorrect-main settings](https://user-images.githubusercontent.com/93543576/186511929-e33fec52-9f13-4bca-96d9-6e60f4e29a35.png)
![Japenese Security tab incorrect](https://user-images.githubusercontent.com/93543576/186511951-6065cfd8-65ac-4f4a-8761-766fd7dab27d.png)
![Spanish Hypen words are bold](https://user-images.githubusercontent.com/93543576/186511980-7e45877e-c368-4484-9ebf-798aaa92f4fa.png)
![Spanish main settings incorrect format ](https://user-images.githubusercontent.com/93543576/186511999-a58cefe7-a792-4ba6-ba82-fea00dcc7446.png)
![Viet Main settings page format incorrect](https://user-images.githubusercontent.com/93543576/186512083-a0eb063c-e437-45d1-a471-392a3f8bab74.png)

## Steps to Reproduce
1.User Clicks on Main Setting in wallet
2.User Clicks on General 
3.User then clicks on language and changes the following languages (German, Korean, Japanese, Spanish, Vietnamese)

https://user-images.githubusercontent.com/93543576/186511737-adeb48f7-117d-487c-be6b-d4dcef45841d.mov

 and will see errors stated above 

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by kjawadDeveloper2** [comment]
@faizhashmiRnS  kindly look into it.

**Comment by Tanyaml** [comment]
@kjawadDeveloper2 

Please see below the following issues that been  fixed and not fixed stated near Issue. Note there is a few new issues as well please see new screenshots and video attached.

German is not working as expected
1.Language shows Deutsch which is Incorrect- should be German** **NOT FIXED**
2.In the security tab  there should be no hyphen (-) near the word ID: FIXED
3.Hyphen letters are bold any letter that has a hyphen it is bold: FIXED 

Korean  is not working as expected
1.Main settings page format off- too long. **NOT FIXED** 

Japanese  is not working as expected
1.Japanese Main settings page format off- too long. **NOT FIXED** 
2.Security Tab  FACE ID  should be translated into Japanese for Login and Transaction: Fixed

Spanish  is not working as expected: FIXED 
2.Main settings page format off- too long. **NOT FIXED** 

Vietnamese  is not working as expected
1.Hyphen letters are bold- any letter that has a hyphen it is bold: FIXED
2.Main settings page format off- too long : **NOT FIXED** 







**### New issues:**
1.Vietnamese- when displaying the language it is in- the acronym of Vietnamese which is VIE

![No Acronym for VIE](https://user-images.githubusercontent.com/93543576/186767619-886b70bd-29f2-4ef4-a683-96ccfc9d1c72.png)









2.Russian -Main settings page format off- too long


![Russian Main settings page Incorrect ](https://user-images.githubusercontent.com/93543576/186767633-592dcb8e-10f2-43a3-a57f-da99e44916fb.png)






3. Japanese- in notification screen the first line the word ID needs to spaced


![Jap Word ID  in frist line needs to spaced ](https://user-images.githubusercontent.com/93543576/186769203-39902b96-c321-4b2b-91e2-815533a3105c.png)




4. Spanish-  
A. Font size  looks like different size for General, Recuperacion, Legal, Borrar biltera 
B. Capitalize  the word  the letter B in the word biografia 

![Spanish Font size differnt and caplatize Bio](https://user-images.githubusercontent.com/93543576/186770039-6260ed23-a3a5-4cab-95f1-cdc972b6e420.png)



C. Font size looks like a different size for Hypen letters on the  Seguridad Screen 

![Spanish Font size looks off for hypen letters ](https://user-images.githubusercontent.com/93543576/186770486-00395802-ca46-47a0-bc48-4e36aff62e06.png)











Uploading Main Setting Language Error V2.mov…

**Comment by faizhashmiRnS** [comment]
Hi @Tanyaml , Can you please elaborate this line a bit?

""Main settings page format off- too long""

Thanks

**Comment by Tanyaml** [comment]
Hi @faizhashmiRnS  The actual format of the main settings page for the bottom does not have a closing to the box, hence it is scaled over the box. Please ping me if you need more explanation @Tanyaml 

Please see the screenshot of the correct scaled format main settings page.


![Correct Format Of Main Settings Page](https://user-images.githubusercontent.com/93543576/186916846-f1b00307-4298-4128-9ae7-a004aab9e1cf.png)

**Comment by Tanyaml** [comment]
@faizhashmiRnS  @kjawadDeveloper2 

German is not working as expected
1.Language shows Deutsch which is Incorrect- should be German** NOT FIXED Needs to DE.

![German incorrect Acronym ](https://user-images.githubusercontent.com/93543576/188251206-27622aee-71c0-4aab-b7a8-21c89610340f.jpeg)






The following is working as expected

Korean is not working as expected
1.Main settings page format off- too long -FIXED

Japanese is not working as expected
1.Japanese Main settings page format off- too long.  FIXED


Spanish is not working as expected:
1.Main settings page format off- too long. FIXED

Vietnamese is not working as expected
2.Main settings page format off- too long : FIXED

Please see Video:


https://user-images.githubusercontent.com/93543576/188251347-14fa4e86-77e6-4d16-8b24-2ea514232823.mov

**Comment by StefanB90** [comment]
quick fix change (DU) to (DE)

**Comment by kjawadDeveloper2** [comment]
@Tanyaml  check this in new build.

**Comment by Tanyaml** [comment]
I have validated that German is  working as expected
1.Language shows GERMAN shows be DE.

Please see screenshots:

Android:

![Android German Lang Validated ](https://user-images.githubusercontent.com/93543576/189148868-6e61c944-ff1b-4347-a863-c88e7790dd3b.png)







iOS:

![iOS German Lang Validated](https://user-images.githubusercontent.com/93543576/189148917-982cc0e4-3bdf-4eae-86c3-9cc9ae44f875.jpg)
