### ISSUE TITLE
 Big Dipper Link for NFT Mobile Purchase Not Working As Expected on Android & iOS Production Env.

### ISSUE THREAD

**Issue by Tanyaml** [Pylons-tech/pylons#877]
## Summary of Bug
The following errors occur when user clicks Link for NFT Mobile Purchase: Android Device in Production Environment 

1. Views is still not removed   
2. Image is stretched out and looks off
3. When user clicks on ownership the Tab view is scaled off- it is stretched out vertical outside the actual frame
4. When user clicks buy they are directed to Wallet- Collection Tab  and then is Directed to NFT where they can purchase NFT 
5. Loading time of NFT is longer than 20 seconds when User clicks on shared NFT is directed onto Big dipper

Please See screenshots and video:

https://user-images.githubusercontent.com/93543576/186556363-762776dd-d6d1-40d6-9f62-199fc284884a.mov

<img width="404" alt="Views still visalbe " src="https://user-images.githubusercontent.com/93543576/186556488-3ba65c26-0ac0-45eb-90e2-0173fd03187d.png">

<img width="448" alt="NFT Streched Out image" src="https://user-images.githubusercontent.com/93543576/186556559-c43937d1-52a7-4028-b84a-0a5ede7b8799.png">

<img width="448" alt="Ownership tab scaled off" src="https://user-images.githubusercontent.com/93543576/186556518-149d6190-c89a-4f0f-a63c-fc17deb17baf.png">

The following errors occur when user clicks Link for NFT Mobile Purchase: iOS Device in Production Environment 

1. Views is still not removed   
2. When User clicks on ownership tab Title Name Cut off  and when user scrolls down the white screen is seen
3. Image is stretched out
4. Loading time of NFT is longer than 20 seconds when User clicks on shared NFT is directed onto Big dipper

Please See screenshots and video:

https://user-images.githubusercontent.com/93543576/186563530-a85bcd0f-00ac-40fd-897c-e0ed91612682.mov

![Image Strenched  and view is off](https://user-images.githubusercontent.com/93543576/186563797-40a46e82-f5ac-4da4-b8e4-c669d44c4999.png)

<img width="423" alt="iOS NFT  white screen seen when scroling down" src="https://user-images.githubusercontent.com/93543576/186564788-d1a50ee9-11d8-44f0-8b7e-e3eec09683b5.png">

## Steps to Reproduce
1. User clicks shared NFT:  https://wallet.pylons.tech/?recipe_id=Easel_Recipe_auto_recipe_2022_08_24_170310_613&cookbook_id=Easel_CookBook_auto_cookbook_2022_08_24_170303_175&address=pylo1nn46gkt4f7ejppxc3m9c5w74nt5l68e6c0k2kan NFT 
2. User is directed to Big Dipper
4. User Is clicks on by button
6. User is Directed to Pylons Wallet ---> Pylons Loading Icon appears
7. User is then land on NFT to purchase in Pylons Wallet

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by abdullahjankhan1** [comment]
@Tanyaml @StefanB90 

Updated UI Screenshot. 
PR https://github.com/Pylons-tech/pylons/pull/882

![image](https://user-images.githubusercontent.com/101688102/186654679-e7940cab-39ce-4c4f-9d2e-d3bef5541318.png)
Will go up to a limit and then we will have our subsections as scrollable 

![image](https://user-images.githubusercontent.com/101688102/186654800-a0a97f2f-e5bb-412f-8766-a326d0326978.png)
Image stretch is also fixed now image is zoomed

![image](https://user-images.githubusercontent.com/101688102/186654912-12a486ab-f5bc-4ce2-8d77-b5bbcff43809.png)
![image](https://user-images.githubusercontent.com/101688102/186654957-dfcd3630-9c0e-4c63-8404-0cef985811f1.png)

Another sample:

![image](https://user-images.githubusercontent.com/101688102/186655266-8a4eb25c-3796-42e5-9357-9efd993bdd7e.png)
![image](https://user-images.githubusercontent.com/101688102/186655323-df1ca649-97dc-4e75-9065-d6a0d699152a.png)
