### ISSUE TITLE
Rename coin to points in IAP module for PYLN

### ISSUE THREAD

**Issue by StefanB90** [Pylons-tech/pylons#887]
## Summary of Bug

we must ensure we refer to PYLN as points not coins. In the in-app purchase pop-up, we refer to PYLN as coins. Please rename it to points.

## Steps to Reproduce

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by faizhashmiRnS** [comment]
**For IOS:** 
![image](https://user-images.githubusercontent.com/106378847/186833159-7eb25b36-aded-4e9e-b70b-71eb4042205f.png)


**For Android:**
![image](https://user-images.githubusercontent.com/106378847/186833253-7df76118-55d3-413c-87fa-fcd75edb4fa6.png)


@kjawadDeveloper2 , It shows coins on Android but points on IOS side. 
Can you please update the products description on AppStore account and replace the "coins" with "points" ?

**Comment by StefanB90** [comment]
@faizhashmiRnS @kjawadDeveloper2 please use PYLN in IAP for both Apple & Google instead of coins or points

**Comment by MikeSofaer** [comment]
Part of the reason to call them points is to make sure everyone understands that they are not a cryptocurrency.

**Comment by StefanB90** [comment]
per standup, wherever PYLN is mentioned, please put "points" instead

on Google IAP remove Pylons and just put "points"

on Apple IAP, rename coins "points"

on Pylons app, rename PYLN to "points"

**Comment by kjawadDeveloper2** [comment]
I changed  on android its done. On ios it will take some time to approve.

**Comment by heyitsjk** [comment]
Apple App Review has approved our change request to "Points" - now displays in-app on iOS

![IMG_E667FA5D3500-1](https://user-images.githubusercontent.com/74597290/187007850-eb385549-8ecd-4a50-817d-f7cd65f815a4.jpeg)

**Comment by kjawadDeveloper2** [comment]
@Tanyaml  kindly check this.

**Comment by StefanB90** [comment]
@Tanyaml please confirm that we can close this. Thank you.

**Comment by Tanyaml** [comment]
@StefanB90  I have validated  the following:

on Google IAP remove Pylons and just put "points"

on Apple IAP, rename coins "points"

on Pylons app, rename PYLN to "points"

Please See Video:
Android

https://user-images.githubusercontent.com/93543576/188255614-a99873ac-b8ea-4d84-9416-12e2af0cb7db.mov

Please See Video:
iOS

https://user-images.githubusercontent.com/93543576/188255736-3085c32d-9641-4934-bbaa-a4235f72cb8f.mov
