### ISSUE TITLE
When User Opens Pylons App after 10 mins or more- Network Error Message Pops Up

### ISSUE THREAD

**Issue by Tanyaml** [Pylons-tech/pylons#888]
## Summary of Bug
When User Opens Pylons App after 10 mins or more- Network Error Message Pops Up Note: I have Wifi and it is working properly.
Note: I was working on previous bug and exit the pylons and came back to retest after 10 mins and Pylons and Network Error message popped up, this occurs in Dev and Prod and on iOS and Android.

Please see video:

https://user-images.githubusercontent.com/93543576/186773351-6d737fc5-adf0-4229-ac27-dbf649654729.mov

## Steps to Reproduce
1. Go onto Pylons App and click on wallet and go back to collection
2. Exit Pylons, do not go back into App for at least 10 mins.
3. Go back on Pylons after 10 minutes or more and Network Error message pops up.

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by StefanB90** [comment]
@Tanyaml has confirmed that this error persists and still needs to be addressed.

**Comment by Tanyaml** [comment]
@faizhashmiRnS @faisalnaveedRNS whats the status on this? It has been over 1 week now.

**Comment by faizhashmiRnS** [comment]
@kjawadDeveloper2 , any update about the testing build for branch **fix/no_internet_popup_issue** ?

**Comment by kjawadDeveloper2** [comment]
@Tanyaml whats the current situation of this bug?

**Comment by Tanyaml** [comment]
I have validated: When User Opens Pylons App after 10 mins or more- Network Error Message Pops Up- it is now working as expected- The Network Error Message is now working as should Once user is off Wifi Message prompts and once user is back on Wifi User is able to press cancel and works as expected

https://user-images.githubusercontent.com/93543576/195394732-74063f51-e4cf-41a5-9263-bad6c9d69a49.mov

.

Please see video:
