### ISSUE TITLE
Big Dipper Video NFT Purchase Preview Not Working As Expected

### ISSUE THREAD

**Issue by Tanyaml** [Pylons-tech/pylons#891]
## Summary of Bug: 
**Note this is happening in both Production and Latest Version on  Pylons on Android & Web Browser 
Video NFT Preview Not Working As Expected
1. When User clicks on Link to purchase NFT- the image of the video is too small.  When User clicks on buy and is  directed to wallet Video NFT is working as expected and this is what should be displayed.
Please see video:

https://user-images.githubusercontent.com/93543576/186810994-06ac9a54-45ad-4055-8e39-a2e67d10dcea.mov

2. The Receipt has the wrong time-stamp of  02:08 UTC when I purchased NFT, the actual time was 11:04pm.
Please see screenshot:

![Time of Purcahse incorrect- video](https://user-images.githubusercontent.com/93543576/186811024-85feb463-f19e-42a7-8cc7-19c319f2eeb8.png)

3. When user clicks link on NFT Web Browser the Scaling of the video is not correct:
Please see Screenshot:

![Video Scaled Incorrect](https://user-images.githubusercontent.com/93543576/186818967-8dab3217-7088-4836-9686-7b0d7ccb7477.png)

## Steps to Reproduce
1. User clicks NFT to purchase:  https://wallet.pylons.tech/?recipe_id=Easel_Recipe_auto_recipe_2022_08_25_222758_109&cookbook_id=Easel_CookBook_auto_cookbook_2022_08_25_222753_679&address=pylo1gqp0uxm0xwnlyfn5ma8hvg846mzxc3swqaawqw
2. User is Directed to Big Dipper and lands on NFT 
3. User views video (which is not working as expected)
5. User clicks on buy and is directed to wallet and purchase NFT
6. User receives popup Receipt (which is where the wrong timestamp 02:08 UTC will be seen).  

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by StefanB90** [comment]
@Tanyaml to close this after final test to confirm working as expected.

**Comment by Tanyaml** [comment]
@faisalnaveedRNS When user is clicking on link for Video NFT and lands on BD  it shows Buy free button:

Please see video:

https://user-images.githubusercontent.com/93543576/188208959-244c420f-db26-4a4e-82c3-785b6bc27cb7.mov

<img width="443" alt="Screen Shot 2022-09-02 at 1 44 20 PM" src="https://user-images.githubusercontent.com/93543576/188209236-7af21e2d-6f5b-4d69-a121-045c55ea0cd3.png">


Big Dipper Web Browser  Video Is not Seen and Buy for Free Button:
Please see Screenshot:

![Screen Shot 2022-09-02 at 1 39 26 PM](https://user-images.githubusercontent.com/93543576/188209932-e5f4daba-efe9-438e-bf61-7d86b06e1e28.png)

**Comment by Tanyaml** [comment]
I have validated  BD on  Web Browser and it is working as expected.

![Screen Shot 2022-09-06 at 9 36 31 PM](https://user-images.githubusercontent.com/93543576/188769637-bdb5b6a6-1c9c-427e-a45b-eb97bd6ec6d7.png)
