### ISSUE TITLE
Big Dipper Audio NFT Purchase  Preview Not Working As Expected

### ISSUE THREAD

**Issue by Tanyaml** [Pylons-tech/pylons#892]
## Summary of Bug
**Note this is happening in both Production and Latest Version of Pylons on Android & Web Browser**
Audio NFT Preview Not Working As Expected
1. When User clicks on Link to purchase NFT-Audio NFT does not have image and the audio playback toggle is positioned to high, When User clicks on buy and is directed to wallet this is the actual Audio NFT is working as expected and this is what should be displayed.
Please see video:

https://user-images.githubusercontent.com/93543576/186812495-eebf560f-3b02-48fc-8d8f-80ac873e3f65.mov

3. The Receipt has the wrong time-stamp of  02:08 UTC when I purchased NFT, the actual time was 11:06 UTC.
Please see screenshot:

![Wrong Time Stamp -Audio](https://user-images.githubusercontent.com/93543576/186812551-457297de-0457-4957-b667-0ecc54cce640.png)

4.When user clicks link on Web Browser for NFT no Image of NFT is attached to Audio.
Please see Screenshot:

![Audio NFT Image not able to preview](https://user-images.githubusercontent.com/93543576/186820727-f35f0c09-f683-4503-9300-57f4cbcc7361.png)

## Steps to Reproduce
1. User clicks NFT to purchase: https://wallet.pylons.tech/?recipe_id=Easel_Recipe_auto_recipe_2022_08_25_223200_364&cookbook_id=Easel_CookBook_auto_cookbook_2022_08_25_222753_679&address=pylo1gqp0uxm0xwnlyfn5ma8hvg846mzxc3swqaawqw
2. User is Directed to Big Dipper and lands on Audio NFT
3. User views Audio (which is not working as expected)
4. User clicks on buy and is directed to wallet and purchase NFT
5.User receives popup Receipt (which is where the wrong timestamp  02:08 UTC will be seen).

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by StefanB90** [comment]
@Tanyaml to close this after final test to confirm working as expected.

**Comment by Tanyaml** [comment]
@faisalnaveedRNS  This issue is not resolved.

When user clicks on NFT :  https://wallet.pylons.tech/?recipe_id=Easel_Recipe_auto_recipe_2022_09_02_223054_116&cookbook_id=Easel_CookBook_auto_cookbook_2022_09_02_222030_186&address=pylo133mtmhludmn8z2ww6axkzayq92gkynmdf9j2c5
User will Land on Big Dipper  and the button " Buy For Free"   which is invalid. 

 
Please see Video:
Android

https://user-images.githubusercontent.com/93543576/188257666-d6e155fd-24e5-4978-85c0-bea055b1cd04.mov







Please see Video:
iOS

https://user-images.githubusercontent.com/93543576/188257946-ecb0a15f-8b38-4576-89aa-195db5bb037e.mov

















In iOS It is working as expected:
Uploading iOS#892 Validated .mov…

**Comment by Tanyaml** [comment]
@faisalnaveedRNS 

Please see screen shot: 
The Audio playback is not in the right position: 
See screenshot:
![invaild Audio NFT](https://user-images.githubusercontent.com/93543576/188769130-cfb1eb6a-0a81-42b1-b2da-ac16fb976bdc.png)

**Comment by StefanB90** [comment]
Every video seems to be horizontal.

@xbdyhh let's design a horizontal screen orientation for video playback on Big Dipper & Pylons App (in addition to Easel)

**Comment by StefanB90** [comment]
@Tanyaml can we test and close this issue?

**Comment by Tanyaml** [comment]
@StefanB90 this still needs to fixed.

**Comment by Tanyaml** [comment]
This is still not working as expected. 

Please see link - Audio playback is still outside of NFT.
https://wallet.pylons.tech/?recipe_id=Easel_Recipe_auto_recipe_2022_08_25_223200_364&cookbook_id=Easel_CookBook_auto_cookbook_2022_08_25_222753_679&address=pylo1gqp0uxm0xwnlyfn5ma8hvg846mzxc3swqaawqw
