### ISSUE TITLE
Big Dipper PDF NFT  Purchase Preview Not Working As Expected

### ISSUE THREAD

**Issue by Tanyaml** [Pylons-tech/pylons#893]
## Summary of Bug
PDF NFT  Purchase Preview Not Working As Expected
**Note this is happening in both Production and Latest Version of  Pylons on Android & Web Browser** 

1. When User clicks on Link to purchase NFT-PDF NFT does not have the actual PDF pages to view it only has the image uploaded for the PDF , When User clicks on buy and is directed to wallet this is the actual PDF pages are seen and  working as expected and this is what should be displayed.
Please see video:

https://user-images.githubusercontent.com/93543576/186813994-c1d0d282-1378-46ba-90f4-6b57837872e6.mov

2.The Receipt has the wrong time-stamp of 02:08 UTC when I purchased NFT, the actual time was 11:09pm.
Please see screenshot:

![Wrong Time Stamp- PDF](https://user-images.githubusercontent.com/93543576/186813968-3a2d20f1-fb27-4865-beab-9dc9381606d4.png)

3. When user clicks link on Web Browser for NFT there is no PDF files to view .
Please see Screenshot:

![PDF incorrect- no pages to view](https://user-images.githubusercontent.com/93543576/186819956-8a869abb-e3ee-484c-9809-596a3975ac81.png)

## Steps to Reproduce
1. User clicks NFT to purchase:  https://wallet.pylons.tech/?recipe_id=Easel_Recipe_auto_recipe_2022_08_25_223403_486&cookbook_id=Easel_CookBook_auto_cookbook_2022_08_25_222753_679&address=pylo1gqp0uxm0xwnlyfn5ma8hvg846mzxc3swqaawqw
2. User is Directed to Big Dipper and lands on PDF NFT
3. User views PDF  only image is seen (which is not working as expected)
4. User clicks on buy and is directed to wallet and purchase NFT
5. User receives popup Receipt (which is where the wrong timestamp 02:08 UTC will be seen).

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by StefanB90** [comment]
@Tanyaml to check that a user cannot read the entire PDF eBook. If that has been addressed in addition to the issues described above (with the exception of the timestamp discrepancy) can close this issue.

**Comment by Tanyaml** [comment]
I have validated the BD that PDF upload is working as expected on Web Browser- being that we are going to create the PDF is available only upon purchase.
