### ISSUE TITLE
Big Dipper 3DNFT Purchase  Preview Not Working As Expected

### ISSUE THREAD

**Issue by Tanyaml** [Pylons-tech/pylons#894]
## Summary of Bug
**Note this is happening in both Production and Latest Version Pylons on Android & Web Browser
3D NFT Preview Not Working As Expected

1.When User clicks on Link to purchase 3D NFT- the image of the 3D does not appear and the toggle icon is in the wrong position, when user then tries to preview 3D in 3D mode nothing is seen . When User clicks on buy and is directed to wallet 3D NFT is working as expected and this is what should be displayed.
Please see video:

https://user-images.githubusercontent.com/93543576/186821775-b7788eed-a699-4102-a18f-36170b2ee85b.mov

2.The Receipt has the wrong time-stamp of 04:08 UTC when I purchased NFT, the actual time was 11:15pm.
Please see screenshot:

![Wrong Timestamp - 3D](https://user-images.githubusercontent.com/93543576/186822027-a6d6d66b-3185-4577-8758-b87f45d4f96d.png)

3.When user clicks link on NFT Web Browser the color of NFT is incorrect it is black. 
Please see screenshot:
![3D Image not avaible for Preview](https://user-images.githubusercontent.com/93543576/186822191-d4086811-daf1-4c63-91e1-ca18cda08b6f.png)

## Steps to Reproduce
1. User clicks NFT to purchase:  https://wallet.pylons.tech/?recipe_id=Easel_Recipe_auto_recipe_2022_08_25_223006_711&cookbook_id=Easel_CookBook_auto_cookbook_2022_08_25_222753_679&address=pylo1gqp0uxm0xwnlyfn5ma8hvg846mzxc3swqaawqw
2. User is Directed to Big Dipper and lands on NFT
3. User views 3D  (which is not working as expected)
4. User clicks on buy and is directed to wallet and purchase NFT
5. User receives popup Receipt (which is where the wrong timestamp 04:08 UTC will be seen).

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by StefanB90** [comment]
@Tanyaml to retest then close.
