### ISSUE TITLE
When User is Main Settings-Email Box Missing Default Text 

### ISSUE THREAD

**Issue by Tanyaml** [Pylons-tech/pylons#898]
## Summary of Bug
Note: This is happening in Both iOS and Android.
When User is Main Settings- Email Default Text Invalid 

Main Settings Email Box Missing Default Text x@pylons.tech

Please See Video and Screenshot:

https://user-images.githubusercontent.com/93543576/186964234-78be0e7d-3d4d-44e1-b233-49ecc8a60c8d.mov

<img width="424" alt="Missing Email Default Text" src="https://user-images.githubusercontent.com/93543576/186965335-a2c69bda-1004-4131-9c25-8bd00d7d2451.png">

Please See Correct file:

![Email Default Text](https://user-images.githubusercontent.com/93543576/186964653-1f4f2df8-f2ef-4014-8a53-6f9376c3bdc2.png)

## Steps to Reproduce
1. User opens Pylons App
2. User clicks on menu settings to the top of collection tab in the left corner
3. User will land on Main Settings and this is where you will view the Email Box- it is missing the default text 

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by StefanB90** [comment]
@Tanyaml to verify then close when possible.

**Comment by Tanyaml** [comment]
This is working as expected.

**Comment by Tanyaml** [comment]
When User is Main Settings-Email Box is working as expected.
![email address validated](https://user-images.githubusercontent.com/93543576/188670788-55a7ccbe-92d8-4a80-8614-a385c487e55f.png)
