### ISSUE TITLE
Creating a NFT feed in the Pylons app using the Pylons API

### ISSUE THREAD

**Issue by StefanB90** [Pylons-tech/pylons#899]
## Summary

We need to create a NFT feed in the Pylons app that automatically takes all NFTs shared from Easel or the Pylons app and aggregates them into a scrollable NFT feed, which will allow other Pylons app users who did not receive the shared link to view a NFT and potentially purchase it if it's available for sale.

Essentially, we are creating a social media card for the Pylons app itself and displaying these preview thumbnails in sequential order based on the most recently shared NFT.

This Pylons app NFT feed could also be created from the Big Dipper Activity feed currently in use, but would broaden its scope to include NFTs that have been shared multiple times by other users who were originally send a shared link from someone else, whether that be another Pylons app user or the original artist/creator who minted the NFT in Easel.

In order to avoid having the most frequently shared NFT constantly show up in every Pylons app user's NFT feed, we will limit the number of times a single NFT can appear in everyone's NFT feed for a specific time interval (i.e. every 30 seconds of scrolling max). 

## Problem Definition

As a Pylons app user, I am unable to discover other NFTs created in Easel or transferred to the Pylons chain without receiving a direct link to that NFT from someone else. How can I discover other NFTs that aren't directly shared with me outside Big Dipper? How do I know which NFTs are most popular/ generating the most buzz?

## Proposal

Create a Pylons API that ingests all NFT-related activity from Easel, Evently, Big Dipper & the Pylons app.

Order this activity into a comprehensive NFT news feed that displays the NFT name, Artist name & thumbnail preview, effectively creating a social media card for the Pylons app itself.

Update this NFT news feed based on the most recent activity with regards to:

1. The most recently created &/or shared NFT in Easel or Evently
2. The most recently shared NFT in the Pylons app
3. The latest NFT to appear in the Big Dipper Activity feed

Create an API spec for other 3rd party app developers to leverage for future use cases involving a combination of any components of our tech stack (i.e. DevTool, SDK, etc.)

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by MikeSofaer** [comment]
This is not just a lot of work, it changes the nature of the service we are providing, and has regulatory as well as positioning implications. Let's set up a call with Josh to talk about how we want to approach discovery.
