### ISSUE TITLE
When User is In Pylons Wallet Tapping the Heart Icon Invalid Behavior 

### ISSUE THREAD

**Issue by Tanyaml** [Pylons-tech/pylons#901]
## Summary of Bug ##
Note: This behavior is iOS and Android Platform.
When User is Tapping the Heart Icon Invalid and different Behaviors for Image, PDF, Audio, 3D, Video NFTs.

NFT IMAGE: Tapping the Heart does NOT turn RED and JUMPS  onto 2 Likes.

PDF IMAGE: Tapping the Heart does turn RED  and JUMPS  onto 2 Likes.

Audio IMAGE: Tapping the Heart does NOT turn RED JUMPS  onto 3 Likes.

3D IMAGE: Tapping the Heart does NOT turn RED JUMPS onto 3 Likes.

Video IMAGE: Tapping the Heart does turn RED JUMPS onto 2 Likes.

Please see Video:

## Steps to Reproduce
1.User will open shared NFT link for purchase: https://wallet.pylons.tech/?recipe_id=Easel_Recipe_auto_recipe_2022_08_26_104852_666&cookbook_id=Easel_CookBook_auto_cookbook_2022_08_26_104843_867&address=pylo13msl7j4qm3734gyee6sqq932fgahh20hva880q

2. User will be directed to NFT Image 
3. User will click on the Heart Icon and will see the Heart does NOT turn RED and JUMPS  onto 2 Likes.
4. Repeat these steps 1-3 for the following for the remainder of NFTs to check

PDF NFT : https://wallet.pylons.tech/?recipe_id=Easel_Recipe_auto_recipe_2022_08_25_223403_486&cookbook_id=Easel_CookBook_auto_cookbook_2022_08_25_222753_679&address=pylo1gqp0uxm0xwnlyfn5ma8hvg846mzxc3swqaawqw 

Audio NFT: https://wallet.pylons.tech/?recipe_id=Easel_Recipe_auto_recipe_2022_08_25_223200_364&cookbook_id=Easel_CookBook_auto_cookbook_2022_08_25_222753_679&address=pylo1gqp0uxm0xwnlyfn5ma8hvg846mzxc3swqaawqw

3D NFT: https://wallet.pylons.tech/?recipe_id=Easel_Recipe_auto_recipe_2022_08_25_223006_711&cookbook_id=Easel_CookBook_auto_cookbook_2022_08_25_222753_679&address=pylo1gqp0uxm0xwnlyfn5ma8hvg846mzxc3swqaawqw

Video NFT: https://wallet.pylons.tech/?recipe_id=Easel_Recipe_auto_recipe_2022_08_25_222758_109&cookbook_id=Easel_CookBook_auto_cookbook_2022_08_25_222753_679&address=pylo1gqp0uxm0xwnlyfn5ma8hvg846mzxc3swqaawqw

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by faizhashmiRnS** [comment]
Hi @Tanyaml , Please close this issue if it is tested. Thanks

**Comment by StefanB90** [comment]
@Tanyaml to close after final video test.

**Comment by Tanyaml** [comment]
@faizhashmiRnS @faisalnaveedRNS @StefanB90 This is still NOT working as expected, last night the new NFT drop below  had 4 likes and now its at 0- please see screenshot:

Last night:
![4 likes NFT drop](https://user-images.githubusercontent.com/93543576/187900741-55d613cf-05a1-43c6-9c83-859c3bee4ef2.png)



This Morning: 
![o likes New NFT Drop](https://user-images.githubusercontent.com/93543576/187900760-29fba815-504a-484e-8f59-60c572b01a24.png)









[ ](https://wallet.pylons.tech/?recipe_id=Easel_Recipe_auto_recipe_2022_08_31_183729_838&cookbook_id=Easel_CookBook_auto_cookbook_2022_08_31_183723_014&address=pylo1w4r78vqfzalx4mlcd53xw808x22xpengh7xfjn)
