### ISSUE TITLE
Force localization at runtime

### ISSUE THREAD

**Issue by heyitsjk** [Pylons-tech/pylons#902]
## Feature Request Summary

Add the ability to read a users set device operating system language to then auto set the language in-app on first launch.

Example: Device OS language is set to Spanish. Installing the Pylons app and launching it will automatically show Spanish i18n on first open.

## Why do we need this?

Having this feature will help retain new users gained from marketing campaigns who might not know English while attempting to use the app.

## Proposal

Use Android & iOS SDKs to read a users set device language preference then match that language in-app on first open. 

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by StefanB90** [comment]
P2 - P3 --> requires research to understand what must be done.

**Comment by heyitsjk** [comment]
functionality is implemented. Was able to reproduce with Russian, Spanish, and other languages with a defined i18n file in Wallet 1.1.2 Android & Easel
