### ISSUE TITLE
Recipe Structure for Evently

### ISSUE THREAD

**Issue by faizhashmiRnS** [Pylons-tech/pylons#904]
This issue is related to the Recipe structure in Evently. Looking forward to have a continuous feedback from everyone on this.

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by StefanB90** [comment]
currently in progress.

P2 - must be completed by end of next week

**Comment by faizhashmiRnS** [comment]
@kjawadDeveloper2 
branch: temp/recipe_struct

Hi, I have tried to make it as close to the problem statement as I could. I am facing some deadlocks now and It still needs some improvements. Please review it.

**Comment by faisalnaveedRNS** [comment]
@kjawadDeveloper2 need discussion on this ticket
