### ISSUE TITLE
Mnemonic should be enough to recover an account

### ISSUE THREAD

**Issue by mustafapylons** [Pylons-tech/pylons#909]
## Summary of Bug
Mnemonic should be enough to recover an account. This is created due to customer issue in discord support channel.

## Steps to Reproduce

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by kjawadDeveloper** [comment]
@StefanB90  do we have a design for this?
@mustafapylons  where we are going to adjust this in our design?

**Comment by StefanB90** [comment]
do not need pylons username to recover your account. Only mnemonic is required.

**Comment by kjawadDeveloper2** [comment]
@Tanyaml  kindly also check this.

**Comment by StefanB90** [comment]
QA testing required to close this.

**Comment by Tanyaml** [comment]
I have validated both on Android & iOS that the Pylons username is no longer on account Recover , Only mnemonic is present.

Please see videos:

https://user-images.githubusercontent.com/93543576/187815968-7f5cf31f-2ab1-4a09-b63d-9fbb949062da.mov



https://user-images.githubusercontent.com/93543576/187816727-de36d696-27ba-49db-b701-2c708b9d2fbc.mov
