### ISSUE TITLE
Move Queries to Cosmosia.

### ISSUE THREAD

**Issue by mustafapylons** [Pylons-tech/pylons#915]
## Summary

Move Queries to Cosmosia.

## Proposal

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by StefanB90** [comment]
work has been started. P1 - to be completed this week

**Comment by StefanB90** [comment]
for gRPC --> discussion ongoing
