### ISSUE TITLE
Pylons: Receipt has the wrong time-stamp Same Time for Each Purchase UTC 22:08

### ISSUE THREAD

**Issue by Tanyaml** [Pylons-tech/pylons#917]
The Receipt has the wrong time-stamp of 02:08 UTC when I purchased NFT, the actual time was 6:23pm- this is happening on both iOS and Android.

Please see screenshot:
![Wrong Timestamp - 3D](https://user-images.githubusercontent.com/93543576/187309331-6701f537-ec55-40f8-a805-6c2f704ec4ce.png)

## Steps to Reproduce
1. User clicks NFT to purchase: https://wallet.pylons.tech/?recipe_id=Easel_Recipe_auto_recipe_2022_08_25_223006_711&cookbook_id=Easel_CookBook_auto_cookbook_2022_08_25_222753_679&address=pylo1gqp0uxm0xwnlyfn5ma8hvg846mzxc3swqaawqw
2. User is Directed to Big Dipper and lands on NFT
3. User views 3D (which is not working as expected)
4. User clicks on buy and is directed to wallet and purchase NFT
5. User receives popup Receipt (which is where the wrong timestamp 22:08 UTC will be seen).

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by faizhashmiRnS** [comment]
Hi @Tanyaml, The similar issue got fixed in PR #903 . Please let me know if you have an updated build. 
Further, Please make sure you are comparing it with the UTC time not local time.

Thanks!

**Comment by Tanyaml** [comment]
@faizhashmiRnS The issue was that not zone of time it was- the same time that is being displayed.

**Comment by kjawadDeveloper2** [comment]
@StefanB90  should we show local time of the user or UTC?

**Comment by StefanB90** [comment]
P3 - must be completed within 30 days

**Comment by kjawadDeveloper2** [comment]
@StefanB90  can you tell us should we show UTC time or user local time ?

**Comment by MikeSofaer** [comment]
User local time

**Comment by faizhashmiRnS** [comment]
As per my discussion with @abdullahjankhan1, This is implemented on devnet from backend team and would not be available on testnet for now. 
@faisalnaveedRNS please let me know the next proceedings for mobile team on this issue.

**Comment by faisalnaveedRNS** [comment]
need to test on dev net

**Comment by Tanyaml** [comment]
@faisalnaveedRNS  what is the status on this?

**Comment by faizhashmiRnS** [comment]
This is in progress. Currently we are unable to get the timestamp in the response payload after executing a recipe while being on the devnet.

**Comment by faisalnaveedRNS** [comment]
@faizhashmiRnS let me check on dev chain

**Comment by faizhashmiRnS** [comment]
Sure, please keep me posted.

**Comment by StefanB90** [comment]
TO BE COMPLETED BY 9/30

CC @MikeSofaer @mustafapylons @faisalnaveedRNS

**Comment by StefanB90** [comment]
conduct test once mainnet is launched

**Comment by abdullahjankhan1** [comment]
Issue is fixed in PR https://github.com/Pylons-tech/pylons/pull/1178

**Comment by faizhashmiRnS** [comment]
I have resolved it from the mobile end too in the PR #963.

**Comment by Tanyaml** [comment]
I have validated that the UTC is now working as Expected in Android and iOS.

Please see video:


Android:
https://user-images.githubusercontent.com/93543576/193853944-598aa082-fa90-4e58-9193-583b0f8003bb.mov

iOS:

https://user-images.githubusercontent.com/93543576/193854206-479bff57-0ca4-4ae4-87e2-ebb3db88d843.mov

**Comment by StefanB90** [comment]
@Tanyaml no need to test this until mainnet launch

**Comment by faisalnaveedRNS** [comment]
@ahmadrns Please test on dev chain

**Comment by ahmadrns** [comment]
@faisalnaveedRNS  Working as Expected

**Comment by faisalnaveedRNS** [comment]
@ahmadrns please move it to testing

**Comment by Tanyaml** [comment]
I just validated the UTC time and is working as expected.

Please see screenshot:
![UTC Validated](https://user-images.githubusercontent.com/93543576/196313779-281344ab-b0c5-40be-9fd4-df6b92be1a6f.png)
