### ISSUE TITLE
Validate JSON for gadgets at load time

### ISSUE THREAD

**Issue by afti-githobo** [Pylons-tech/pylons#918]
## Summary

We should validate the JSON for a gadget when we load it.

## Problem Definition

Currently, gadgets don't do any JSON validation until macro expansion happens. That sorta sucks, but a naive approach won't function because gadgets aren't actually valid JSON! They're arbitrary snippets that are assembled into a single JSON document, and may themselves contain placeholders that... are also arbitrary.

## Proposal

We need to be able to do a few things:

a) work out from looking at a gadget what its context is supposed to be so we can actually build a valid JSON document around it. This may be difficult w/o extensions to the gadget format, though we also... can't really strap a ton of metadata to gadget definitions without making gadgets significantly less usable. This needs looking into.

b) work out sane placeholder values for gadget arguments. This would... also have to be contextual, right now, because gadget arguments are untyped and numbered.

This seems like it's actually a pretty significant amount of work, whether we do it by reworking the format or by doing wacky things to intuit the appropriate context for gadgets, so it probably should not be considered for the immediate term.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by StefanB90** [comment]
high priority, but requires more clarification and discussion before we can proceed.

**Comment by afti-githobo** [comment]
i'm confused b/c i thought yesterday that our assessment about this (and the related case of identifying specific sources for JSON validation failures in recipes that contain multiple macros) was that they were _desirable_ things to have in the future, but that we couldn't justify the amount of time and energy that would need to be spent on engineering them right now?

cf. that discord threat I made yesterday where I was looking into the matter.

@MikeSofaer @mustafapylons 

like, which is it? is this a very high-priority thing, where the engineering problems need to be solved as soon as possible, or is it not worth the time investment it'd take at this point in time?

to be clear here: I genuinely have no idea how to build these features, and absent major changes to the gadget format it... seems like they will likely involve confronting novel engineering problems. if there's prior art I haven't found it.

**Comment by MikeSofaer** [comment]
Sorry, this one slipped past me. Validation is not high priority, we need to focus on first impression, which means features
