### ISSUE TITLE
Pylons-When User is trying to Purchase NFT- Invalid Behavior

### ISSUE THREAD

**Issue by Tanyaml** [Pylons-tech/pylons#923]
## Summary of Bug
Pylons-When User is trying to Purchase NFT- Invalid Behavior
When User is in Android Device- it goes directly to Big Dipper Block Page.

https://user-images.githubusercontent.com/93543576/187461813-12de182f-e2ca-4ccb-8e6e-0ffd0557aaaf.mov

When user is in iOS, it goes to Pylons for a split second it show purchase screen but then goes into Collection tab and Pylons Icon Keeps loading .

Uploading ios Error .mov…

## Version
Latest Version

## Steps to Reproduce
Android:
1.User clicks on shared NFT:[
](https://wallet.pylons.tech/?cookbook_id=Easel_CookBook_auto_cookbook_2022_08_29_133300_933&item_id=QGETYcR5rFq&address=pylo1cldgze0pqgysfvm7m5xrpdu3j5u6mpkdzq8ss5)
2. User lands on Big Dipper Blocks

iOS
1.User Clicks on shared NFT:[
](https://wallet.pylons.tech/?recipe_id=Easel_Recipe_auto_recipe_2022_08_29_165252_872&cookbook_id=Easel_CookBook_auto_cookbook_2022_08_29_165245_674&address=pylo1t456cn4xrh3k09j77kpg9490c4ufurffu6k5jz
2.User lands on wallet and is directed to purchase NFT for a spilt second and goes back to collection tab and Pylons Icon keeps loading.   
 

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by kjawadDeveloper2** [comment]
Point two i resolved.

**Comment by faisalnaveedRNS** [comment]
https://wallet.pylons.tech/?cookbook_id=Easel_CookBook_auto_cookbook_2022_08_29_133300_933&item_id=QGETYcR5rFq&address=pylo1cldgze0pqgysfvm7m5xrpdu3j5u6mpkdzq8ss5

**Comment by StefanB90** [comment]
P1 - to be completed this week

**Comment by faisalnaveedRNS** [comment]
PR is created, need to merge, then we can test

**Comment by faisalnaveedRNS** [comment]
@faizhashmiRnS Please confirm your status on this

**Comment by faizhashmiRnS** [comment]
> @faizhashmiRnS Please confirm your status on this

Yes, Development is completed. Just need to be merged and tested.
