### ISSUE TITLE
Lock aspect ratio vs fit to screen

### ISSUE THREAD

**Issue by StefanB90** [Pylons-tech/pylons#925]
## Summary of Bug

The crop/zoom functionality in Easel is unpredictable. Ensure it is working as expected --> the NFT should look exactly as I set it when I edit it using the crop/zoom tool.

To address the snap zoom issue, we must add a checkbox/button to enable/disable snap zoom so that the image you see in the crop screen before you hit "Done" is the same you see on the next screen as the NFT Preview

This snap zoom checkbox/button should automatically display the image with or without snap zoom, so that if I enabled it, then the NFT Preview on the next screen will be exactly what I saw when I was on the crop image screen before hitting "Done"

When I disable snap zoom on the crop image screen I should again see what I saw on the previous screen on the NFT Preview screen after I click "Done"

The checkbox would be "fill screen" or "maintain aspect ratio"?

--> Yes, fit to screen vs lock aspect ratio

## Steps to Reproduce

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by kjawadDeveloper2** [comment]
@StefanB90  can you give more info on this?

**Comment by StefanB90** [comment]
so when I edit an image that I wish to upload to IPFS to create a Draft NFT. When I'm done editing it (by that I mean, when I'm done adjusting it and click upload) the full screen NFT preview should look exactly the same as what I saw before I clicked upload. The NFT should always remain constant in terms of size/orientation/dimensions/resolution across any device as I set it when I uploaded it to IPFS. I should never wonder what the NFT will look like when I finally publish it. I should know that it will look exactly the same as when I uploaded it.

**Comment by StefanB90** [comment]
@kjawadDeveloper2 please see the following discord discussion with Easel creator pasted below for ease of reference:


**The image is 1:1 currently, but it's 3000x3000 so there is scope to crop to 9:16 if that's the accepted format?**

_That's what I would do, to reduce variables_

**When I added the image the crop tool was 1:1, so it works. Once you click ok, you see the image scaled up so it's confusing.**

_Yeah, I think we have this snap zoom where it fills the vertical space and cuts the sides off_

**Comment by StefanB90** [comment]
@kjawadDeveloper2 to address this issue asap, please offer "Lock aspect ratio" toggle in the crop/edit screen in Easel. Thank you!

**Comment by MikeSofaer** [comment]
This should also set a flag on the recipe, as it should only affect how it is viewed in the app, not how it uploads.

**Comment by StefanB90** [comment]
P1 - to be completed this week.

**Comment by StefanB90** [comment]
@kjawadDeveloper2 
![Screen Shot 2022-09-06 at 3 27 12 PM](https://user-images.githubusercontent.com/97635071/188721951-c53f3e7b-6ddc-4d96-b705-5a2f991384ce.png)

**Comment by StefanB90** [comment]
^ You can remove the rotate counterclockwise icon from the bottom menu to make space for the Lock image checkbox.
Locking the image locks the aspect ration that the user can select from the list or by manually editing using the box provided. I've removed square from the aspect ratio options provided and inserted Fit to Screen in its place. Thank you.

CC @xbdyhh @MikeSofaer @mustafapylons @Tanyaml @heyitsjk

**Comment by faizhashmiRnS** [comment]
Hi @kjawadDeveloper2, should we start working on these design if they are approved?

**Comment by kjawadDeveloper2** [comment]
Hi @StefanB90  can we schedule a meeting with you , me and @StefanB90 .

**Comment by Tanyaml** [comment]
@kjawadDeveloper2 what is the status on this?
