### ISSUE TITLE
Easel App: Pylons Text in for Denoms is invalid 

### ISSUE THREAD

**Issue by Tanyaml** [Pylons-tech/pylons#926]
## Summary of Bug
Pylons Text in for Denoms is invalid - The text is close to end of the text box.
Please see Screenshot:
![Pylons Text for Denom ](https://user-images.githubusercontent.com/93543576/187471802-fb4071bd-e928-4798-9894-3d6a8296f041.png)

## Steps to Reproduce
1. User logs on Easel and goes through with uploading NFT.
2. User lands on NFT pricing and will click on DENOMS Box and will see Pylons text invaild.

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by kjawadDeveloper2** [comment]
@Tanyaml 
https://we.tl/t-egVPcm1dGP
Kindly check with this build.

**Comment by Tanyaml** [comment]
I have tested the  Pylons Text in for Denoms and it is now Valid.
Please see video:

Uploading #926 Easel Resolved.mov…




<img width="444" alt="Pylons Text Vaild" src="https://user-images.githubusercontent.com/93543576/187485400-50c5ac37-ebbb-42d0-9aa9-ef8c1df7db2b.png">
