### ISSUE TITLE
Retry functionality in wallet 

### ISSUE THREAD

**Issue by kjawadDeveloper2** [Pylons-tech/pylons#950]
User should be able to retry the transactions if they didn't went through.

**Comment by StefanB90** [comment]
P1 must be completed this week

**Comment by faizhashmiRnS** [comment]
Hi @StefanB90, This issue might take sometime to complete. As discussed with @kjawadDeveloper2, There will be a screen having all the failures at one place and each failure will have a retry button. We will also need the design for that. 
Further, we have so many transactions that can be failed and user should be able to retry them. It may take sometime to implement this failure mechanism throughout the wallet app.

**Comment by MikeSofaer** [comment]
Let's deliver this in parts, then. The first piece should be a list of failed transactions, where if the transaction was an IAP mint or Stripe purchase, the user can see the details of the purchase they made.

**Comment by StefanB90** [comment]
@kjawadDeveloper2 
![Screen Shot 2022-09-06 at 5 26 38 PM](https://user-images.githubusercontent.com/97635071/188742798-bc054198-7eee-423c-96ba-f4c8b4048aca.png)

**Comment by StefanB90** [comment]
I've moved the stripe & Transaction History Overview icons on the same line with the Collection & Wallet tabs... you first get the error popup notification and if you close that by mistake the transaction that hasn't been processed on-chain is highlighted in red and the refresh icon is now added at the end next to the Transaction History Overview icon. The pylon points symbol has also changed to a refresh icon and if you click the arrow corresponding to the Purchased Pylon tx (note: should be "Purchased pylon points") then you will get to the Transaction Detail with the same note and retry button.

CC @xbdyhh @MikeSofaer @mustafapylons @Tanyaml

**Comment by StefanB90** [comment]
@kjawadDeveloper2 as discussed during standup. Final design ready for dev takes the user immediately to the Transaction Overview page after an IAP transaction receipt is obtained, but the chain fails to finalize the transaction on our end

![Screen Shot 2022-09-07 at 6 09 34 PM](https://user-images.githubusercontent.com/97635071/188992472-3640f00d-974a-4230-ba24-bba28bfe36e8.png)

**Comment by kjawadDeveloper2** [comment]
Why we need buyer here?

**Comment by kjawadDeveloper2** [comment]
In case of failure TxId is not created . Thats why we cannot save it.

**Comment by kjawadDeveloper2** [comment]
@StefanB90 you are mixing transaction history from the backend and from the local device. When ever a transaction fails its recorded in the local system not in the remote. So can we have only one set of transactions history. Or how we can accomodate transaction history from both the sources?

**Comment by StefanB90** [comment]
> Why we need buyer here?

you're right we don't need buyer please remove it thank you for pointing that out.

**Comment by faizhashmiRnS** [comment]
https://user-images.githubusercontent.com/106378847/190351547-95312ede-cf1d-4fc6-834d-4a5f2d913278.mp4

Hi @kjawadDeveloper2 , Please find out the attached demo for Retry Functionality in pylons app.

**Comment by mustafapylons** [comment]
According to @kjawadDeveloper2, this still has to be tested and @Tanyaml has to sign off for mobile release.

**Comment by Tanyaml** [comment]
I have validated the Pylons Retry Functionality and is working as expected only for Pylons Points Purchasing.

Note when I was trying to purchase NFT and turning wifi off it was not working as expected- I will be creating a bug for this issue.

Please see video: 

https://user-images.githubusercontent.com/93543576/193121411-5b6a5c7d-eeba-446b-bbd2-6943bb6b8839.mov
