### ISSUE TITLE
Pylons Views is Not Working as Expected

### ISSUE THREAD

**Issue by Tanyaml** [Pylons-tech/pylons#954]
## Summary of Bug
Pylons Views is Not Working as Expected,  when user likes NFT the night before the next day it goes down to 0- This is not working as should- also as I was testing I viewed this NFT more than 8 times with the different devices and I created different accounts- so that is also a major issue.

Please see screenshot:

Views Last night which was 8- 
![View night Before](https://user-images.githubusercontent.com/93543576/187901738-74dc2c4f-91a8-4808-91e8-1a30199b5ac7.png)

Views This morning:
![Views next day](https://user-images.githubusercontent.com/93543576/187902014-3e1f0410-b6ff-43bd-8df6-b0fd5f8cf770.png)

## Steps to Reproduce
1. The first day Open Pylons click on NFT to Purchase:  https://wallet.pylons.tech/?recipe_id=Easel_Recipe_auto_recipe_2022_08_31_183729_838&cookbook_id=Easel_CookBook_auto_cookbook_2022_08_31_183723_014&address=pylo1w4r78vqfzalx4mlcd53xw808x22xpengh7xfjn
2. Look at how many views, then Purchase 
3. Next day Open Pylons and look at your Purchased NFT and check views.
4. 

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by faisalnaveedRNS** [comment]
I think App was connected with wrong Big dipper URL updated, please check again

**Comment by kjawadDeveloper2** [comment]
@faisalnaveedRNS do we need to send new build to @Tanyaml  or it will be resolved automatically.

**Comment by StefanB90** [comment]
Per Mike --> API is not stable. Please check the stability of the API to test the accuracy of view counts. We should be counting views based on how many different people are looking at all the editions within the total number of editions offered. Edition 5 of 750 should not have more views than edition 8 of 750 as a quick sanity check.

**Comment by faisalnaveedRNS** [comment]
replace with better deployment API, to increase speed

**Comment by Tanyaml** [comment]
@Faisal Naveed | RNS Solutions#7222  I mentioned this before when user steps away from app more then 10mins and opens app the view count does not change at all- if user then kills app you will see the change with in 2 seconds.

please see video:


https://user-images.githubusercontent.com/93543576/188196655-1f2ede74-1a77-497a-80f3-60cc8a64fb06.mov

**Comment by faisal** [comment]
🤦

**Comment by faisal** [comment]
@faisalnaveedRNS I believe this one's for you.

**Comment by Tanyaml** [comment]
I have validated Pylons Views it is working as expected.

Please see video:

Android:

https://user-images.githubusercontent.com/93543576/188758454-d8c935dc-057e-4b20-ab42-0e2537bd3705.mov




iOS:



https://user-images.githubusercontent.com/93543576/188758470-9754f090-9480-4d5a-8bf6-85c1725278f1.mov
