### ISSUE TITLE
When User Creates account or Restores and lands on Pylons "Something Went Wrong "Message Pops up 

### ISSUE THREAD

**Issue by Tanyaml** [Pylons-tech/pylons#955]
## Summary of Bug
1.When User creates or restores account  on Android and lands on Pylons "Something Went Wrong" Message Pops up, this happens when you also kill app or leave app- the "Something went Wrong" message appears on the bottom.

Please see video:
Android:

https://user-images.githubusercontent.com/93543576/187903446-729dc201-7f89-409d-addf-92543b9cc260.mov

2.When User creates or restores account  on iOS and lands on Pylons "Something Went Wrong Restart your Application " Message Pops up, this happens when you also kill app or leave app- the "Something went Wrong" message appears on the bottom.

Please see screen shot:

![iOS Something went wrong ](https://user-images.githubusercontent.com/93543576/187905771-c0a110e5-cd02-4420-82f1-5cd4283b474b.jpg)

## Steps to Reproduce
1. User will Create Account or Restores
2. User then will be direct to Pylon home screen
3. User will then see "something went wrong" on the bottom of the page

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by faisalnaveedRNS** [comment]
I think App was connected with wrong Big dipper URL updated, please check again

**Comment by Tanyaml** [comment]
I have validated When User Creates account or Restores and lands on Pylons with no issue and now is working as expected.

Please see videos:

Android:

https://user-images.githubusercontent.com/93543576/188757236-f5082e19-afc8-4cb7-90a2-dfa723e50899.mov






iOS: 


https://user-images.githubusercontent.com/93543576/188757263-af6d0b57-adf6-4369-837f-af96b486e3e4.mov
