### ISSUE TITLE
ADD/REPAIR: Google Analytics for Firebase Tracking

### ISSUE THREAD

**Issue by heyitsjk** [Pylons-tech/pylons#962]
## Summary

Right now, there is no analytic data of users activity coming through Firebase Analytics. We need to add or repair the Analytics SDK so we can start seeing incoming user traffic to Big Dipper & the main Pylons app. 

We need to be able to see: Realtime Data, Events, Tags, & Conversions 

The projects & ID’s already live within our Firebase Console, which makes me think we had these at some point and they just broke along the way. Just need to make sure the Firebase Analytic SDK system is properly set for each one of these: 

tech.pylons.wallet (android) 

xyz.pylons.wallet (iOS)

PylonsBigdipper (web)

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by kjawadDeveloper2** [comment]
@heyitsjk i can add for android and ios . @faisalnaveedRNS  kindly look into big dipper one.

**Comment by StefanB90** [comment]
not required for Easel at this time.

**Comment by heyitsjk** [comment]
pylons/big-dipper/imports/ui/easel_buy/EaselBuy.jsx
Line 241 : “handleLoginConfirmed”

Add the ability to save the users inbound tags on Big Dipper and send to the new outbound Dynamic Link to the app so we can still see which ad they came from post-install.

“utm_source”
“utm_medium”
“utm_campaign”
“utm_id”
“utm_content”

**Comment by heyitsjk** [comment]
Analytics are shipping in version 1.1.2 of main Pylons app (09.13.2022)
