### ISSUE TITLE
Add analytic in whole checkout process

### ISSUE THREAD

**Issue by kjawadDeveloper2** [Pylons-tech/pylons#969]
Right now we only have analytics for the whole app. But our core feature purchase of NFT doesnt have analytics in the whole flow.

**Comment by StefanB90** [comment]
@kjawadDeveloper2 please let us know when you add those tags to the purchase flow. Thank you.

**Comment by heyitsjk** [comment]
still working on this - need @kjawadDeveloper2 to assist
