### ISSUE TITLE
Add Campaign Tags to Big Dipper's 'Buy Button' Dynamic Link

### ISSUE THREAD

**Issue by heyitsjk** [Pylons-tech/pylons#972]
## Summary

pylons/big-dipper/imports/ui/easel_buy/EaselBuy.jsx

Lines 692 & 1045: div className="buy-btn"

Line 241 : “handleLoginConfirmed”

Add the ability to save the users inbound tags and send to the new outbound Dynamic Link to the app so we can still see which ad they came from post-install.

“utm_source”
“utm_medium”
“utm_campaign”
“utm_id”
“utm_content”

Test: 
The flow from an Ad link, to Big Dipper, install the app, load the right art on first-open, purchase.
 -- See the data load on Firebase Console.
The flow from an Ad link, into the proper purchase page in-app, purchase.
 -- See the data load on Firebase Console.

Example of a newly formatted link to Andy’s drop: 
https://wallet.pylons.tech/?recipe_id=Easel_Recipe_auto_recipe_2022_08_31_183729_838&cookbook_id=Easel_CookBook_auto_cookbook_2022_08_31_183723_014&address=pylo1w4r78vqfzalx4mlcd53xw808x22xpengh7xfjn&utm_source=facebook&utm_medium=cpc&utm_campaign=an-x02-abfull&utm_id=6311910811819&utm_content=X01A 
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by StefanB90** [comment]
@heyitsjk do you mind checking if we can close this request? Thank you.

**Comment by heyitsjk** [comment]
still working on this - need @kjawadDeveloper2 to assist

**Comment by heyitsjk** [comment]
any update on this? @kjawadDeveloper2
