### ISSUE TITLE
Bring up a prompt in receipt page for rating the app such as "do you like us, rate us".

### ISSUE THREAD

**Issue by mustafapylons** [Pylons-tech/pylons#984]
## Summary
Bring up a prompt in receipt page for rating the app such as "do you like us, rate us".

## Proposal

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by mustafapylons** [comment]
@heyitsjk This is the draft feature request for rate us the app feature. Please work with @StefanB90 and Xinya to get the UX fleshed out.

**Comment by heyitsjk** [comment]
Flow:
after a users first transaction, show a "Are you enjoying Pylons?" popup
two options: yes or no
- tapping "yes" will show OS native prompt to review us on the app store
- tapping "no" will show our "submit feedback" form
