### ISSUE TITLE
iOS- When User is in iOS Purchasing NFT Invalid Behavior Occurs

### ISSUE THREAD

**Issue by Tanyaml** [Pylons-tech/pylons#985]
## Summary of Bug
iOS- When User is in iOS Purchasing NFT Invalid Behavior Occurs
User clicks on link to purchase NFT- User is Directed to Open Link URL then goes to Pylons and lands in the collection tab which then the Pylons Icon keeps loading.

Please see Video:

https://user-images.githubusercontent.com/93543576/188746638-989b12c6-f6ba-42e0-a5f6-d89eb70eca16.mov

## Version 1.1.2
iphone 11

## Steps to Reproduce
1. Click on shared NFT link: https://pylons.page.link/LCyriLVjRFyqqhZi6
2. User will be directed to NFT->and then the Screen Open link pops up.
3. And user clicks open link and directed to collection tab and Pylons Icon Loads.

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by StefanB90** [comment]
two separate issues:

1. disable "Open link in app" intermediary page that prompts user to click ok every time they click on a shared link
2. long loading time --> identify if issue is from chain or mobile side.

**Comment by Tanyaml** [comment]
@faisalnaveedRNS @kjawadDeveloper2  The purchase flow has changed again. User clicks on shared link and is directed to BD and goes to Pylons app for Purchase. This is happening in both iOS and Android.

Please see video:

https://user-images.githubusercontent.com/93543576/189364476-f6654df5-f902-4e7c-8941-e5fd22c530c4.mov

**Comment by kjawadDeveloper2** [comment]
So we tried the changes but nothing can satisfy all the needs.

**Comment by Tanyaml** [comment]
@mustafapylons @StefanB90 Thoughts?

**Comment by StefanB90** [comment]
please address other critical issues first that would otherwise prevent us from launching mainnet next week. At that point, we can address this

**Comment by kjawadDeveloper2** [comment]
@Tanyaml  can you confirm why its open?

**Comment by kjawadDeveloper2** [comment]
@Kamran-Khan-Gene  did you checked this.

**Comment by Kamran-Khan-Gene** [comment]
> @Kamran-Khan-Gene did you checked this.

No, I did not have MacBook, just purchased it.. I will check this today.

**Comment by ahmadrns** [comment]
@kjawadDeveloper2  Checked working fine as expected, on iOS when user click on NFT link it first go to Big Dipper then redirect to application.
