### ISSUE TITLE
Remove Version Number from Big Dipper Header

### ISSUE THREAD

**Issue by heyitsjk** [Pylons-tech/pylons#987]
## Summary of Bug

Remove the version number displaying in the header of Big Dipper -- UX Cleanup

_pylons/big-dipper/imports/ui/components/Header.jsx_ 
Line 213:          <Badge color='secondary'>{this.state.version}</Badge>{' '}

![Screen Shot 2022-09-06 at 4 33 57 PM](https://user-images.githubusercontent.com/74597290/188758048-46f873c7-23f5-496a-98c2-2944fecd4681.png)
____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by faisalnaveedRNS** [comment]
@StefanB90 Please close this ticket

**Comment by heyitsjk** [comment]
deployed & fixed
