### ISSUE TITLE
Gestures

### ISSUE THREAD

**Issue by StefanB90** [Pylons-tech/pylons#988]
## Summary

![Screen Shot 2022-09-06 at 7 45 16 PM](https://user-images.githubusercontent.com/97635071/188758968-c28c1554-7053-451f-885d-d14a8ee8cf4f.png)

## Proposal

Adding gestures to the full-screen NFT view to make it easier for users to remove all icons/text to see the NFT as the artist intended it to be seen and minimize the popup overlay box, as well as cycle to the next NFT in their collection.
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by ahmadrns** [comment]
Hi @StefanB90, 
In the 3D model & Pdf case, the user interacts with the asset, can play around with the 3D model, and can also change the pages of the pdf file on the swipe. 
For example in PDF, a right swipe can also mean the next PDF page or the next NFT collection.
So how the gestures will respond in these cases?

**Comment by faizhashmiRnS** [comment]
Hi @Tanyaml , Please test this when you are able to. Thanks.

**Comment by ahmadrns** [comment]
@kamranRNS @faisalnaveedRNS  This issue is resolved and merged and it is still open is there anything else that we have to do regarding gestures?
