### ISSUE TITLE
iOS Recovery Phrase Invalid

### ISSUE THREAD

**Issue by Tanyaml** [Pylons-tech/pylons#989]
## Summary of Bug
iOS Recovery Phrase Invalid
When user is trying to reveal recovery phrase- no phrase is available, and of user clicks on Test Practice- no phrase is avaiable  to test.
Note this is only happening in iOS.

Please see video:

https://user-images.githubusercontent.com/93543576/188760430-0dc6dc4c-58e5-459e-9336-190bd1e99bcf.mov

## Version 1.1.2
iPhone 11

## Steps to Reproduce
1. User will open Pylons App
2. User will then go to main menu settings
3. User will click on Recovery and click on View Recovery Phrase and will see no Phrase available 
4. User will click on Practice Test and no recovery phrase is available

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by StefanB90** [comment]
@Tanyaml confirmed that the recovery phrase is copied just not being displayed when you enable biometric ID

**Comment by MikeSofaer** [comment]
The phone clipboard is not secure, we should not be copying the phrase at any time.

**Comment by kjawadDeveloper2** [comment]
So i was not able to produce this issue. @Tanyaml  kindly test with new build.

**Comment by Tanyaml** [comment]
where is the new Build? @kjawadDeveloper2

**Comment by kjawadDeveloper2** [comment]
@Tanyaml  in next 2 hours.

**Comment by Tanyaml** [comment]
I have Validated the  iOS Recovery Phrase and it is working as expected.

Please see video:

https://user-images.githubusercontent.com/93543576/189152911-18071112-3bb1-4ca2-a94a-404ade3aef79.mov
