### ISSUE TITLE
Prepare for mainnet

### ISSUE THREAD

**Issue by nghuyenthevinh2000** [Pylons-tech/pylons#996]
## Summary

This post introduces check list of issues that must be addressed before mainnet launch

## Proposal

- [x] https://github.com/Pylons-tech/pylons/issues/997
- [x] https://github.com/Pylons-tech/pylons/issues/1056
- [x] https://github.com/Pylons-tech/pylons/issues/998
- [x] https://github.com/Pylons-tech/pylons/issues/1129
- [x] https://github.com/Pylons-tech/pylons/issues/1082
- [x] https://github.com/Pylons-tech/pylons/pull/808
- [x] https://github.com/Pylons-tech/pylons/issues/1169
- [x] https://github.com/Pylons-tech/pylons/issues/1214
- [x] https://github.com/Pylons-tech/pylons/issues/1052

____

#### For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels applied
- [x] Appropriate contributors tagged
- [x] Contributor assigned/self-assigned

**Comment by nghuyenthevinh2000** [comment]
monday: training multisig tool.

**Comment by nghuyenthevinh2000** [comment]
https://github.com/Pylons-tech/pylons/pull/1029

https://github.com/Pylons-tech/pylons/pull/1018

https://github.com/Pylons-tech/pylons/pull/1019

**Comment by StefanB90** [comment]
set all stripe USD to 0

Bedrock token

**Comment by StefanB90** [comment]
@MikeSofaer @mustafapylons @faddat final go/no-go meeting next Wednesday, September 21st

**Comment by StefanB90** [comment]
sell issue is mainnet critical.

**Comment by nghuyenthevinh2000** [comment]
Strategic planning: 

- need to identify which keeper logic functions that can lose user money.
- after identification, testing will be done.

**Comment by nghuyenthevinh2000** [comment]
multi - signature (threshold: 2 of 4) (no more subset)
