### ISSUE TITLE
feat(mainnet): redistribute ubedrock and stripe usd

### ISSUE THREAD

**Issue by nghuyenthevinh2000** [Pylons-tech/pylons#997]
## Summary

ubedrock is scattered around in many addresses. In preparation of mainnet, bedrock should only exist in 8 specified wallet with specified amount. 8 wallets constitute a total of 1 bils

Also 1 bedrock to each validator. Which one in 8 address will send bedrock to validator? @MikeSofaer 

@GNaD13 is assigned on this.

@MikeSofaer can I share the excel file to here?

- [ ] get address
- [ ] working tested code
- [ ] integration code to upgrade handler 

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by GNaD13** [comment]
Hi @MikeSofaer, about 8 specified wallets for "ubedrock". Do they have vesting time or all the token will release immediately after the Upgrade process? If they have vesting time, please give me those information.

**Comment by MikeSofaer** [comment]
No vesting time for any of the initial wallets. The key element is that those wallets are permitted to send Bedrock, but no other wallet is permitted to send any Bedrock it receives.

**Comment by nghuyenthevinh2000** [comment]
yep, I have a solution design for that bedrock transfer restriction: https://github.com/Pylons-tech/pylons/issues/998

**Comment by nghuyenthevinh2000** [comment]
@MikeSofaer

Hi, so 1 bedrock will be distributed to each validator. I assume that I will use Engineer Hot Wallet to distribute 1 bedrock to each validator?

**Comment by MikeSofaer** [comment]
Yes, you can use the engineering hot wallet to do this, or it can be done in the upgrade handler (otherwise the chain might not be able to start after the upgrade)
