### ISSUE TITLE
feat: ante decorator for restricting ubedrock transaction allowed address only

### ISSUE THREAD

**Issue by nghuyenthevinh2000** [Pylons-tech/pylons#998]
## Summary

bedrock is a security asset which should only be transfered among allowed address.

## Proposal

The design for this would need:
1. Ante decorator logic to check tx. It will check against allowed address stored in x/pylons
2. RegisterKYCAddress msg in x/pylons to register allowed address

- Need an address as the book keeper in server side (seed phrase has to be kept a secret else attacker can register rogue address) to do this task.

![kyc_register drawio](https://user-images.githubusercontent.com/23058164/191001833-7dc4439a-2f43-452f-8338-19e7676e635f.png)

@levanhieuhust will be doing this

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by vuong177** [comment]
I think only need set this Denom to 'non-transferable'

**Comment by nghuyenthevinh2000** [comment]
https://github.com/Pylons-tech/pylons/compare/nhan/upgrade-handler?fbclid=IwAR2Pyn1DR5xvXqSyX1b9uDpwYqNEk-XI2EWTyj34ky7diSbJOr_2FyZgDh4

https://github.com/levanhieuhust/pylons/commit/ec4256b5949458c50ba01b9480b66a487eb97086?fbclid=IwAR3-kPdKqPg0wzPCJGuSQF5vcF5mEOFotC4dA1NKTUARd0w1SQ0rfulYDpQ

**Comment by jlkershner** [comment]
I wrote a lengthy comment about how the whitelisting process for wallets should work: https://github.com/Pylons-tech/pylons/issues/1044#issuecomment-1245980181

Take a look at that as it is the basic structure needed here.  Whitelisting should be extensible so that we can use that feature to grant a range of permissions to a given wallet with the four such permissions to start with:
(1) Cashing out Pylons points;
(2) Holding security tokens (i.e. either an accredited investor or otherwise entitled to hold security tokens) (this is a flag showing regulatory compliance);
(3) Can receive Bedrock (this would be a superset of #2 because some internal company wallets and validators would have permission to receive bedrock even if they are not otherwise eligible to hold security tokens)
(4) Can send Bedrock (this is permission to send Bedrock to others).

We might also want to add a fifth permission just for validators.  The whitelisting system needs a way to remove permission as well as grant it, and ideally would be extensible to allow Pylons to add new permission categories as needed in the future.

**Comment by nghuyenthevinh2000** [comment]
currently, here is how we would add KYC address structure to x/pylons
{
  userName: string
  address: string
}

**Comment by MikeSofaer** [comment]
Needs at least three more fields I think.

level: integer
provider: string
provider_id: string

**Comment by levanhieuhust** [comment]
> Needs at least three more fields I think.
> 
> level: integer provider: string provider_id: string

Could you please explain why we need these fields?

**Comment by MikeSofaer** [comment]
We would like to know which KYC provider has checked them (we might have multiple providers) and the external ID for the person in that provider's system. We would also like to know the access level we want to provide, per Josh's comment above.

**Comment by levanhieuhust** [comment]
> We would like to know which KYC provider has checked them (we might have multiple providers) and the external ID for the person in that provider's system. We would also like to know the access level we want to provide, per Josh's comment above.

Thank you, I get it

**Comment by nghuyenthevinh2000** [comment]
@MikeSofaer @vuong177

Please look at the diagram above first.

How to add KYC addresses to chain can be potentially difficult. Here, I present 3 solutions that I think of:
1. Use a designated address (with secret seed phrase) to add KYC address to the chain. If seed is exposed, attacker can add rogue address to KYCed address list. This is dangerous.
* the address can be multisig address (hide 4 seed phrase, each seed phrase belongs to an independent verifier of KYC Id provided by KYC service). It decreases risk but the risk of getting all 4 seed phrases is still there.
2. This problem is very much alike getting off - chain information from oracle. We can build an entire oracle module like Terra, https://github.com/terra-money/classic-core/tree/main/x/oracle. But lengthly.
3. Using gov to add a batch of 100 address to KYC list (or per month). But not instantly.

Woud love to here more opinions.

**Comment by jlkershner** [comment]
Some things to think about:
(1) the worst case scenario for compromising the KYC sender address in
solutions 1 & 2 is that a bunch of spam KYC transactions happen.  That’s
much less dangerous than stealing coins because the KYC is merely a
permission to do something else, it doesn’t have intrinsic value.  If the
seed is compromised and unrecoverable, the whole KYC whitelist could be
abandoned and redone from scratch and there will always be an off chain
database associated with it that wouldn’t be compromised.  And, if it’s
just a few spam KYC transactions, they can always be reversed since the KYC
process has to be reversible.

(2) That last point is important, we need to be unable to remove someone
from the whitelist by sending another KYC transaction reversing it.  In the
same way that we need to be able to send multiple types of permissions via
the whitelist process, we need to be able to reverse them as well.

(3) We might also get some type of receipt from the KYC process that we
could append to the transaction as a memo.  If we do that, then fake
transactions wouldn’t have the data to put in the memo and would be easily
identifiable.

**Comment by StefanB90** [comment]
To be completed by 9/30

**Comment by StefanB90** [comment]
> @MikeSofaer @vuong177
> 
> Please look at the diagram above first.
> 
> How to add KYC addresses to chain can be potentially difficult. Here, I present 3 solutions that I think of:
> 
> 1. Use a designated address (with secret seed phrase) to add KYC address to the chain. If seed is exposed, attacker can add rogue address to KYCed address list. This is dangerous.
> 
> * the address can be multisig address (hide 4 seed phrase, each seed phrase belongs to an independent verifier of KYC Id provided by KYC service). It decreases risk but the risk of getting all 4 seed phrases is still there.
> 
> 2. This problem is very much alike getting off - chain information from oracle. We can build an entire oracle module like Terra, https://github.com/terra-money/classic-core/tree/main/x/oracle. But lengthly.
> 3. Using gov to add a batch of 100 address to KYC list (or per month). The founding team will broadcast approval if this add is legit. But not instantly.
> 
> Woud love to here more opinions.

we want option #1 with secret key held by fractal not pylons

**Comment by StefanB90** [comment]
at some point add governance for generalizing behavior and specifying keys to wallet addresses.

**Comment by StefanB90** [comment]
each public key is associated with a set of transactions.

Fractal resembles stripe server & ideally move to a single code path for these KYC transactions

**Comment by StefanB90** [comment]
access control matrix = single code path (use for any key)

**Comment by nghuyenthevinh2000** [comment]
https://github.com/Pylons-tech/pylons/blob/main/x/pylons/types/payment_processor.go#L24

**Comment by nghuyenthevinh2000** [comment]
@StefanB90 
can you give me a Fractal example of signature for a verified account

**Comment by levanhieuhust** [comment]
> each public key is associated with a set of transactions.
> 
> Fractal resembles stripe server & ideally move to a single code path for these KYC transactions

Hello @StefanB90 , Could you please give a Fractal secret key to verify? Thank you

**Comment by MikeSofaer** [comment]
> > each public key is associated with a set of transactions.
> > Fractal resembles stripe server & ideally move to a single code path for these KYC transactions
> 
> Hello @StefanB90 , Could you please give a Fractal secret key example to verify? Thank you

You should be able to generate a valid attestation by going through the KYC process on yourself.

**Comment by levanhieuhust** [comment]
> > > each public key is associated with a set of transactions.
> > > Fractal resembles stripe server & ideally move to a single code path for these KYC transactions
> > 
> > 
> > Hello @StefanB90 , Could you please give a Fractal secret key example to verify? Thank you
> 
> You should be able to generate a valid attestation by going through the KYC process on yourself.

Hello @MikeSofaer and @StefanB90 , I have tried with kyc process on fractal. I see that Fractal kyc process is accept metamask wallet with erc-20 and bep-20 address. So we can not use the fractal for kyc in cosmos. Could we use verify signature in cosmos sdk?

![image](https://user-images.githubusercontent.com/42901950/192466197-6cc2ad77-f536-4898-8956-25bc0262d494.png)
(The KYC process on fractal)

**Comment by MikeSofaer** [comment]
> > > > each public key is associated with a set of transactions.
> > > > Fractal resembles stripe server & ideally move to a single code path for these KYC transactions
> > > 
> > > 
> > > Hello @StefanB90 , Could you please give a Fractal secret key example to verify? Thank you
> > 
> > 
> > You should be able to generate a valid attestation by going through the KYC process on yourself.
> 
> Hello @MikeSofaer and @StefanB90 , I have tried with kyc process on fractal. I see that Fractal kyc process is accept metamask wallet with erc-20 and bep-20 address. So we can not use the fractal for kyc in cosmos. Could we use verify signature in cosmos sdk?
> 
> ![image](https://user-images.githubusercontent.com/42901950/192466197-6cc2ad77-f536-4898-8956-25bc0262d494.png) (The KYC process on fractal)
> 
> https://docs.developer.fractal.id/did-credentials (Fractal DID Credentials)

You are approaching this backwards. We are not trying to validate their wallet, we are trying to validate their IRL identity and then attach the validation receipt to their wallet.

**Comment by levanhieuhust** [comment]
> > > > > each public key is associated with a set of transactions.
> > > > > Fractal resembles stripe server & ideally move to a single code path for these KYC transactions
> > > > 
> > > > 
> > > > Hello @StefanB90 , Could you please give a Fractal secret key example to verify? Thank you
> > > 
> > > 
> > > You should be able to generate a valid attestation by going through the KYC process on yourself.
> > 
> > 
> > Hello @MikeSofaer and @StefanB90 , I have tried with kyc process on fractal. I see that Fractal kyc process is accept metamask wallet with erc-20 and bep-20 address. So we can not use the fractal for kyc in cosmos. Could we use verify signature in cosmos sdk?
> > ![image](https://user-images.githubusercontent.com/42901950/192466197-6cc2ad77-f536-4898-8956-25bc0262d494.png) (The KYC process on fractal)
> > https://docs.developer.fractal.id/did-credentials (Fractal DID Credentials)
> 
> You are approaching this backwards. We are not trying to validate their wallet, we are trying to validate their IRL identity and then attach the validation receipt to their wallet.

I still don't quite understand how to validate the URL. Here, I see that the metamask wallet will act as transaction confirmation and I can't implement it into the validation process.

**Comment by levanhieuhust** [comment]
Hello @MikeSofaer , Can you setup a call with Fractal to know for sure how to get infomation about IRL identity?

**Comment by nghuyenthevinh2000** [comment]
@MikeSofaer 

can you setup a call with Fractal side? during the process of working on this, there is a lot of question that documents don't have.

**Comment by MikeSofaer** [comment]
We can set up a call with Fractal but I think you are trying to build the wrong feature. There is nothing to do with Metamask. Users KYC with Fractal and submit their Fractal ID to the Pylons chain so we can look up who they are on the Fractal dashboard. That is all, there's no Metamask here.

**Comment by nghuyenthevinh2000** [comment]
> We can set up a call with Fractal but I think you are trying to build the wrong feature. There is nothing to do with Metamask. Users KYC with Fractal and submit their Fractal ID to the Pylons chain so we can look up who they are on the Fractal dashboard. That is all, there's no Metamask here.

Yep, I have just worked with Hieu and told him to use OAuth for verification, it has nothing to do with Metamask.

Still, there are some questions about OAuth that requires a meeting with Fractal.

**Comment by StefanB90** [comment]
need to confirm that no other party (including other Fractal customers) can view our users' KYC check
